export const NETZWERK_DATA_MAPPING = [
    // ==========================================
    // KAPITEL 1: UND WAS MACHST DU?
    // ==========================================
    {
        id: "a2-kapitel-1-1b-3c", num: "Kapitel 1 (1b-3c)", name: "Ausbildung & Leben", emoji: "💼",
        items: [
            { de: "die Ausbildung, -en", en: "training / education", hint: "1b" },
            { de: "die Bankkauffrau, -en", en: "bank clerk (f)", hint: "1b" },
            { de: "der Bankkaufmann, \"-er", en: "bank clerk (m)", hint: "1b" },
            { de: "fließend", en: "fluently", hint: "1b" },
            { de: "geboren", en: "born", hint: "1b" },
            { de: "geschieden", en: "divorced", hint: "1b" },
            { de: "reiten", en: "horseback riding", hint: "1b" },
            { de: "renovieren", en: "to renovate", hint: "1b" },
            { de: "der Rentner, -", en: "pensioner (m)", hint: "1b" },
            { de: "die Rentnerin, -nen", en: "pensioner (f)", hint: "1b" },
            { de: "an|melden", en: "to sign up", hint: "3a" },
            { de: "die Arbeit, -en", en: "work", hint: "3a" },
            { de: "beenden", en: "to finish", hint: "3a" },
            { de: "heiraten", en: "to marry", hint: "3a" },
            { de: "die Hochzeit, -en", en: "wedding", hint: "3a" },
            { de: "mieten", en: "to rent", hint: "3a" },
            { de: "organisieren", en: "to organise", hint: "3a" },
            { de: "teilnehmen", en: "to participate", hint: "3a" },
            { de: "der Verein, -e", en: "club", hint: "3a" },
            { de: "ab|schließen", en: "to finish", hint: "3c" }
        ]
    },
    {
        id: "a2-kapitel-1-6b-9d", num: "Kapitel 1 (6b-9d)", name: "Gesundheit & Restaurant", emoji: "🍽️",
        items: [
            { de: "die Grippe, -n", en: "flu", hint: "6b" },
            { de: "die Überstunde, -n", en: "overtime", hint: "6b" },
            { de: "weil", en: "because", hint: "7a" },
            { de: "ab|sagen", en: "to cancel", hint: "8b" },
            { de: "vor|schlagen", en: "to suggest", hint: "8b" },
            { de: "zu|sagen", en: "to accept", hint: "8b" },
            { de: "der Flohmarkt, \"-e", en: "flea market", hint: "8c" },
            { de: "die Angst, \"-e", en: "fear", hint: "9c" },
            { de: "aus|wählen", en: "to choose", hint: "9c" },
            { de: "der Eingang, \"-e", en: "entrance", hint: "9c" },
            { de: "empfangen", en: "to welcome", hint: "9c" },
            { de: "fühlen", en: "to feel", hint: "9c" },
            { de: "die Reservierung, -en", en: "reservation", hint: "9c" },
            { de: "der Sinn, -e", en: "sense", hint: "9c" },
            { de: "die Zigarette, -n", en: "cigarette", hint: "9c" },
            { de: "der Aufenthalt, -e", en: "stay", hint: "9d" }
        ]
    },

    // ==========================================
    // KAPITEL 2: NACH DER SCHULZEIT
    // ==========================================
    {
        id: "a2-kapitel-2-1a-3a", num: "Kapitel 2 (1a-3a)", name: "Berufe & Schulerinnerungen", emoji: "🎓",
        items: [
            { de: "die Schulzeit (Sg.)", en: "school days", hint: "1a" },
            { de: "der Altenpfleger, -", en: "geriatric nurse (m)", hint: "1b" },
            { de: "die Altenpflegerin, -nen", en: "geriatric nurse (f)", hint: "1b" },
            { de: "das Au-pair, -s", en: "au pair", hint: "1b" },
            { de: "die Krankenschwester, -n", en: "nurse", hint: "1b" },
            { de: "das Abitur (Sg.)", en: "A levels", hint: "1a ÜB" },
            { de: "der/die Auszubildende, -n", en: "apprentice", hint: "1a ÜB" },
            { de: "die Berufsschule, -n", en: "vocational school", hint: "1a ÜB" },
            { de: "das Zeugnis, -se", en: "report card", hint: "1a ÜB" },
            { de: "aus|schlafen", en: "to sleep in", hint: "1c" },
            { de: "die Erinnerung, -en", en: "memory", hint: "3a" },
            { de: "die Ferien (Pl.)", en: "holidays", hint: "3a" },
            { de: "streng", en: "strict", hint: "3a" },
            { de: "der Vokabeltest, -s", en: "vocabulary test", hint: "3a" }
        ]
    },
    {
        id: "a2-kapitel-2-7a-11a", num: "Kapitel 2 (7a-11a)", name: "Abschluss & Schulsystem", emoji: "🏫",
        items: [
            { de: "die Behinderung, -en", en: "disability", hint: "7a" },
            { de: "freiwillig", en: "voluntarily", hint: "7a" },
            { de: "der Rollstuhl, \"-e", en: "wheelchair", hint: "7a" },
            { de: "der Schulabschluss, \"-e", en: "graduation", hint: "7a" },
            { de: "ab|lehnen", en: "to refuse", hint: "8c" },
            { de: "die Meinung, -en", en: "opinion", hint: "8c" },
            { de: "zu|stimmen", en: "to agree", hint: "8c" },
            { de: "die Berufserfahrung (Sg.)", en: "work experience", hint: "9a" },
            { de: "unabhängig", en: "independent", hint: "9a" },
            { de: "die Weltreise, -n", en: "world trip", hint: "9a" },
            { de: "das Bundesland, \"-er", en: "state", hint: "11a" },
            { de: "das Gymnasium, Gymnasien", en: "grammar school", hint: "11a" },
            { de: "das Schulsystem, -e", en: "school system", hint: "11a" }
        ]
    },
    // ==========================================
    // KAPITEL 3: IMMER ONLINE?
    // ==========================================
    {
        id: "a2-kapitel-3-1a-3", num: "Kapitel 3 (1a-3)", name: "Digitale Medien & Geräte", emoji: "📱",
        items: [
            { de: "aus|probieren", en: "to try", hint: "1a" },
            { de: "chatten", en: "to chat", hint: "1a" },
            { de: "checken", en: "to check", hint: "1a" },
            { de: "downloaden", en: "to download", hint: "1a" },
            { de: "herunter|laden", en: "to download", hint: "1a" },
            { de: "kopieren", en: "to copy", hint: "1a" },
            { de: "der Link, -s", en: "link", hint: "1a" },
            { de: "posten", en: "to post", hint: "1a" },
            { de: "die VR-Brille, -n", en: "VR goggles", hint: "1a" },
            { de: "die Webseite, -n", en: "website", hint: "1a" },
            { de: "das E-Book, -s", en: "ebook", hint: "1b" },
            { de: "der Laptop, -s", en: "laptop", hint: "1b" },
            { de: "das Smartphone, -s", en: "smartphone", hint: "1b" },
            { de: "die Smartwatch, -es", en: "smartwatch", hint: "1b" },
            { de: "die Spielekonsole, -n", en: "video game console", hint: "1b" },
            { de: "der Bildschirm, -e", en: "screen", hint: "ÜB" },
            { de: "das Kabel, -", en: "cable", hint: "ÜB" },
            { de: "der Lautsprecher, -", en: "speaker", hint: "ÜB" },
            { de: "die Maus, \"-e", en: "mouse", hint: "ÜB" },
            { de: "das Tablet, -s", en: "tablet", hint: "ÜB" },
            { de: "die Tastatur, -en", en: "keyboard", hint: "ÜB" },
            { de: "an|klicken", en: "to click", hint: "ÜB" },
            { de: "löschen", en: "to delete", hint: "1b" },
            { de: "senden", en: "to send", hint: "1b" },
            { de: "weiter|leiten", en: "to forward", hint: "1b" },
            { de: "bloggen", en: "to blog", hint: "1a" },
            { de: "mailen", en: "to mail", hint: "1b" }
        ]
    },
    {
        id: "a2-kapitel-3-4c-8b", num: "Kapitel 3 (4c-8b)", name: "Vergleiche & Meinungen", emoji: "💻",
        items: [
            { de: "genauso", en: "just as", hint: "4c" },
            { de: "entwickeln", en: "to develop", hint: "5a" },
            { de: "gründen", en: "to found", hint: "5a" },
            { de: "programmieren", en: "to programme", hint: "5a" },
            { de: "schwierig", en: "difficult", hint: "5a" },
            { de: "das Start-Up, -s", en: "start-up", hint: "5a" },
            { de: "die Umfrage, -n", en: "survey", hint: "5a" },
            { de: "unbedingt", en: "absolutely", hint: "5a" },
            { de: "gewinnen", en: "to win", hint: "6b" },
            { de: "tippen", en: "to type", hint: "6d" },
            { de: "blöd", en: "daft", hint: "8b" },
            { de: "dass", en: "that", hint: "8b" },
            { de: "dumm", en: "stupid", hint: "8b" },
            { de: "der Enkel, -", en: "grandchild (m)", hint: "8b" },
            { de: "die Enkelin, -nen", en: "grandchild (f)", hint: "8b" },
            { de: "hoch|laden", en: "to upload", hint: "8b" },
            { de: "kritisch", en: "critical", hint: "8b" },
            { de: "mit|teilen", en: "to share", hint: "8b" },
            { de: "peinlich", en: "embarrassing", hint: "8b" },
            { de: "teilen", en: "to share", hint: "8b" },
            { de: "vorsichtig", en: "careful", hint: "8c" }
        ]
    },
    {
        id: "a2-kapitel-3-10-13e", num: "Kapitel 3 (10-13e)", name: "Filme, Kino & Kommunikation", emoji: "🎬",
        items: [
            { de: "flüstern", en: "to whisper", hint: "11a" },
            { de: "still", en: "silent", hint: "11a" },
            { de: "der Actionfilm, -e", en: "action film", hint: "12a" },
            { de: "der Fantasy-Film, -e", en: "fantasy film", hint: "12a" },
            { de: "die Komödie, -n", en: "comedy", hint: "12a" },
            { de: "der Krimi, -s", en: "crime novel", hint: "12a" },
            { de: "lachen", en: "to laugh", hint: "12a" },
            { de: "der Liebesfilm, -e", en: "romantic film", hint: "12a" },
            { de: "der Thriller, -", en: "thriller", hint: "12a" },
            { de: "weinen", en: "to cry", hint: "12a" },
            { de: "fröhlich", en: "happy", hint: "12b" },
            { de: "der Humor (Sg.)", en: "humour", hint: "12b" },
            { de: "die Kindheit (Sg.)", en: "childhood", hint: "12b" },
            { de: "plötzlich", en: "suddenly", hint: "12b" },
            { de: "das Schicksal, -e", en: "destiny", hint: "12b" },
            { de: "die Sorge, -n", en: "worry", hint: "12b" },
            { de: "sterben", en: "to die", hint: "12b" },
            { de: "das Talent, -e", en: "talent", hint: "12b" },
            { de: "der Witz, -e", en: "joke", hint: "12b" },
            { de: "die Freundschaft, -en", en: "friendship", hint: "12c" },
            { de: "die Hauptperson, -en", en: "protagonist", hint: "12c" },
            { de: "tot", en: "dead", hint: "12c" },
            { de: "die Filmmusik (Sg.)", en: "film music", hint: "13b" },
            { de: "die Handlung, -en", en: "plot", hint: "13c" },
            { de: "logisch", en: "logical", hint: "13c" },
            { de: "überhaupt", en: "at all", hint: "13c" },
            { de: "kommentieren", en: "to comment on sth", hint: "13c" },
            { de: "der Trailer, -", en: "trailer", hint: "13e" }
        ]
    },

    // ==========================================
    // KAPITEL 4: GROSSE UND KLEINE GEFÜHLE
    // ==========================================
    {
        id: "a2-kapitel-4-1a-4d", num: "Kapitel 4 (1a-4d)", name: "Emotionen & Ereignisse", emoji: "🎉",
        items: [
            { de: "aufgeregt", en: "excited", hint: "1a" },
            { de: "bestehen", en: "to pass", hint: "1a" },
            { de: "das Brautkleid, -er", en: "wedding dress", hint: "1a" },
            { de: "der Führerschein, -e", en: "driver's license", hint: "1a" },
            { de: "die Geburt, -en", en: "birth", hint: "1a" },
            { de: "das Gefühl, -e", en: "feeling", hint: "1a" },
            { de: "gratulieren", en: "to congratulate", hint: "1a" },
            { de: "die Medaille, -n", en: "medal", hint: "1a" },
            { de: "nervös", en: "nervous", hint: "1a" },
            { de: "schmücken", en: "to decorate", hint: "1a" },
            { de: "der Sieg, -e", en: "victory", hint: "1a" },
            { de: "stolz", en: "proud", hint: "1a" },
            { de: "wenn", en: "when / if", hint: "1a" },
            { de: "unglücklich", en: "unhappy", hint: "1a" },
            { de: "genervt", en: "annoyed", hint: "2" },
            { de: "traurig", en: "sad", hint: "3a" },
            { de: "die Laune (Sg.)", en: "mood", hint: "3e" },
            { de: "die Absage, -n", en: "cancellation", hint: "3e" },
            { de: "das Brautpaar, -e", en: "bride and groom", hint: "4a" },
            { de: "die Dankeskarte, -n", en: "thank-you card", hint: "4a" },
            { de: "die Glückwunschkarte, -n", en: "congratulations card", hint: "4a" },
            { de: "die Liebe (Sg.)", en: "love", hint: "4a" },
            { de: "die Zukunft (Sg.)", en: "future", hint: "4a" },
            { de: "bedanken (sich)", en: "to thank", hint: "4c" }
        ]
    },
    {
        id: "a2-kapitel-4-5a-9b", num: "Kapitel 4 (5a-9b)", name: "Reflexivverben & Stimmungen", emoji: "💭",
        items: [
            { de: "ärgern (sich)", en: "to be annoyed", hint: "5c" },
            { de: "entscheiden (sich)", en: "to decide", hint: "5c" },
            { de: "erinnern (sich)", en: "to remember", hint: "5c" },
            { de: "hoffen", en: "to hope", hint: "5c" },
            { de: "unterhalten (sich)", en: "to talk", hint: "5c" },
            { de: "aus|ruhen (sich)", en: "to rest", hint: "7a" },
            { de: "langweilen (sich)", en: "to be bored", hint: "7a" },
            { de: "streiten (sich)", en: "to argue", hint: "7a" },
            { de: "das Bedauern (Sg.)", en: "regret", hint: "8b" },
            { de: "beruhigen", en: "to calm down", hint: "8b" },
            { de: "die Freude, -n", en: "joy", hint: "8b" },
            { de: "riesig", en: "vast / huge", hint: "8b" },
            { de: "wahr", en: "true", hint: "8b" },
            { de: "unangenehm", en: "uncomfortable", hint: "8c" },
            { de: "ärgerlich", en: "annoyed", hint: "9a" },
            { de: "emotional", en: "emotional", hint: "9a" },
            { de: "gestresst", en: "stressed", hint: "9a" },
            { de: "die Emotion, -en", en: "emotion", hint: "9b" },
            { de: "erkennen", en: "to recognize", hint: "9b" }
        ]
    },
    {
        id: "a2-kapitel-4-10a-12b", num: "Kapitel 4 (10a-12b)", name: "Event, Kultur & Wohlfühlen", emoji: "⚓",
        items: [
            { de: "bewundern", en: "to admire", hint: "10a" },
            { de: "das Feuerwerk, -e", en: "fireworks", hint: "10a" },
            { de: "die Segelregatta, Segelregatten", en: "sailing regatta", hint: "10a" },
            { de: "weltweit", en: "worldwide", hint: "10a" },
            { de: "gestalten", en: "to design", hint: "10d" },
            { de: "kostenlos", en: "free", hint: "10d" },
            { de: "an|bieten", en: "to offer", hint: "11a" },
            { de: "aufregend", en: "exciting", hint: "11a" },
            { de: "fremd", en: "alien / foreign", hint: "11a" },
            { de: "gewöhnen (sich)", en: "to get used to", hint: "11a" },
            { de: "hilfsbereit", en: "helpful", hint: "11a" },
            { de: "inzwischen", en: "meanwhile", hint: "11a" },
            { de: "ordentlich", en: "tidy", hint: "11a" },
            { de: "schlimm", en: "bad", hint: "11a" },
            { de: "die Währung, -en", en: "currency", hint: "11a" },
            { de: "wohl-fühlen (sich)", en: "to feel comfortable", hint: "11a" },
            { de: "das Wohnheim, -e", en: "dorm", hint: "11a" },
            { de: "unordentlich", en: "messy", hint: "12a ÜB" },
            { de: "unsympathisch", en: "disagreeable", hint: "12a ÜB" },
            { de: "unwichtig", en: "unimportant", hint: "12a ÜB" },
            { de: "verspätet", en: "late", hint: "12a ÜB" },
            { de: "aus|tauschen", en: "to exchange", hint: "12b" }
        ]
    },
    // ==========================================
    // KAPITEL 5: LEBEN IN DER STADT
    // ==========================================
    {
        id: "a2-kapitel-5-1a-1b", num: "Kapitel 5 (1a-1b)", name: "Ämter, Müll & Stadtpflege", emoji: "🏛️",
        items: [
            { de: "das Amt, \"-er", en: "department", hint: "1a" },
            { de: "die Behörde, -n", en: "authority / agency", hint: "1a" },
            { de: "die Müllabfuhr (Sg.)", en: "garbage disposal", hint: "1a" },
            { de: "öffentlich", en: "public", hint: "1a" },
            { de: "die Polizei (Sg.)", en: "police", hint: "1a" },
            { de: "die Straßenreinigung (Sg.)", en: "street cleaning", hint: "1a" },
            { de: "das Verkehrsmittel, -", en: "(means of) transportation", hint: "1a" },
            { de: "der Antrag, \"-e", en: "application", hint: "1b" },
            { de: "auf|räumen", en: "to clean up", hint: "1b" },
            { de: "aus|füllen", en: "to fill (in)", hint: "1b" },
            { de: "der Beamte, -n", en: "official (m)", hint: "1b" },
            { de: "die Beamtin, -nen", en: "official (f)", hint: "1b" },
            { de: "bedienen", en: "to serve", hint: "1b" },
            { de: "beschützen", en: "to protect", hint: "1b" },
            { de: "das Dokument, -e", en: "document", hint: "1b" },
            { de: "der Fahrer, -", en: "driver (m)", hint: "1b" },
            { de: "die Fahrerin, -nen", en: "driver (f)", hint: "1b" },
            { de: "genehmigen", en: "to approve", hint: "1b" },
            { de: "kümmern (sich)", en: "to take care of", hint: "1b" },
            { de: "leeren", en: "to empty", hint: "1b" },
            { de: "der Müll (Sg.)", en: "rubbish", hint: "1b" },
            { de: "die Mülltonne, -n", en: "rubbish bin", hint: "1b" },
            { de: "die Operation, -en", en: "operation", hint: "1b" },
            { de: "pflegen", en: "to take care of", hint: "1b" }
        ]
    },
    {
        id: "a2-kapitel-5-2a-3c", num: "Kapitel 5 (2a-3c)", name: "Jobsuche & Vorstellungsgespräch", emoji: "💼",
        items: [
            { de: "aus|geben", en: "to spend", hint: "2a" },
            { de: "die Aushilfe, -n", en: "temporary help", hint: "2a" },
            { de: "der Dom, -e", en: "cathedral", hint: "2a" },
            { de: "dringend", en: "urgent", hint: "2a" },
            { de: "erledigen", en: "to take care of", hint: "2a" },
            { de: "eröffnen", en: "to open", hint: "2a" },
            { de: "der Lohn, \"-e", en: "wage", hint: "2a" },
            { de: "vor|stellen (sich)", en: "to imagine", hint: "2a" },
            { de: "das Vorstellungsgespräch, -e", en: "job interview", hint: "2a ÜB" },
            { de: "bewerben", en: "to apply", hint: "3a" },
            { de: "die Kenntnis, -se", en: "knowledge", hint: "3a" },
            { de: "die Stellenanzeige, -n", en: "job advertisement", hint: "3a" },
            { de: "die Teilzeit (Sg.)", en: "part-time", hint: "3a" },
            { de: "die Unterlagen (Pl.)", en: "documents", hint: "3a" },
            { de: "die Bezahlung, -en", en: "payment", hint: "3c" },
            { de: "erwarten", en: "to expect", hint: "3c" },
            { de: "bunt", en: "colourful", hint: "3c" },
            { de: "spontan", en: "spontaneous", hint: "3c" }
        ]
    },
    {
        id: "a2-kapitel-5-4a-6d", num: "Kapitel 5 (4a-6d)", name: "Behördengänge & Dokumente", emoji: "📄",
        items: [
            { de: "ab|geben", en: "to submit", hint: "5a" },
            { de: "beantragen", en: "to apply for", hint: "5a" },
            { de: "der Betrag, \"-e", en: "amount", hint: "5a" },
            { de: "der Diebstahl, \"-e", en: "theft", hint: "5a" },
            { de: "die Einbürgerung, -en", en: "naturalisation", hint: "5a" },
            { de: "die Geldbörse, -n", en: "purse", hint: "5a" },
            { de: "der Kredit, -e", en: "loan", hint: "5a" },
            { de: "melden", en: "to report", hint: "5a" },
            { de: "der Personalausweis, -e", en: "ID card", hint: "5a" },
            { de: "verlängern", en: "to extend", hint: "5a" },
            { de: "die Bankkarte, -n", en: "bank card", hint: "5c" },
            { de: "ab|heben", en: "to withdraw", hint: "5d" },
            { de: "die Grenze, -n", en: "border", hint: "5d" },
            { de: "gültig", en: "valid", hint: "5e" },
            { de: "das Visum, Visa", en: "visa", hint: "5e" },
            { de: "sperren", en: "to block", hint: "6a" },
            { de: "aus|drucken", en: "to print", hint: "6c" },
            { de: "bitten", en: "to ask for sth", hint: "6c" },
            { de: "funktionieren", en: "to work", hint: "6c" },
            { de: "der Gefallen, -", en: "favour", hint: "6c" },
            { de: "leihen", en: "to borrow", hint: "6c" }
        ]
    },
    {
        id: "a2-kapitel-5-8a-8b", num: "Kapitel 5 (8a-8b)", name: "Rund um den Wiener Ring", emoji: "🗺️",
        items: [
            { de: "der Stadtplan, \"-e", en: "city map", hint: "8a" },
            { de: "der/die Angestellte, -n", en: "employee", hint: "8b" },
            { de: "die Disco, -s", en: "disco", hint: "8b" },
            { de: "das Drama, Dramen", en: "drama", hint: "8b" },
            { de: "die Entspannung (Sg.)", en: "relaxation", hint: "8b" },
            { de: "das Gebäude, -", en: "building", hint: "8b" },
            { de: "das Gesetz, -e", en: "law", hint: "8b" },
            { de: "der Kaiser, -", en: "emperor", hint: "8b" },
            { de: "die Kaiserin, -nen", en: "empress", hint: "8b" },
            { de: "der Maler, -", en: "painter (m)", hint: "8b" },
            { de: "die Malerin, -nen", en: "painter (f)", hint: "8b" },
            { de: "das Parlament, -e", en: "parliament", hint: "8b" },
            { de: "der Politiker, -", en: "politician (m)", hint: "8b" },
            { de: "die Politikerin, -nen", en: "politician (f)", hint: "8b" },
            { de: "die Ruhe (Sg.)", en: "quiet", hint: "8b" },
            { de: "der Tourist, -en", en: "tourist (m)", hint: "8b" },
            { de: "die Touristin, -nen", en: "tourist (f)", hint: "8b" },
            { de: "die Verwaltung (Sg.)", en: "administration", hint: "8b" }
        ]
    },

    // ==========================================
    // KAPITEL 6: ARBEITSWELTEN
    // ==========================================
    {
        id: "a2-kapitel-6-1b-3a", num: "Kapitel 6 (1b-3a)", name: "Alltag & Geschäftsreise", emoji: "🚆",
        items: [
            { de: "der Ärger (Sg.)", en: "anger", hint: "1b" },
            { de: "beeilen (sich)", en: "to hurry (up)", hint: "1b" },
            { de: "klappen", en: "to work / succeed", hint: "2a" },
            { de: "die Rückfahrt (Sg.)", en: "return journey", hint: "2a" },
            { de: "beraten", en: "to advise", hint: "2c" },
            { de: "ein|halten", en: "to adhere (to an appointment)", hint: "2c" },
            { de: "die Tätigkeit, -en", en: "occupation", hint: "2c" },
            { de: "die Vokabel, -n", en: "word", hint: "2c" },
            { de: "die Geschäftsreise, -n", en: "business trip", hint: "3a" },
            { de: "zurück|kommen", en: "to return", hint: "3a" },
            { de: "die Hinfahrt (Sg.)", en: "journey there", hint: "3a" },
            { de: "die Bahn, -en", en: "train", hint: "3a ÜB" },
            { de: "die Bahnhofshalle, -n", en: "station hall", hint: "3a ÜB" },
            { de: "die Durchsage, -n", en: "announcement", hint: "3a ÜB" },
            { de: "der Fahrgast, \"-e", en: "passenger", hint: "3a ÜB" },
            { de: "der Fahrplan, \"-e", en: "timetable", hint: "3a ÜB" },
            { de: "der Schalter, -", en: "counter", hint: "3a ÜB" },
            { de: "der Wagen, -", en: "car / carriage", hint: "3a ÜB" },
            { de: "die Zugverbindung, -en", en: "train connection", hint: "4a" },
            { de: "der Fahrkartenschalter, -", en: "booking office", hint: "4b" },
            { de: "der Gang, \"-e", en: "aisle", hint: "4b" }
        ]
    },
    {
        id: "a2-kapitel-6-5a-6", num: "Kapitel 6 (5a-6)", name: "Kultur & Abendprogramm", emoji: "🎟️",
        items: [
            { de: "das Abend-Programm, -e", en: "evening programme", hint: "5a" },
            { de: "das Album, Alben", en: "album", hint: "5a" },
            { de: "die Band, -s", en: "band", hint: "5a" },
            { de: "erleben", en: "to experience", hint: "5a" },
            { de: "die Ermäßigung, -en", en: "discount", hint: "5a" },
            { de: "der Feiertag, -e", en: "holiday", hint: "5a" },
            { de: "der Musiker, -", en: "musician (m)", hint: "5a" },
            { de: "die Musikerin, -nen", en: "musician (f)", hint: "5a" },
            { de: "der Sänger, -", en: "singer (m)", hint: "5a" },
            { de: "die Sängerin, -nen", en: "singer (f)", hint: "5a" },
            { de: "der Tagesgast, \"-e", en: "one-day visitor", hint: "5a" },
            { de: "der Trainer, -", en: "trainer (m)", hint: "5a" },
            { de: "die Trainerin, -nen", en: "trainer (f)", hint: "5a" },
            { de: "professionell", en: "professional", hint: "5c" },
            { de: "fantastisch", en: "fantastic", hint: "6" },
            { de: "das Kunstmuseum, Kunstmuseen", en: "art museum", hint: "6" },
            { de: "preiswert", en: "cheap / good value", hint: "6" }
        ]
    },
    {
        id: "a2-kapitel-6-7a-9b", num: "Kapitel 6 (7a-9b)", name: "Karriere & Berufswechsel", emoji: "👨‍⚕️",
        items: [
            { de: "auf keinen Fall", en: "under no circumstances", hint: "7a" },
            { de: "bereuen", en: "to regret", hint: "7a" },
            { de: "beruflich", en: "professional", hint: "7a" },
            { de: "der Berufswechsel, -", en: "career change", hint: "7a" },
            { de: "die Chance, -n", en: "opportunity", hint: "7a" },
            { de: "erfolgreich", en: "successful", hint: "7a" },
            { de: "finanziell", en: "financial", hint: "7a" },
            { de: "die Freiheit (Sg.)", en: "freedom", hint: "7a" },
            { de: "das Gehalt, \"-er", en: "salary", hint: "7a" },
            { de: "der Jobwechsel, -", en: "job change", hint: "7a" },
            { de: "der Lastwagen, -", en: "truck", hint: "7a" },
            { de: "der Leiter, -", en: "director (m)", hint: "7a" },
            { de: "die Leiterin, -nen", en: "director (f)", hint: "7a" },
            { de: "der Lkw, -s", en: "truck", hint: "7a" },
            { de: "der Neuanfang, \"-e", en: "new beginning", hint: "7a" },
            { de: "das Risiko, Risiken", en: "risk", hint: "7a" },
            { de: "selbstständig", en: "independent / freelance", hint: "7a" },
            { de: "der Übersetzer, -", en: "translator (m)", hint: "7a" },
            { de: "die Übersetzerin, -nen", en: "translator (f)", hint: "7a" },
            { de: "die Umwelt (Sg.)", en: "environment", hint: "7c" },
            { de: "schwanger", en: "pregnant", hint: "8b" },
            { de: "der Berufswunsch, \"-e", en: "career goal", hint: "8c" }
        ]
    },
    {
        id: "a2-kapitel-6-11b-13a", num: "Kapitel 6 (11b-13a)", name: "Telefonat & Digitale Arbeitswelt", emoji: "📞",
        items: [
            { de: "der Anrufbeantworter, -", en: "answering machine", hint: "11b" },
            { de: "deutlich", en: "distinct / clear", hint: "11b" },
            { de: "hektisch", en: "hectic", hint: "11b" },
            { de: "konzentrieren (sich)", en: "to concentrate", hint: "11b" },
            { de: "lächeln", en: "to smile", hint: "11b" },
            { de: "stören", en: "to disturb", hint: "11b" },
            { de: "das Telefonat, -e", en: "telephone call", hint: "11b" },
            { de: "der Anrufer, -", en: "caller (m)", hint: "12b" },
            { de: "die Anruferin, -nen", en: "caller (f)", hint: "12b" },
            { de: "aus|richten", en: "to pass on sth to sb", hint: "12b" },
            { de: "hinterlassen", en: "to leave (behind)", hint: "12b" },
            { de: "die Rückmeldung, -en", en: "response", hint: "12b" },
            { de: "zurück|rufen", en: "to call sb back", hint: "12b" },
            { de: "verändern", en: "to change", hint: "13a" },
            { de: "befristet", en: "temporary", hint: "13a" },
            { de: "die Digitalisierung (Sg.)", en: "digitisation", hint: "13a" },
            { de: "erreichbar", en: "reachable", hint: "13a" },
            { de: "die Fabrik, -en", en: "factory", hint: "13a" },
            { de: "das Grundeinkommen, -", en: "basic income", hint: "13a" },
            { de: "die Kompetenz, -en", en: "expertise", hint: "13a" },
            { de: "die Maschine, -n", en: "machine", hint: "13a" },
            { de: "der Roboter, -", en: "robot", hint: "13a" },
            { de: "die Videokonferenz, -en", en: "video conference", hint: "13a" },
            { de: "virtuell", en: "virtual", hint: "13a" }
        ]
    },
    // ==========================================
    // KAPITEL 5: LEBEN IN DER STADT
    // ==========================================
    {
        id: "a2-kapitel-5-1a-1b", num: "Kapitel 5 (1a-1b)", name: "Ämter, Müll & Stadtpflege", emoji: "🏛️",
        items: [
            { de: "das Amt, \"-er", en: "department", hint: "1a" },
            { de: "die Behörde, -n", en: "authority / agency", hint: "1a" },
            { de: "die Müllabfuhr (Sg.)", en: "garbage disposal", hint: "1a" },
            { de: "öffentlich", en: "public", hint: "1a" },
            { de: "die Polizei (Sg.)", en: "police", hint: "1a" },
            { de: "die Straßenreinigung (Sg.)", en: "street cleaning", hint: "1a" },
            { de: "das Verkehrsmittel, -", en: "(means of) transportation", hint: "1a" },
            { de: "der Antrag, \"-e", en: "application", hint: "1b" },
            { de: "auf|räumen", en: "to clean up", hint: "1b" },
            { de: "aus|füllen", en: "to fill (in)", hint: "1b" },
            { de: "der Beamte, -n", en: "official (m)", hint: "1b" },
            { de: "die Beamtin, -nen", en: "official (f)", hint: "1b" },
            { de: "bedienen", en: "to serve", hint: "1b" },
            { de: "beschützen", en: "to protect", hint: "1b" },
            { de: "das Dokument, -e", en: "document", hint: "1b" },
            { de: "der Fahrer, -", en: "driver (m)", hint: "1b" },
            { de: "die Fahrerin, -nen", en: "driver (f)", hint: "1b" },
            { de: "genehmigen", en: "to approve", hint: "1b" },
            { de: "kümmern (sich)", en: "to take care of", hint: "1b" },
            { de: "leeren", en: "to empty", hint: "1b" },
            { de: "der Müll (Sg.)", en: "rubbish", hint: "1b" },
            { de: "die Mülltonne, -n", en: "rubbish bin", hint: "1b" },
            { de: "die Operation, -en", en: "operation", hint: "1b" },
            { de: "pflegen", en: "to take care of", hint: "1b" }
        ]
    },
    {
        id: "a2-kapitel-5-2a-3c", num: "Kapitel 5 (2a-3c)", name: "Jobsuche & Vorstellungsgespräch", emoji: "💼",
        items: [
            { de: "aus|geben", en: "to spend", hint: "2a" },
            { de: "die Aushilfe, -n", en: "temporary help", hint: "2a" },
            { de: "der Dom, -e", en: "cathedral", hint: "2a" },
            { de: "dringend", en: "urgent", hint: "2a" },
            { de: "erledigen", en: "to take care of", hint: "2a" },
            { de: "eröffnen", en: "to open", hint: "2a" },
            { de: "der Lohn, \"-e", en: "wage", hint: "2a" },
            { de: "vor|stellen (sich)", en: "to imagine", hint: "2a" },
            { de: "das Vorstellungsgespräch, -e", en: "job interview", hint: "2a ÜB" },
            { de: "bewerben", en: "to apply", hint: "3a" },
            { de: "die Kenntnis, -se", en: "knowledge", hint: "3a" },
            { de: "die Stellenanzeige, -n", en: "job advertisement", hint: "3a" },
            { de: "die Teilzeit (Sg.)", en: "part-time", hint: "3a" },
            { de: "die Unterlagen (Pl.)", en: "documents", hint: "3a" },
            { de: "die Bezahlung, -en", en: "payment", hint: "3c" },
            { de: "erwarten", en: "to expect", hint: "3c" },
            { de: "bunt", en: "colourful", hint: "3c" },
            { de: "spontan", en: "spontaneous", hint: "3c" }
        ]
    },
    {
        id: "a2-kapitel-5-4a-6d", num: "Kapitel 5 (4a-6d)", name: "Behördengänge & Dokumente", emoji: "📄",
        items: [
            { de: "ab|geben", en: "to submit", hint: "5a" },
            { de: "beantragen", en: "to apply for", hint: "5a" },
            { de: "der Betrag, \"-e", en: "amount", hint: "5a" },
            { de: "der Diebstahl, \"-e", en: "theft", hint: "5a" },
            { de: "die Einbürgerung, -en", en: "naturalisation", hint: "5a" },
            { de: "die Geldbörse, -n", en: "purse", hint: "5a" },
            { de: "der Kredit, -e", en: "loan", hint: "5a" },
            { de: "melden", en: "to report", hint: "5a" },
            { de: "der Personalausweis, -e", en: "ID card", hint: "5a" },
            { de: "verlängern", en: "to extend", hint: "5a" },
            { de: "die Bankkarte, -n", en: "bank card", hint: "5c" },
            { de: "ab|heben", en: "to withdraw", hint: "5d" },
            { de: "die Grenze, -n", en: "border", hint: "5d" },
            { de: "gültig", en: "valid", hint: "5e" },
            { de: "das Visum, Visa", en: "visa", hint: "5e" },
            { de: "sperren", en: "to block", hint: "6a" },
            { de: "aus|drucken", en: "to print", hint: "6c" },
            { de: "bitten", en: "to ask for sth", hint: "6c" },
            { de: "funktionieren", en: "to work", hint: "6c" },
            { de: "der Gefallen, -", en: "favour", hint: "6c" },
            { de: "leihen", en: "to borrow", hint: "6c" }
        ]
    },
    {
        id: "a2-kapitel-5-8a-8b", num: "Kapitel 5 (8a-8b)", name: "Rund um den Wiener Ring", emoji: "🗺️",
        items: [
            { de: "der Stadtplan, \"-e", en: "city map", hint: "8a" },
            { de: "der/die Angestellte, -n", en: "employee", hint: "8b" },
            { de: "die Disco, -s", en: "disco", hint: "8b" },
            { de: "das Drama, Dramen", en: "drama", hint: "8b" },
            { de: "die Entspannung (Sg.)", en: "relaxation", hint: "8b" },
            { de: "das Gebäude, -", en: "building", hint: "8b" },
            { de: "das Gesetz, -e", en: "law", hint: "8b" },
            { de: "der Kaiser, -", en: "emperor", hint: "8b" },
            { de: "die Kaiserin, -nen", en: "empress", hint: "8b" },
            { de: "der Maler, -", en: "painter (m)", hint: "8b" },
            { de: "die Malerin, -nen", en: "painter (f)", hint: "8b" },
            { de: "das Parlament, -e", en: "parliament", hint: "8b" },
            { de: "der Politiker, -", en: "politician (m)", hint: "8b" },
            { de: "die Politikerin, -nen", en: "politician (f)", hint: "8b" },
            { de: "die Ruhe (Sg.)", en: "quiet", hint: "8b" },
            { de: "der Tourist, -en", en: "tourist (m)", hint: "8b" },
            { de: "die Touristin, -nen", en: "tourist (f)", hint: "8b" },
            { de: "die Verwaltung (Sg.)", en: "administration", hint: "8b" }
        ]
    },

    // ==========================================
    // KAPITEL 6: ARBEITSWELTEN
    // ==========================================
    {
        id: "a2-kapitel-6-1b-3a", num: "Kapitel 6 (1b-3a)", name: "Alltag & Geschäftsreise", emoji: "🚆",
        items: [
            { de: "der Ärger (Sg.)", en: "anger", hint: "1b" },
            { de: "beeilen (sich)", en: "to hurry (up)", hint: "1b" },
            { de: "klappen", en: "to work / succeed", hint: "2a" },
            { de: "die Rückfahrt (Sg.)", en: "return journey", hint: "2a" },
            { de: "beraten", en: "to advise", hint: "2c" },
            { de: "ein|halten", en: "to adhere (to an appointment)", hint: "2c" },
            { de: "die Tätigkeit, -en", en: "occupation", hint: "2c" },
            { de: "die Vokabel, -n", en: "word", hint: "2c" },
            { de: "die Geschäftsreise, -n", en: "business trip", hint: "3a" },
            { de: "zurück|kommen", en: "to return", hint: "3a" },
            { de: "die Hinfahrt (Sg.)", en: "journey there", hint: "3a" },
            { de: "die Bahn, -en", en: "train", hint: "3a ÜB" },
            { de: "die Bahnhofshalle, -n", en: "station hall", hint: "3a ÜB" },
            { de: "die Durchsage, -n", en: "announcement", hint: "3a ÜB" },
            { de: "der Fahrgast, \"-e", en: "passenger", hint: "3a ÜB" },
            { de: "der Fahrplan, \"-e", en: "timetable", hint: "3a ÜB" },
            { de: "der Schalter, -", en: "counter", hint: "3a ÜB" },
            { de: "der Wagen, -", en: "car / carriage", hint: "3a ÜB" },
            { de: "die Zugverbindung, -en", en: "train connection", hint: "4a" },
            { de: "der Fahrkartenschalter, -", en: "booking office", hint: "4b" },
            { de: "der Gang, \"-e", en: "aisle", hint: "4b" }
        ]
    },
    {
        id: "a2-kapitel-6-5a-6", num: "Kapitel 6 (5a-6)", name: "Kultur & Abendprogramm", emoji: "🎟️",
        items: [
            { de: "das Abend-Programm, -e", en: "evening programme", hint: "5a" },
            { de: "das Album, Alben", en: "album", hint: "5a" },
            { de: "die Band, -s", en: "band", hint: "5a" },
            { de: "erleben", en: "to experience", hint: "5a" },
            { de: "die Ermäßigung, -en", en: "discount", hint: "5a" },
            { de: "der Feiertag, -e", en: "holiday", hint: "5a" },
            { de: "der Musiker, -", en: "musician (m)", hint: "5a" },
            { de: "die Musikerin, -nen", en: "musician (f)", hint: "5a" },
            { de: "der Sänger, -", en: "singer (m)", hint: "5a" },
            { de: "die Sängerin, -nen", en: "singer (f)", hint: "5a" },
            { de: "der Tagesgast, \"-e", en: "one-day visitor", hint: "5a" },
            { de: "der Trainer, -", en: "trainer (m)", hint: "5a" },
            { de: "die Trainerin, -nen", en: "trainer (f)", hint: "5a" },
            { de: "professionell", en: "professional", hint: "5c" },
            { de: "fantastisch", en: "fantastic", hint: "6" },
            { de: "das Kunstmuseum, Kunstmuseen", en: "art museum", hint: "6" },
            { de: "preiswert", en: "cheap / good value", hint: "6" }
        ]
    },
    {
        id: "a2-kapitel-6-7a-9b", num: "Kapitel 6 (7a-9b)", name: "Karriere & Berufswechsel", emoji: "👨‍⚕️",
        items: [
            { de: "auf keinen Fall", en: "under no circumstances", hint: "7a" },
            { de: "bereuen", en: "to regret", hint: "7a" },
            { de: "beruflich", en: "professional", hint: "7a" },
            { de: "der Berufswechsel, -", en: "career change", hint: "7a" },
            { de: "die Chance, -n", en: "opportunity", hint: "7a" },
            { de: "erfolgreich", en: "successful", hint: "7a" },
            { de: "finanziell", en: "financial", hint: "7a" },
            { de: "die Freiheit (Sg.)", en: "freedom", hint: "7a" },
            { de: "das Gehalt, \"-er", en: "salary", hint: "7a" },
            { de: "der Jobwechsel, -", en: "job change", hint: "7a" },
            { de: "der Lastwagen, -", en: "truck", hint: "7a" },
            { de: "der Leiter, -", en: "director (m)", hint: "7a" },
            { de: "die Leiterin, -nen", en: "director (f)", hint: "7a" },
            { de: "der Lkw, -s", en: "truck", hint: "7a" },
            { de: "der Neuanfang, \"-e", en: "new beginning", hint: "7a" },
            { de: "das Risiko, Risiken", en: "risk", hint: "7a" },
            { de: "selbstständig", en: "independent / freelance", hint: "7a" },
            { de: "der Übersetzer, -", en: "translator (m)", hint: "7a" },
            { de: "die Übersetzerin, -nen", en: "translator (f)", hint: "7a" },
            { de: "die Umwelt (Sg.)", en: "environment", hint: "7c" },
            { de: "schwanger", en: "pregnant", hint: "8b" },
            { de: "der Berufswunsch, \"-e", en: "career goal", hint: "8c" }
        ]
    },
    {
        id: "a2-kapitel-6-11b-13a", num: "Kapitel 6 (11b-13a)", name: "Telefonat & Digitale Arbeitswelt", emoji: "📞",
        items: [
            { de: "der Anrufbeantworter, -", en: "answering machine", hint: "11b" },
            { de: "deutlich", en: "distinct / clear", hint: "11b" },
            { de: "hektisch", en: "hectic", hint: "11b" },
            { de: "konzentrieren (sich)", en: "to concentrate", hint: "11b" },
            { de: "lächeln", en: "to smile", hint: "11b" },
            { de: "stören", en: "to disturb", hint: "11b" },
            { de: "das Telefonat, -e", en: "telephone call", hint: "11b" },
            { de: "der Anrufer, -", en: "caller (m)", hint: "12b" },
            { de: "die Anruferin, -nen", en: "caller (f)", hint: "12b" },
            { de: "aus|richten", en: "to pass on sth to sb", hint: "12b" },
            { de: "hinterlassen", en: "to leave (behind)", hint: "12b" },
            { de: "die Rückmeldung, -en", en: "response", hint: "12b" },
            { de: "zurück|rufen", en: "to call sb back", hint: "12b" },
            { de: "verändern", en: "to change", hint: "13a" },
            { de: "befristet", en: "temporary", hint: "13a" },
            { de: "die Digitalisierung (Sg.)", en: "digitisation", hint: "13a" },
            { de: "erreichbar", en: "reachable", hint: "13a" },
            { de: "die Fabrik, -en", en: "factory", hint: "13a" },
            { de: "das Grundeinkommen, -", en: "basic income", hint: "13a" },
            { de: "die Kompetenz, -en", en: "expertise", hint: "13a" },
            { de: "die Maschine, -n", en: "machine", hint: "13a" },
            { de: "der Roboter, -", en: "robot", hint: "13a" },
            { de: "die Videokonferenz, -en", en: "video conference", hint: "13a" },
            { de: "virtuell", en: "virtual", hint: "13a" }
        ]
    },
    // ==========================================
    // KAPITEL 7: GANZ SCHÖN MOBIL
    // ==========================================
    {
        id: "a2-kapitel-7-1a-3c", num: "Kapitel 7 (1a-3c)", name: "Verkehr, Panne & Auto", emoji: "🚗",
        items: [
            { de: "der Konzertsaal, -säle", en: "concert hall", hint: "1a" },
            { de: "versprechen", en: "to promise", hint: "1 ÜB" },
            { de: "vor|haben", en: "to plan", hint: "1 ÜB" },
            { de: "die Ampel, -n", en: "traffic light", hint: "1 ÜB" },
            { de: "halten", en: "to stop", hint: "1 ÜB" },
            { de: "der Motor, -en", en: "motor", hint: "1 ÜB" },
            { de: "die Panne, -n", en: "car trouble", hint: "1 ÜB" },
            { de: "der Parkplatz, \"-e", en: "parking lot", hint: "1 ÜB" },
            { de: "der Reifen, -", en: "tire", hint: "1 ÜB" },
            { de: "der Stau, -s", en: "traffic jam", hint: "1 ÜB" },
            { de: "das Navi, -s", en: "satnav", hint: "2" },
            { de: "das Parkhaus, \"-er", en: "parking garage", hint: "2" },
            { de: "tanken", en: "to refuel", hint: "3" },
            { de: "ab|fliegen", en: "to depart", hint: "3c ÜB" },
            { de: "der Abflug, \"-e", en: "departing flight", hint: "3c ÜB" },
            { de: "das Benzin (Sg.)", en: "petrol", hint: "3c ÜB" },
            { de: "bremsen", en: "to brake", hint: "3c ÜB" },
            { de: "buchen", en: "to book", hint: "3c ÜB" },
            { de: "das Kennzeichen, -", en: "license plate", hint: "3c ÜB" },
            { de: "die Monatskarte, -n", en: "monthly ticket", hint: "3c ÜB" },
            { de: "parken", en: "to park", hint: "3c ÜB" },
            { de: "die Tankstelle, -n", en: "petrol station", hint: "3c ÜB" },
            { de: "die Versicherung, -en", en: "insurance", hint: "3c ÜB" }
        ]
    },
    {
        id: "a2-kapitel-7-4a-6c", num: "Kapitel 7 (4a-6c)", name: "Unterwegs & Carsharing", emoji: "🛴",
        items: [
            { de: "ewig", en: "forever", hint: "4a" },
            { de: "das Kinderabteil, -e", en: "children's compartment", hint: "4a" },
            { de: "nervig", en: "annoying", hint: "4a" },
            { de: "ungeduldig", en: "impatient", hint: "4a" },
            { de: "weiter|fahren", en: "to carry on / drive on", hint: "4a" },
            { de: "der Kinderwagen, -", en: "pram", hint: "5a" },
            { de: "der Bordcomputer, -", en: "on-board computer", hint: "6a" },
            { de: "der E-Scooter, -", en: "electric scooter", hint: "6a" },
            { de: "das Fahrzeug, -e", en: "vehicle", hint: "6a" },
            { de: "registrieren (sich)", en: "to register", hint: "6a" },
            { de: "der Tarif, -e", en: "rate", hint: "6a" },
            { de: "die Werbung, -en", en: "advertisement", hint: "6a" },
            { de: "ab|stellen", en: "to park", hint: "6c" },
            { de: "erreichen", en: "to reach", hint: "6c" },
            { de: "die Fahrt, -en", en: "journey", hint: "6c" },
            { de: "die Kaution, -en", en: "deposit", hint: "6c" },
            { de: "der Kundenservice, -s", en: "customer service", hint: "6c" },
            { de: "nötig", en: "necessary", hint: "6c" },
            { de: "versichert", en: "insured", hint: "6c" }
        ]
    },
    {
        id: "a2-kapitel-7-8a-10c", num: "Kapitel 7 (8a-10c)", name: "Wegbeschreibung & Umwelt", emoji: "🚲",
        items: [
            { de: "die Kreuzung, -en", en: "crossroads", hint: "8c" },
            { de: "vorbei|gehen", en: "to walk past", hint: "8c" },
            { de: "die Beschreibung, -en", en: "description", hint: "8f" },
            { de: "die Platzreservierung, -en", en: "seat reservation", hint: "9a" },
            { de: "die Stadtbesichtigung, -en", en: "sightseeing tour", hint: "9a" },
            { de: "das E-Bike, -s", en: "electronic bike", hint: "10a" },
            { de: "elektrisch", en: "electric", hint: "10a" },
            { de: "der Experte, -n", en: "expert (m)", hint: "10a" },
            { de: "die Expertin, -nen", en: "expert (f)", hint: "10a" },
            { de: "die Großstadt, \"-e", en: "large city", hint: "10a" },
            { de: "die Innenstadt, \"-e", en: "city centre", hint: "10a" },
            { de: "die Konsequenz, -en", en: "consequence", hint: "10a" },
            { de: "lösen", en: "to solve", hint: "10a" },
            { de: "der Lösungsvorschlag, \"-e", en: "proposed solution", hint: "10a" },
            { de: "der Radfahrer, -", en: "cyclist (m)", hint: "10a" },
            { de: "die Radfahrerin, -nen", en: "cyclist (f)", hint: "10a" },
            { de: "der Radweg, -e", en: "cycle path", hint: "10a" },
            { de: "reduzieren", en: "to reduce", hint: "10a" },
            { de: "die Seilbahn, -en", en: "cable car", hint: "10a" },
            { de: "umweltfreundlich", en: "environmentally friendly", hint: "10a" },
            { de: "das Verkehrsproblem, -e", en: "traffic problem", hint: "10a" },
            { de: "sinnvoll", en: "sensible", hint: "10c" },
            { de: "unpraktisch", en: "impractical", hint: "10c" }
        ]
    },
    {
        id: "a2-kapitel-7-11a-11c", num: "Kapitel 7 (11a-11c)", name: "Pendeln & Wetterfaktoren", emoji: "🌦️",
        items: [
            { de: "brauchen", en: "to need", hint: "11a" },
            { de: "das Gewitter, -", en: "thunderstorm", hint: "11a" },
            { de: "das Glatteis (Sg.)", en: "black ice", hint: "11a" },
            { de: "pendeln", en: "to commute", hint: "11a" },
            { de: "die Richtung, -en", en: "direction", hint: "11a" },
            { de: "sogar", en: "even", hint: "11a" },
            { de: "die Zugfahrt, -en", en: "train ride", hint: "11a" },
            { de: "hinten", en: "behind", hint: "11c" },
            { de: "die Schlange, -n", en: "queue", hint: "11c" },
            { de: "vorne", en: "at the front", hint: "11c" },
            { de: "klatschen", en: "to clap", hint: "13c" },
            { de: "überlegen (sich)", en: "to invent / consider", hint: "13d" }
        ]
    },

    // ==========================================
    // KAPITEL 8: GELERNT IST GELERNT!
    // ==========================================
    {
        id: "a2-kapitel-8-1a-1b", num: "Kapitel 8 (1a-1b)", name: "Lernen & Hobbys", emoji: "🎸",
        items: [
            { de: "chinesisch", en: "Chinese", hint: "1a" },
            { de: "die Schrift, -en", en: "script", hint: "1a" },
            { de: "abonnieren", en: "to subscribe to sth", hint: "1b" },
            { de: "bearbeiten", en: "to edit", hint: "1b" },
            { de: "beschweren (sich)", en: "to complain about", hint: "1b" },
            { de: "die Disziplin (Sg.)", en: "discipline", hint: "1b" },
            { de: "die Einführung, -en", en: "introduction", hint: "1b" },
            { de: "gebraucht", en: "used", hint: "1b" },
            { de: "die Gitarre, -n", en: "guitar", hint: "1b" },
            { de: "das Instrument, -e", en: "instrument", hint: "1b" },
            { de: "der Kanal, \"-e", en: "channel", hint: "1b" },
            { de: "das Klavier, -e", en: "piano", hint: "1b" },
            { de: "kompliziert", en: "complicated", hint: "1b" },
            { de: "der Kursleiter, -", en: "course director (m)", hint: "1b" },
            { de: "die Kursleiterin, -nen", en: "course director (f)", hint: "1b" },
            { de: "notwendig", en: "necessary", hint: "1b" },
            { de: "pensioniert", en: "retired", hint: "1b" },
            { de: "prima", en: "great", hint: "1b" },
            { de: "die Qualität, -en", en: "quality", hint: "1b" },
            { de: "die Rente, -n", en: "retirement", hint: "1b" }
        ]
    },
    {
        id: "a2-kapitel-8-3a-4a", num: "Kapitel 8 (3a-4a)", name: "Prüfungssorgen & Lerntipps", emoji: "🧠",
        items: [
            { de: "die Abschlussprüfung, -en", en: "final exam", hint: "3a" },
            { de: "die Fahrstunde, -n", en: "driving lesson", hint: "3a" },
            { de: "das Forum, Foren", en: "panel / forum", hint: "3a" },
            { de: "hart", en: "difficult", hint: "3a" },
            { de: "intelligent", en: "intelligent", hint: "3a" },
            { de: "kapieren", en: "to understand", hint: "3a" },
            { de: "klug", en: "clever", hint: "3a" },
            { de: "die Magenschmerzen (Pl.)", en: "stomach ache", hint: "3a" },
            { de: "rasen", en: "to race", hint: "3a" },
            { de: "realistisch", en: "realistic", hint: "3a" },
            { de: "das Stipendium, Stipendien", en: "scholarship", hint: "3a" },
            { de: "der Stoff, -e", en: "material", hint: "3a" },
            { de: "der Zeitplan, \"-e", en: "schedule", hint: "3a" },
            { de: "verschieben", en: "to postpone", hint: "3c" },
            { de: "durch|atmen", en: "to breathe deeply", hint: "4a" },
            { de: "die Energie, -n", en: "energy", hint: "4a" },
            { de: "die Nervosität (Sg.)", en: "nervousness", hint: "4a" },
            { de: "der Prüfer, -", en: "examiner (m)", hint: "4a" },
            { de: "die Prüferin, -nen", en: "examiner (f)", hint: "4a" },
            { de: "der Trick, -s", en: "trick", hint: "4a" }
        ]
    },
    {
        id: "a2-kapitel-8-4bub-6b", num: "Kapitel 8 (4bÜB-6b)", name: "Beratung & Berufe mit Sprache", emoji: "🗣️",
        items: [
            { de: "die Beratung, -en", en: "consultation", hint: "4b ÜB" },
            { de: "erfahren", en: "experienced", hint: "4b ÜB" },
            { de: "erforderlich", en: "required", hint: "4b ÜB" },
            { de: "die Förderung, -en", en: "funding", hint: "4b ÜB" },
            { de: "mündlich", en: "oral", hint: "4b ÜB" },
            { de: "schriftlich", en: "written", hint: "4b ÜB" },
            { de: "der Workshop, -s", en: "workshop", hint: "4b ÜB" },
            { de: "der Ratschlag, \"-e", en: "advice", hint: "4d" },
            { de: "an|stellen", en: "to hire", hint: "6b" },
            { de: "der Arbeitgeber, -", en: "employer", hint: "6b" },
            { de: "der Auftrag, \"-e", en: "contract / order", hint: "6b" },
            { de: "ausländisch", en: "foreign", hint: "6b" },
            { de: "der Autor, -en", en: "author (m)", hint: "6b" },
            { de: "die Autorin, -nen", en: "author (f)", hint: "6b" },
            { de: "begleiten", en: "to accompany", hint: "6b" },
            { de: "dolmetschen", en: "to translate (orally)", hint: "6b" },
            { de: "faszinieren", en: "to fascinate", hint: "6b" },
            { de: "freiberuflich", en: "freelance", hint: "6b" },
            { de: "der Gebärdendolmetscher, -", en: "sign language interpreter (m)", hint: "6b" },
            { de: "die Gebärdendolmetscherin, -nen", en: "sign language interpreter (f)", hint: "6b" },
            { de: "gehörlos", en: "deaf", hint: "6b" },
            { de: "die Kommunikation (Sg.)", en: "communication", hint: "6b" },
            { de: "kommunizieren", en: "to communicate", hint: "6b" },
            { de: "die Konferenz, -en", en: "conference", hint: "6b" },
            { de: "die Sprachwissenschaft, -en", en: "linguistic science", hint: "6b" }
        ]
    },
    {
        id: "a2-kapitel-8-9a-11b", num: "Kapitel 8 (9a-11b)", name: "Ehrenamt & Präsentationen", emoji: "🎤",
        items: [
            { de: "die Bücherei, -en", en: "library", hint: "9a" },
            { de: "existieren", en: "to exist", hint: "9a" },
            { de: "der/die Freiwillige, -n", en: "volunteer", hint: "9a" },
            { de: "putzen", en: "to clean", hint: "9a" },
            { de: "die Reparatur, -en", en: "repair", hint: "9a" },
            { de: "reparieren", en: "to repair", hint: "9a" },
            { de: "der Senior, -en", en: "senior (m)", hint: "9a" },
            { de: "die Seniorin, -nen", en: "senior (f)", hint: "9a" },
            { de: "spülen", en: "to rinse", hint: "9a" },
            { de: "voneinander", en: "from each other", hint: "9a" },
            { de: "weg|werfen", en: "to throw away", hint: "9a" },
            { de: "das Werkzeug, -e", en: "tool", hint: "9a" },
            { de: "die Einleitung, -en", en: "introduction", hint: "10b" },
            { de: "die Gliederung, -en", en: "outline", hint: "10b" },
            { de: "der Hauptteil, -e", en: "main part", hint: "10b" },
            { de: "ab|lesen", en: "to read", hint: "11a" },
            { de: "beachten", en: "to consider", hint: "11b" },
            { de: "flüssig", en: "fluent", hint: "11b" },
            { de: "der Inhalt, -e", en: "content", hint: "11b" },
            { de: "vor|tragen", en: "to present", hint: "11b" },
            { de: "der Zuhörer, -", en: "member of audience (m)", hint: "11b" },
            { de: "die Zuhörerin, -nen", en: "member of audience (f)", hint: "11b" }
        ]
    },
    // ==========================================
    // KAPITEL 9: SPORTLICH, SPORTLICH
    // ==========================================
    {
        id: "a2-kapitel-9-1a-2b", num: "Kapitel 9 (1a-2b)", name: "Sportarten & Ausrüstung", emoji: "⚽",
        items: [
            { de: "der Fußballschuh, -e", en: "football boot", hint: "1a" },
            { de: "das Kajak, -s", en: "kayak", hint: "1a" },
            { de: "langlaufen", en: "to cross-country ski", hint: "1a" },
            { de: "die Matte, -n", en: "mat", hint: "1a" },
            { de: "das Mountainbike, -s", en: "mountain bike", hint: "1a" },
            { de: "das Paddel, -", en: "paddle", hint: "1a" },
            { de: "der Schläger, -", en: "bat / racket", hint: "1a" },
            { de: "der Skistock, \"-e", en: "ski pole", hint: "1a" },
            { de: "die Sportart, -en", en: "sport", hint: "1a" },
            { de: "das Surfbrett, -er", en: "surf board", hint: "1a" },
            { de: "surfen", en: "to surf", hint: "1a" },
            { de: "tauchen", en: "to dive", hint: "1a" },
            { de: "die Taucherbrille, -n", en: "diving mask", hint: "1a" },
            { de: "Volleyball (Sg.)", en: "volleyball", hint: "1a" },
            { de: "die Mannschaft, -en", en: "team", hint: "1b ÜB" },
            { de: "schießen", en: "to shoot", hint: "1b" },
            { de: "das Tor, -e", en: "goal", hint: "1b" },
            { de: "der Wettbewerb, -e", en: "competition", hint: "1b" },
            { de: "entspannen", en: "to relax", hint: "2b" },
            { de: "der Erfolg, -e", en: "success", hint: "2b" },
            { de: "die Gesundheit (Sg.)", en: "health", hint: "2b" },
            { de: "basteln", en: "to make sth / craft", hint: "2b" },
            { de: "die Kette, -n", en: "necklace", hint: "2b" }
        ]
    },
    {
        id: "a2-kapitel-9-3a-5c", num: "Kapitel 9 (3a-5c)", name: "Fan-Kultur & Emotionen", emoji: "🏆",
        items: [
            { de: "der Fanartikel, -", en: "team merchandise", hint: "3a" },
            { de: "der Sportverein, -e", en: "sports club", hint: "3b" },
            { de: "der Fußballfan, -s", en: "football fan", hint: "3c" },
            { de: "verstärken", en: "to reinforce", hint: "3c" },
            { de: "wahnsinnig", en: "crazy", hint: "3c" },
            { de: "die Enttäuschung, -en", en: "disappointment", hint: "3d" },
            { de: "genial", en: "impressive / brilliant", hint: "3d" },
            { de: "großartig", en: "terrific", hint: "3d" },
            { de: "die Hoffnung, -en", en: "hope", hint: "3d" },
            { de: "die Katastrophe, -n", en: "catastrophe", hint: "3d" },
            { de: "unglaublich", en: "unbelievable", hint: "3d" },
            { de: "aus|fallen", en: "to be cancelled", hint: "4" },
            { de: "die Radtour, -en", en: "bike ride", hint: "4" },
            { de: "benehmen (sich)", en: "to behave", hint: "5a" },
            { de: "deshalb", en: "therefore", hint: "5a" },
            { de: "die Fanseite, -n", en: "fan page", hint: "5a" },
            { de: "treu", en: "loyal", hint: "5a" },
            { de: "trotzdem", en: "still / nevertheless", hint: "5a" },
            { de: "das Vorbild, -er", en: "role model", hint: "5a" },
            { de: "die Folge, -n", en: "consequence", hint: "5b" },
            { de: "sympathisch", en: "likeable", hint: "5c" },
            { de: "der Widerspruch, \"-e", en: "contradiction", hint: "5c" }
        ]
    },
    {
        id: "a2-kapitel-9-8a-11b", num: "Kapitel 9 (8a-11b)", name: "Klettergarten & Verabredung", emoji: "🧗",
        items: [
            { de: "der Cousin, -s", en: "cousin (m)", hint: "8a" },
            { de: "die Cousine, -n", en: "cousin (f)", hint: "8a" },
            { de: "die Kondition (Sg.)", en: "stamina", hint: "8a" },
            { de: "einverstanden", en: "agreed", hint: "9a" },
            { de: "neulich", en: "recent", hint: "9b" },
            { de: "der Hochseilgarten, \"-", en: "high ropes course", hint: "10a" },
            { de: "der Kletterer, -", en: "climber (m)", hint: "10a" },
            { de: "der Klettergurt, -e", en: "harness", hint: "10a" },
            { de: "die Kletterin, -nen", en: "climber (f)", hint: "10a" },
            { de: "übermorgen", en: "day after tomorrow", hint: "10a" },
            { de: "zurück|geben", en: "to return", hint: "10a" },
            { de: "werfen", en: "to throw", hint: "11b" },
            { de: "bewachen", en: "to guard", hint: "12a" },
            { de: "eineinhalb", en: "one and a half", hint: "12a" },
            { de: "entfernt", en: "away", hint: "12a" },
            { de: "faszinierend", en: "fascinating", hint: "12a" },
            { de: "der Führer, -", en: "guide (m)", hint: "12a" },
            { de: "die Führerin, -nen", en: "guide (f)", hint: "12a" },
            { de: "das Gasthaus, \"-er", en: "inn", hint: "12a" },
            { de: "das Gebiet, -e", en: "area", hint: "12a" }
        ]
    },
    {
        id: "a2-kapitel-9-12a-13a", num: "Kapitel 9 (12a-13a)", name: "Natur, Wandern & Kitesurfen", emoji: "🏞️",
        items: [
            { de: "das Grenzgebiet, -e", en: "frontier / border area", hint: "12a" },
            { de: "hinunter", en: "down", hint: "12a" },
            { de: "der Hinweis, -e", en: "evidence / hint", hint: "12a" },
            { de: "die Höhle, -n", en: "cave", hint: "12a" },
            { de: "kulturell", en: "cultural", hint: "12a" },
            { de: "der Nationalpark, -s", en: "national park", hint: "12a" },
            { de: "der Nebel, -", en: "fog", hint: "12a" },
            { de: "quer", en: "across", hint: "12a" },
            { de: "der Staat, -en", en: "state", hint: "12a" },
            { de: "die Strecke, -n", en: "route", hint: "12a" },
            { de: "der Streifen, -", en: "strip", hint: "12a" },
            { de: "das Tal, \"-er", en: "valley", hint: "12a" },
            { de: "die Temperatur, -en", en: "temperature", hint: "12a" },
            { de: "trocken", en: "dry", hint: "12a" },
            { de: "die Umgebung, -en", en: "vicinity / surroundings", hint: "12a" },
            { de: "die Wanderung, -en", en: "hike", hint: "12a" },
            { de: "der Wanderweg, -e", en: "hiking trail", hint: "12a" },
            { de: "der Einwohner, -", en: "inhabitant (m)", hint: "13a" },
            { de: "die Einwohnerin, -nen", en: "inhabitant (f)", hint: "13a" },
            { de: "das Kitesurfen (Sg.)", en: "kitesurfing", hint: "13a" },
            { de: "die Surfschule, -n", en: "surf school", hint: "13a" }
        ]
    },

    // ==========================================
    // KAPITEL 10: ZUSAMMEN LEBEN
    // ==========================================
    {
        id: "a2-kapitel-10-1a-2a", num: "Kapitel 10 (1a-2a)", name: "Wohnformen & Hausbereiche", emoji: "🏡",
        items: [
            { de: "der Bauernhof, \"-e", en: "farm", hint: "1a" },
            { de: "die Breite, -n", en: "width", hint: "1b" },
            { de: "die Ferienwohnung, -en", en: "holiday home", hint: "1b" },
            { de: "die Fläche, -n", en: "area", hint: "1b" },
            { de: "das Hausboot, -e", en: "houseboat", hint: "1b" },
            { de: "die Höhe, -n", en: "altitude / height", hint: "1b" },
            { de: "intensiv", en: "intense", hint: "1b" },
            { de: "die Kuh, \"-e", en: "cow", hint: "1b" },
            { de: "die Länge, -n", en: "length", hint: "1b" },
            { de: "der Luxus (Sg.)", en: "luxury", hint: "1b" },
            { de: "nass", en: "wet", hint: "1b" },
            { de: "der Quadratmeter, -", en: "square meter", hint: "1b" },
            { de: "schaukeln", en: "to rock", hint: "1b" },
            { de: "spiegeln (sich)", en: "to reflect", hint: "1b" },
            { de: "der Stadtrand, \"-er", en: "city limit", hint: "1b" },
            { de: "das Ufer, -", en: "shore", hint: "1b" },
            { de: "die Wagenburg, -en", en: "wagon fort", hint: "1b" },
            { de: "das Dach, \"-er", en: "roof", hint: "1a ÜB" },
            { de: "der Keller, -", en: "basement", hint: "1a ÜB" },
            { de: "einsam", en: "lonely", hint: "2a" }
        ]
    },
    {
        id: "a2-kapitel-10-3c-5e", num: "Kapitel 10 (3c-5e)", name: "Nachbarn & Sommerfest", emoji: "🎈",
        items: [
            { de: "gießen", en: "to water", hint: "3c" },
            { de: "der Lärm (Sg.)", en: "noise", hint: "3c" },
            { de: "bellen", en: "to bark", hint: "4b" },
            { de: "das Päckchen, -", en: "package", hint: "4b" },
            { de: "stinken", en: "to stink", hint: "4b" },
            { de: "der Aushang, \"-e", en: "announcement", hint: "5a" },
            { de: "schmutzig", en: "dirty", hint: "5a" },
            { de: "die Torte, -n", en: "gateau / cake", hint: "5a" },
            { de: "der Blumentopf, \"-e", en: "flower pot", hint: "5b" },
            { de: "der Boden, \"-", en: "floor / ground", hint: "5b" },
            { de: "das Gartenhaus, \"-er", en: "summer house", hint: "5b" },
            { de: "hängen", en: "to hang / be attached", hint: "5b" },
            { de: "die Kerze, -n", en: "candle", hint: "5b" },
            { de: "das Kissen, -", en: "pillow", hint: "5b" },
            { de: "der Lampion, -s", en: "paper lantern", hint: "5b" },
            { de: "das Poster, -", en: "poster", hint: "5b" },
            { de: "der Roller, -", en: "scooter", hint: "5b" },
            { de: "das Spielzeug, -e", en: "toy", hint: "5b" },
            { de: "legen", en: "to lie / put horizontally", hint: "5c" },
            { de: "die Dekoration, -en", en: "decoration", hint: "5e" }
        ]
    },
    {
        id: "a2-kapitel-10-6b-7c", num: "Kapitel 10 (6b-7c)", name: "WG, Mieter & Auszug", emoji: "🔑",
        items: [
            { de: "ein|ziehen", en: "to move in", hint: "6b" },
            { de: "der Mieter, -", en: "tenant (m)", hint: "6b" },
            { de: "die Mieterin, -nen", en: "tenant (f)", hint: "6b" },
            { de: "möbliert", en: "furnished", hint: "6b" },
            { de: "die Nebenkosten (Pl.)", en: "utilities", hint: "6b" },
            { de: "aus|kennen (sich)", en: "to know one's way around", hint: "6c" },
            { de: "aus|packen", en: "to unpack", hint: "6c" },
            { de: "der Briefkasten, \"-", en: "mailbox", hint: "6c" },
            { de: "gespannt", en: "curious", hint: "6c" },
            { de: "kündigen", en: "to resign / terminate lease", hint: "6c" },
            { de: "der Mitbewohner, -", en: "flatmate (m)", hint: "6d" },
            { de: "die Mitbewohnerin, -nen", en: "flatmate (f)", hint: "6d" },
            { de: "verirren (sich)", en: "to get lost", hint: "6d" },
            { de: "die Zulassung, -en", en: "admission", hint: "6d" },
            { de: "einmalig", en: "unique", hint: "7c" },
            { de: "gelten", en: "to apply / be valid", hint: "7c" },
            { de: "der Zeitraum, \"-e", en: "period", hint: "7c" }
        ]
    },
    {
        id: "a2-kapitel-10-10c-12e", num: "Kapitel 10 (10c-12e)", name: "Haustiere & Tiergeschichten", emoji: "🐶",
        items: [
            { de: "der Bär, -en", en: "bear", hint: "10c" },
            { de: "der Hase, -n", en: "rabbit", hint: "10c" },
            { de: "die Katze, -n", en: "cat", hint: "10c" },
            { de: "der Kosename, -n", en: "pet name", hint: "10c" },
            { de: "das Haustier, -e", en: "pet", hint: "10d" },
            { de: "die Ratte, -n", en: "rat", hint: "11a" },
            { de: "das Futter (Sg.)", en: "feed", hint: "11b" },
            { de: "modisch", en: "fashionable", hint: "11b" },
            { de: "das Schwein, -e", en: "pig", hint: "11b" },
            { de: "der Tierarzt, \"-e", en: "vet (m)", hint: "11b" },
            { de: "die Tierärztin, -nen", en: "vet (f)", hint: "11b" },
            { de: "die Vermutung, -en", en: "assumption", hint: "11b" },
            { de: "der Vogel, \"-", en: "bird", hint: "11b" },
            { de: "der Bauer, -n", en: "farmer (m)", hint: "12a" },
            { de: "die Bäuerin, -nen", en: "farmer (f)", hint: "12a" },
            { de: "der Besitzer, -", en: "owner (m)", hint: "12a" },
            { de: "die Besitzerin, -nen", en: "owner (f)", hint: "12a" },
            { de: "besorgt", en: "worried", hint: "12a" },
            { de: "dünn", en: "thin", hint: "12a" },
            { de: "das Schaf, -e", en: "sheep", hint: "12a" },
            { de: "das Zuhause, -", en: "home", hint: "12a" },
            { de: "füttern", en: "to feed", hint: "12c" },
            { de: "nebenan", en: "next door", hint: "12c" },
            { de: "das Stockwerk, -e", en: "floor", hint: "12c" },
            { de: "weg|laufen", en: "to run away", hint: "12c" }
        ]
    },
    // ==========================================
    // KAPITEL 11: WIE DIE ZEIT VERGEHT!
    // ==========================================
    {
        id: "a2-kapitel-11-1a-2c", num: "Kapitel 11 (1a-2c)", name: "Zeit, Alltag & Unfälle", emoji: "⏳",
        items: [
            { de: "verbringen", en: "to spend (time)", hint: "1a" },
            { de: "vergehen", en: "to pass by", hint: "1a" },
            { de: "verreisen", en: "to go away (on a journey)", hint: "1a" },
            { de: "Acht geben", en: "to take care", hint: "1b ÜB" },
            { de: "der Alkohol (Sg.)", en: "alcohol", hint: "1b ÜB" },
            { de: "backen", en: "to bake", hint: "1b ÜB" },
            { de: "bauen", en: "to build", hint: "1b ÜB" },
            { de: "betrunken", en: "drunk", hint: "1b ÜB" },
            { de: "bluten", en: "to bleed", hint: "1b ÜB" },
            { de: "brechen", en: "to break", hint: "1b ÜB" },
            { de: "ein|richten", en: "to furnish", hint: "1b ÜB" },
            { de: "die Hausfrau, -en", en: "homemaker (f)", hint: "1b ÜB" },
            { de: "der Hausmann, \"-er", en: "homemaker (m)", hint: "1b ÜB" },
            { de: "sparen", en: "to save", hint: "1b ÜB" },
            { de: "verletzen", en: "to hurt / injure", hint: "1b ÜB" },
            { de: "vor allem", en: "especially", hint: "2a" },
            { de: "der Werktag, -e", en: "working day", hint: "2c" }
        ]
    },
    {
        id: "a2-kapitel-11-5a-9d", num: "Kapitel 11 (5a-9d)", name: "Stress, Arbeit & Ausflug", emoji: "💼",
        items: [
            { de: "behalten", en: "to keep", hint: "5a" },
            { de: "die Ehe, -n", en: "marriage", hint: "5a" },
            { de: "entlassen", en: "to fire / dismiss", hint: "5a" },
            { de: "der Export, -e", en: "export", hint: "5a" },
            { de: "die Frist, -en", en: "deadline", hint: "5a" },
            { de: "der Import, -e", en: "import", hint: "5a" },
            { de: "klingeln", en: "to ring", hint: "5a" },
            { de: "schimpfen", en: "to scold", hint: "5a" },
            { de: "ständig", en: "constant", hint: "5a" },
            { de: "aus|schalten", en: "to switch off", hint: "5b" },
            { de: "die Kategorie, -n", en: "category", hint: "8a" },
            { de: "die Kajaktour, -en", en: "kayak tour", hint: "9a" },
            { de: "das Mitleid (Sg.)", en: "pity / compassion", hint: "9a" },
            { de: "interessieren (sich)", en: "to be interested in", hint: "9d" }
        ]
    },
    {
        id: "a2-kapitel-11-11a-12b", num: "Kapitel 11 (11a-12b)", name: "Früher & Sprichwörter", emoji: "📜",
        items: [
            { de: "altmodisch", en: "old-fashioned", hint: "11a" },
            { de: "besitzen", en: "to own", hint: "11a" },
            { de: "damals", en: "back then", hint: "11a" },
            { de: "das Einkaufszentrum, -zentren", en: "shopping centre", hint: "11a" },
            { de: "das Feuer, -", en: "fire", hint: "11a" },
            { de: "heizen", en: "to heat", hint: "11a" },
            { de: "die Heizung, -en", en: "heating", hint: "11a" },
            { de: "die Hektik (Sg.)", en: "rush / haste", hint: "11a" },
            { de: "kühl", en: "cool", hint: "11a" },
            { de: "die Kutsche, -n", en: "carriage", hint: "11a" },
            { de: "der Notfall, \"-e", en: "emergency", hint: "11b" },
            { de: "produzieren", en: "to produce", hint: "11b" },
            { de: "reich", en: "rich", hint: "11b" },
            { de: "der Strom (Sg.)", en: "electricity", hint: "11b" },
            { de: "träumen", en: "to dream", hint: "11b" },
            { de: "die Unterkunft, \"-e", en: "accommodation", hint: "11b" },
            { de: "verzichten", en: "to give up sth", hint: "11d" },
            { de: "besorgen", en: "to get / obtain", hint: "12a" },
            { de: "das Gold (Sg.)", en: "gold", hint: "12a" },
            { de: "heilen", en: "to heal", hint: "12a" },
            { de: "der Rat (Sg.)", en: "advice", hint: "12a" },
            { de: "das Sprichwort, \"-er", en: "proverb", hint: "12a" },
            { de: "effektiv", en: "effective", hint: "12b" }
        ]
    },

    // ==========================================
    // KAPITEL 12: GUTE UNTERHALTUNG!
    // ==========================================
    {
        id: "a2-kapitel-12-1a-1d", num: "Kapitel 12 (1a-1d)", name: "Literatur & Medienwelt", emoji: "👑",
        items: [
            { de: "der König, -e", en: "king", hint: "1a" },
            { de: "die Königin, -nen", en: "queen", hint: "1a" },
            { de: "die Unterhaltung, -en", en: "entertainment", hint: "1a" },
            { de: "die Gesellschaft, -en", en: "society", hint: "1b" },
            { de: "die Gewalt (Sg.)", en: "violence", hint: "1b" },
            { de: "insbesondere", en: "especially", hint: "1b" },
            { de: "jährlich", en: "yearly", hint: "1b" },
            { de: "das Kinderbuch, \"-er", en: "children's book", hint: "1b" },
            { de: "die Kriminalität (Sg.)", en: "criminality", hint: "1b" },
            { de: "die Kulisse, -n", en: "scenery / backdrop", hint: "1b" },
            { de: "das Märchenschloss, \"-er", en: "fairytale castle", hint: "1b" },
            { de: "die Realität, -en", en: "reality", hint: "1b" },
            { de: "der Roman, -e", en: "novel", hint: "1b" },
            { de: "das Schloss, \"-er", en: "castle", hint: "1b" },
            { de: "der Synchronsprecher, -", en: "voice actor (m)", hint: "1b" },
            { de: "die Synchronsprecherin, -nen", en: "voice actress (f)", hint: "1b" },
            { de: "die Verfilmung, -en", en: "film adaptation", hint: "1d" },
            { de: "das Werk, -e", en: "piece / work of art", hint: "1d" },
            { de: "wild", en: "wild", hint: "1d" },
            { de: "die Führung, -en", en: "guided tour", hint: "1d" }
        ]
    },
    {
        id: "a2-kapitel-12-3a-4c", num: "Kapitel 12 (3a-4c)", name: "Festival, Ticket & Booking", emoji: "🎟️",
        items: [
            { de: "das Musikfestival, -s", en: "music festival", hint: "3a" },
            { de: "die AGB, -s", en: "terms and conditions", hint: "3a ÜB" },
            { de: "erhalten", en: "to receive", hint: "3a ÜB" },
            { de: "die Gebühr, -en", en: "fee", hint: "3a ÜB" },
            { de: "der Kauf, \"-e", en: "purchase", hint: "3a ÜB" },
            { de: "die Mehrwertsteuer (Mwst.)", en: "value-added tax (VAT)", hint: "3a ÜB" },
            { de: "der Sitzplatz, \"-e", en: "seat", hint: "3a ÜB" },
            { de: "der Stehplatz, \"-e", en: "standing room", hint: "3a ÜB" },
            { de: "die Überweisung, -en", en: "bank transfer", hint: "3a ÜB" },
            { de: "der Versand (Sg.)", en: "shipping", hint: "3a ÜB" },
            { de: "der Warenkorb, \"-e", en: "shopping cart", hint: "3a ÜB" },
            { de: "die Zahlungsart, -en", en: "payment method", hint: "3a ÜB" },
            { de: "der Campingplatz, \"-e", en: "campsite", hint: "4a" },
            { de: "die Verpflegung, -en", en: "provisions / catering", hint: "4a" },
            { de: "der Rucksack, \"-e", en: "backpack", hint: "4b" },
            { de: "die Übernachtung, -en", en: "overnight stay", hint: "4b" }
        ]
    },
    {
        id: "a2-kapitel-12-6b-8a", num: "Kapitel 12 (6b-8a)", name: "Musikstile & Radio-Meldungen", emoji: "📻",
        items: [
            { de: "der Hardrock (Sg.)", en: "hard rock", hint: "6b" },
            { de: "der Hit, -s", en: "hit", hint: "6b" },
            { de: "melodisch", en: "melodious", hint: "6b" },
            { de: "der Musikstil, -e", en: "music genre", hint: "6b" },
            { de: "befreundet", en: "friendly", hint: "7a" },
            { de: "bestätigen", en: "to confirm", hint: "7a" },
            { de: "der Einsatz, \"-e", en: "assignment", hint: "7a" },
            { de: "der Hörer, -", en: "listener (m)", hint: "7a" },
            { de: "die Hörerin, -nen", en: "listener (f)", hint: "7a" },
            { de: "der Nachrichtensprecher, -", en: "newsreader (m)", hint: "7a" },
            { de: "die Nachrichtensprecherin, -nen", en: "newsreader (f)", hint: "7a" },
            { de: "der Sammler, -", en: "collector (m)", hint: "7a" },
            { de: "die Sammlerin, -nen", en: "collector (f)", hint: "7a" },
            { de: "das Schnäppchen, -", en: "bargain", hint: "7a" },
            { de: "die Stille (Sg.)", en: "silence", hint: "7a" },
            { de: "die Stimme, -n", en: "voice", hint: "7a" },
            { de: "die Stimmung, -en", en: "mood", hint: "7a" },
            { de: "verschlafen", en: "to oversleep", hint: "7a" },
            { de: "der Wert, -e", en: "value", hint: "7a" },
            { de: "wertvoll", en: "valuable", hint: "7a" },
            { de: "die Meldung, -en", en: "announcement / report", hint: "8a" }
        ]
    },
    {
        id: "a2-kapitel-12-9a-11b", num: "Kapitel 12 (9a-11b)", name: "Kunst, Malerei & Bilder", emoji: "🎨",
        items: [
            { de: "die Hauptrolle, -n", en: "lead / main role", hint: "9a" },
            { de: "der/die Prominente, -n", en: "celebrity", hint: "9a" },
            { de: "die Malerei, -en", en: "painting", hint: "10a" },
            { de: "der Audioguide, -s", en: "audio guide", hint: "10b" },
            { de: "die Bedeutung, -en", en: "meaning", hint: "10c" },
            { de: "die Kunstgeschichte (Sg.)", en: "art history", hint: "10c" },
            { de: "ab|malen", en: "to depict / paint", hint: "10d" },
            { de: "das Wildschwein, -e", en: "wild boar", hint: "10d" },
            { de: "abstrakt", en: "abstract", hint: "11a" },
            { de: "hübsch", en: "pretty", hint: "11a" },
            { de: "uninteressant", en: "uninteresting", hint: "11a" },
            { de: "verrückt", en: "crazy", hint: "11a" },
            { de: "die Bildbeschreibung, -en", en: "description of a picture", hint: "11b" },
            { de: "dahinter", en: "behind it", hint: "11b" },
            { de: "deuten", en: "to indicate", hint: "11b" },
            { de: "der Titel, -", en: "title", hint: "11b" },
            { de: "der Vordergrund, \"-e", en: "foreground", hint: "11b" },
            { de: "auf|fallen", en: "to stand out / notice", hint: "12c" },
            { de: "der Ausblick, -e", en: "view", hint: "12c" },
            { de: "der Hintergrund, \"-e", en: "background", hint: "12c" }
        ]
    }
];
