
export const NETZWERK_DATA_MAPPING = [
    // ==========================================
    // KAPITEL 1: GUTE REISE!
    // ==========================================
    {
        id: "b1-kapitel-1-1a-3b", num: "Kapitel 1 (1a-3b)", name: "Natur, Urlaub & Genuss", emoji: "🏕️",
        items: [
            { de: "faulenzen", en: "to lounge around", hint: "1a ÜB" },
            { de: "giftig", en: "poisonous", hint: "1a ÜB" },
            { de: "der Himmel, -", en: "sky", hint: "1a ÜB" },
            { de: "im Freien", en: "outdoors", hint: "1a ÜB" },
            { de: "das Insekt, -en", en: "insect", hint: "1a ÜB" },
            { de: "das Netz, -e", en: "net", hint: "1a ÜB" },
            { de: "der Pilz, -e", en: "mushroom", hint: "1a ÜB" },
            { de: "der Schutz (Sg.)", en: "protection", hint: "1a ÜB" },
            { de: "zelten", en: "to camp", hint: "1a ÜB" },
            { de: "angenehm", en: "pleasant", hint: "2" },
            { de: "die Aussicht, -en", en: "view", hint: "2" },
            { de: "drüben", en: "over there", hint: "2" },
            { de: "das Erlebnis, -se", en: "experience", hint: "2" },
            { de: "der Genuss (Sg.)", en: "treat / enjoyment", hint: "2" },
            { de: "herrlich", en: "glorious", hint: "2" },
            { de: "die Küste, -n", en: "coast", hint: "2" },
            { de: "reif", en: "ripe", hint: "2" },
            { de: "der Sand (Sg.)", en: "sand", hint: "2" },
            { de: "die Traube, -n", en: "grape", hint: "2" },
            { de: "die Entfernung, -en", en: "distance", hint: "3b" },
            { de: "das Ferienhaus, \"-er", en: "holiday home", hint: "3b" },
            { de: "gründlich", en: "thorough", hint: "3b" },
            { de: "rechtzeitig", en: "on time", hint: "3b" },
            { de: "das Urlaubsziel, -e", en: "holiday destination", hint: "3b" }
        ]
    },
    {
        id: "b1-kapitel-1-4a-7", num: "Kapitel 1 (4a-7)", name: "Urlaubsplanung & Reisebüro", emoji: "🧳",
        items: [
            { de: "erholen (sich)", en: "to relax", hint: "4a" },
            { de: "der Kompromiss, -e", en: "compromise", hint: "4a" },
            { de: "meinetwegen", en: "fine with me", hint: "4a" },
            { de: "die Urlaubsplanung, -en", en: "holiday planning", hint: "4a" },
            { de: "entspannend", en: "relaxing", hint: "5a" },
            { de: "erfahren", en: "to learn / find out", hint: "5c" },
            { de: "die Schifffahrt, -en", en: "boat trip", hint: "6a" },
            { de: "das Wellnesshotel, -s", en: "spa hotel", hint: "6a" },
            { de: "enthalten sein", en: "to be included", hint: "7" },
            { de: "die Fahrtzeit, -en", en: "travel time", hint: "7" },
            { de: "das Gästehaus, \"-er", en: "guest house", hint: "7" },
            { de: "die Halbpension (Sg.)", en: "half board", hint: "7" },
            { de: "höchstens", en: "at the most", hint: "7" },
            { de: "der Reisebüro-Mitarbeiter, -", en: "travel agent (m)", hint: "7" },
            { de: "die Reisebüro-Mitarbeiterin, -nen", en: "travel agent (f)", hint: "7" },
            { de: "der Skibus, -se", en: "ski bus", hint: "7" },
            { de: "das Skigebiet, -e", en: "ski resort", hint: "7" },
            { de: "der Skilift, -e", en: "ski lift", hint: "7" },
            { de: "die Vollpension (Sg.)", en: "full board", hint: "7" },
            { de: "der Wellness-Bereich, -e", en: "spa area", hint: "7" },
            { de: "der Winterurlaub, -e", en: "winter holiday", hint: "7" }
        ]
    },
    {
        id: "b1-kapitel-1-8b-9c", num: "Kapitel 1 (8b-9c)", name: "Reiseziele & Missgeschicke", emoji: "🚗",
        items: [
            { de: "die Badewanne, -n", en: "bathtub", hint: "8b" },
            { de: "das Boot, -e", en: "boat", hint: "8b" },
            { de: "der Einfall, \"-e", en: "idea", hint: "8b" },
            { de: "enttäuscht", en: "disappointed", hint: "8b" },
            { de: "jedenfalls", en: "in any case", hint: "8c" },
            { de: "obwohl", en: "although / even though", hint: "8c" },
            { de: "offenbar", en: "obvious / apparently", hint: "8c" },
            { de: "spazieren", en: "to go for a walk", hint: "8c" },
            { de: "die Strandpromenade, -n", en: "beach promenade", hint: "8c" },
            { de: "das Abenteuer, -", en: "adventure", hint: "9a" },
            { de: "auf|bauen", en: "to build", hint: "9a" },
            { de: "brennen", en: "to burn", hint: "9a" },
            { de: "der Eimer, -", en: "bucket", hint: "9a" },
            { de: "der Kofferraum, \"-e", en: "car boot / trunk", hint: "9a" },
            { de: "schief|gehen", en: "to go wrong", hint: "9a" },
            { de: "tragen", en: "to carry", hint: "9a" },
            { de: "verzweifelt", en: "desperate", hint: "9a" },
            { de: "die Wiese, -n", en: "meadow", hint: "9a" },
            { de: "das Zeug (Sg.)", en: "stuff", hint: "9a" },
            { de: "fest|machen", en: "to fasten", hint: "9c" },
            { de: "die Perspektive, -n", en: "perspective", hint: "9c" }
        ]
    },
    {
        id: "b1-kapitel-1-11a-13c", num: "Kapitel 1 (11a-13c)", name: "Unterwegs & Almleben", emoji: "🏔️",
        items: [
            { de: "die Zugnummer, -n", en: "train number", hint: "11a" },
            { de: "die Bushaltestelle, -n", en: "bus stop", hint: "12b" },
            { de: "das Gepäckband, \"-er", en: "baggage conveyor belt", hint: "12b" },
            { de: "der Tiergarten, \"-", en: "zoo", hint: "12b" },
            { de: "der Hauptbahnhof, \"-e", en: "central station", hint: "12c" },
            { de: "die Alm, -en", en: "alpine pasture", hint: "13a" },
            { de: "begeistert", en: "enthusiastic", hint: "13a" },
            { de: "beinahe", en: "almost", hint: "13a" },
            { de: "die Einsamkeit (Sg.)", en: "solitude / loneliness", hint: "13a" },
            { de: "der Empfang (Sg.)", en: "reception / signal", hint: "13a" },
            { de: "entschließen (sich)", en: "to decide", hint: "13a" },
            { de: "erholt", en: "relaxed / recovered", hint: "13a" },
            { de: "erkälten (sich)", en: "to have a cold", hint: "13a" },
            { de: "das Gebirge, -", en: "mountains / mountain range", hint: "13a" },
            { de: "das Heimweh (Sg.)", en: "homesickness", hint: "13a" },
            { de: "die Hütte, -n", en: "hut / lodge", hint: "13a" },
            { de: "die Käserei, -en", en: "cheese factory", hint: "13a" },
            { de: "melken", en: "to milk", hint: "13a" },
            { de: "der Sonnenaufgang, \"-e", en: "sunrise", hint: "13a" },
            { de: "der Terminkalender, -", en: "diary / schedule", hint: "13a" },
            { de: "der Olivenbaum, \"-e", en: "olive tree", hint: "13b" },
            { de: "die Abneigung, -en", en: "dislike", hint: "13c" }
        ]
    },
    // ==========================================
    // KAPITEL 2: DAS IST JA PRAKTISCH!
    // ==========================================
    {
        id: "b1-kapitel-2-1a-3a", num: "Kapitel 2 (1a-3a)", name: "Technik, Bedienung & Reparatur", emoji: "🔌",
        items: [
            { de: "benötigen", en: "to need", hint: "1a" },
            { de: "der Fingerabdruck, \"-e", en: "fingerprint", hint: "1a" },
            { de: "der Funkkopfhörer, -", en: "wireless headphones", hint: "1a" },
            { de: "das Lastenfahrrad, \"-er", en: "freight bicycle", hint: "1a" },
            { de: "der Sprachassistent, -en", en: "language assistant", hint: "1a" },
            { de: "der Türöffner, -", en: "door opener", hint: "1a" },
            { de: "die Taste, -n", en: "key / button", hint: "1b" },
            { de: "der Transport, -e", en: "transport", hint: "1b" },
            { de: "an|schließen", en: "to connect / plug in", hint: "1b ÜB" },
            { de: "auf|laden", en: "to charge", hint: "1b ÜB" },
            { de: "bedienen", en: "to use / operate", hint: "1b ÜB" },
            { de: "ein|setzen", en: "to insert", hint: "1b ÜB" },
            { de: "ein|stecken", en: "to plug (in)", hint: "1b ÜB" },
            { de: "installieren", en: "to install", hint: "1b ÜB" },
            { de: "stumm", en: "mute / silent", hint: "1b ÜB" },
            { de: "die Anleitung, -en", en: "instruction", hint: "3a" },
            { de: "an|schaffen (sich)", en: "to get / obtain", hint: "3a" },
            { de: "herunter|fallen", en: "to fall down", hint: "3a" },
            { de: "kaputt|gehen", en: "to break", hint: "3a" },
            { de: "lohnen (sich)", en: "to be worth it", hint: "3a" },
            { de: "das Sonderangebot, -e", en: "special offer", hint: "3a" },
            { de: "der Staubsauger, -", en: "vacuum cleaner", hint: "3a" }
        ]
    },
    {
        id: "b1-kapitel-2-3e-5c", num: "Kapitel 2 (3e-5c)", name: "Einkauf, Garantie & Reklamation", emoji: "💳",
        items: [
            { de: "nähen", en: "to sew", hint: "3e" },
            { de: "reinigen", en: "to clean", hint: "3e" },
            { de: "streichen", en: "to paint", hint: "3e" },
            { de: "der Kopfhörer, -", en: "headphones", hint: "4a" },
            { de: "das Ladekabel, -", en: "charger cable", hint: "4a" },
            { de: "die Powerbank, -s", en: "powerbank", hint: "4a" },
            { de: "daher", en: "therefore", hint: "4b" },
            { de: "darum", en: "that's why", hint: "4b" },
            { de: "deswegen", en: "therefore", hint: "4b" },
            { de: "der Handyakku, -s", en: "mobile phone battery", hint: "4b" },
            { de: "sodass", en: "so that", hint: "4b" },
            { de: "die EC-Karte, -n", en: "debit card", hint: "5a ÜB" },
            { de: "die Gebrauchsanweisung, -en", en: "instructions", hint: "5a ÜB" },
            { de: "die Geheimzahl, -en", en: "PIN", hint: "5a ÜB" },
            { de: "der Geldautomat, -en", en: "ATM", hint: "5a ÜB" },
            { de: "das Girokonto, -konten", en: "checking account", hint: "5a ÜB" },
            { de: "gratis", en: "free", hint: "5a ÜB" },
            { de: "der Rabatt, -e", en: "discount", hint: "5a ÜB" },
            { de: "verraten", en: "to reveal", hint: "5a ÜB" },
            { de: "zurück|zahlen", en: "to pay back", hint: "5a ÜB" },
            { de: "die Garantie, -n", en: "warranty", hint: "5b" },
            { de: "die Quittung, -en", en: "receipt", hint: "5b" },
            { de: "reklamieren", en: "to complain / exchange", hint: "5b" }
        ]
    },
    {
        id: "b1-kapitel-2-6a-7d", num: "Kapitel 2 (6a-7d)", name: "Smart Home & Technologie", emoji: "🏠",
        items: [
            { de: "die Technologie, -n", en: "technology", hint: "6a" },
            { de: "die Vorstellungen (Pl.)", en: "ideas / suggestions", hint: "6a" },
            { de: "die Alarmanlage, -n", en: "alarm system", hint: "6b" },
            { de: "die Ausnahme, -n", en: "exception", hint: "6b" },
            { de: "bemerken", en: "to notice", hint: "6b" },
            { de: "bereits", en: "already", hint: "6b" },
            { de: "berühren", en: "to touch", hint: "6b" },
            { de: "der Einbruch, \"-e", en: "break-in", hint: "6b" },
            { de: "gleichzeitig", en: "simultaneous", hint: "6b" },
            { de: "die Jalousie, -n", en: "shutter / blind", hint: "6b" },
            { de: "steuern", en: "to control", hint: "6b" },
            { de: "der Tagesablauf, \"-e", en: "daily routine", hint: "6b" },
            { de: "die Wand, \"-e", en: "wall", hint: "6b" },
            { de: "an|passen", en: "to adjust", hint: "6d" },
            { de: "ein|schalten", en: "to switch on", hint: "6d" },
            { de: "geschehen", en: "to happen", hint: "7a" },
            { de: "leisten (sich)", en: "to afford", hint: "7a" },
            { de: "entsprechen", en: "to correspond", hint: "7b" },
            { de: "sparsam", en: "frugal / economical", hint: "7c" },
            { de: "die Gefahr, -en", en: "danger", hint: "7d" }
        ]
    },
    {
        id: "b1-kapitel-2-9b-11", num: "Kapitel 2 (9b-11)", name: "Werbung & Konsumverhalten", emoji: "📢",
        items: [
            { de: "die Werbeanzeige, -n", en: "advertisement", hint: "9b" },
            { de: "ansprechend", en: "appealing", hint: "9c" },
            { de: "unmodern", en: "unfashionable", hint: "9c" },
            { de: "unverständlich", en: "incomprehensible", hint: "9c" },
            { de: "ausgezeichnet", en: "excellent", hint: "9d" },
            { de: "frech", en: "cheeky", hint: "9d" },
            { de: "merkwürdig", en: "strange", hint: "9d" },
            { de: "seltsam", en: "odd", hint: "9d" },
            { de: "der Klebefilm, -e", en: "adhesive tape", hint: "10a" },
            { de: "der Markenname, -n", en: "brand name", hint: "10a" },
            { de: "die Schmerztablette, -n", en: "painkiller", hint: "10a" },
            { de: "das Taschentuch, \"-er", en: "handkerchief", hint: "10a" },
            { de: "aufmerksam", en: "attentive", hint: "10b" },
            { de: "beeinflussen", en: "to influence", hint: "10b" },
            { de: "genügen", en: "to suffice", hint: "10b" },
            { de: "das Kaufverhalten, -", en: "shopping behaviour", hint: "10b" },
            { de: "das Unternehmen, -", en: "company", hint: "10b" },
            { de: "das Verhalten, -", en: "behaviour", hint: "10b" },
            { de: "vertrauen", en: "to trust", hint: "10b" },
            { de: "der Werbetrick, -s", en: "advertising trick", hint: "10c" },
            { de: "das Wortspiel, -e", en: "pun / play on words", hint: "10c" },
            { de: "ungesund", en: "unhealthy", hint: "11" },
            { de: "verbieten", en: "to forbid", hint: "11" }
        ]
    },
    // ==========================================
    // KAPITEL 3: VERÄNDERUNGEN
    // ==========================================
    {
        id: "b1-kapitel-3-1a-2ub", num: "Kapitel 3 (1a-2ÜB)", name: "Arbeit, Gesundheit & Ernährung", emoji: "🥦",
        items: [
            { de: "der Arbeiter, -", en: "worker (m)", hint: "1a" },
            { de: "die Arbeiterin, -nen", en: "worker (f)", hint: "1a" },
            { de: "automatisiert", en: "automated", hint: "1a" },
            { de: "die Bedingung, -en", en: "condition", hint: "1a" },
            { de: "die Behandlung, -en", en: "treatment", hint: "1a" },
            { de: "die Diagnose, -n", en: "diagnosis", hint: "1a" },
            { de: "die Hygiene (Sg.)", en: "hygiene", hint: "1a" },
            { de: "die Konkurrenz (Sg.)", en: "competition", hint: "1a" },
            { de: "medizinisch", en: "medical", hint: "1a" },
            { de: "monoton", en: "monotonous", hint: "1a" },
            { de: "operieren", en: "to operate", hint: "1a" },
            { de: "die Pflegekraft, \"-e", en: "caregiver", hint: "1a" },
            { de: "die Schulbildung (Sg.)", en: "education", hint: "1a" },
            { de: "die Strafe, -n", en: "punishment / penalty", hint: "1a" },
            { de: "tolerant", en: "tolerant", hint: "1a" },
            { de: "ausschließlich", en: "exclusive", hint: "2 ÜB" },
            { de: "bewusst", en: "conscious", hint: "2 ÜB" },
            { de: "biologisch", en: "biological", hint: "2 ÜB" },
            { de: "die Diät, -en", en: "diet", hint: "2 ÜB" },
            { de: "ernähren (sich)", en: "to eat / nourish", hint: "2 ÜB" },
            { de: "die Ernährung (Sg.)", en: "nutrition", hint: "2 ÜB" },
            { de: "das Nahrungsmittel, -", en: "food", hint: "2 ÜB" },
            { de: "vegan", en: "vegan", hint: "2 ÜB" },
            { de: "vegetarisch", en: "vegetarian", hint: "2 ÜB" }
        ]
    },
    {
        id: "a1-kapitel-3-3a-3c", num: "Kapitel 3 (3a-3c)", name: "Lebenswege & Herausforderungen", emoji: "🌱",
        items: [
            { de: "erben", en: "to inherit", hint: "3a" },
            { de: "führen", en: "to lead (to)", hint: "3a" },
            { de: "gewohnt", en: "usual", hint: "3a" },
            { de: "die Krisensituation, -en", en: "crisis (situation)", hint: "3a" },
            { de: "die Lebensgeschichte, -n", en: "life story", hint: "3a" },
            { de: "der Lebensweg, -e", en: "path in life", hint: "3a" },
            { de: "der Prozess, -e", en: "process", hint: "3a" },
            { de: "der Todesfall, \"-e", en: "death", hint: "3a" },
            { de: "die Trennung, -en", en: "separation", hint: "3a" },
            { de: "der Wendepunkt, -e", en: "turning point", hint: "3a" },
            { de: "das Anliegen, -", en: "issue", hint: "3c" },
            { de: "der Buchautor, -en", en: "author (m)", hint: "3c" },
            { de: "die Buchautorin, -nen", en: "author (f)", hint: "3c" },
            { de: "ein|setzen (sich)", en: "to support", hint: "3c" },
            { de: "die Herausforderung, -en", en: "challenge", hint: "3c" },
            { de: "der Mut (Sg.)", en: "courage", hint: "3c" },
            { de: "die Rückkehr (Sg.)", en: "return", hint: "3c" },
            { de: "sammeln", en: "to gain / collect", hint: "3c" },
            { de: "das Schutzprojekt, -e", en: "protection project", hint: "3c" },
            { de: "die Sehnsucht, \"-e", en: "longing / desire", hint: "3c" },
            { de: "verursachen", en: "to cause", hint: "3c" },
            { de: "wesentlich", en: "considerable", hint: "3c" },
            { de: "das Wildtier, -e", en: "wild animal", hint: "3c" }
        ]
    },
    {
        id: "b1-kapitel-3-4b-6d", num: "Kapitel 3 (4b-6d)", name: "Erfolge, Liebe & Beziehungen", emoji: "❤️",
        items: [
            { de: "ehren", en: "to honour", hint: "4b" },
            { de: "gelähmt", en: "paralyzed", hint: "4b" },
            { de: "der Held, -en", en: "hero (m)", hint: "4b" },
            { de: "die Heldin, -nen", en: "hero (f)", hint: "4b" },
            { de: "der Höhepunkt, -e", en: "peak", hint: "4b" },
            { de: "kämpfen", en: "to fight", hint: "4b" },
            { de: "mittlerweile", en: "meanwhile", hint: "4b" },
            { de: "der Optimismus (Sg.)", en: "optimism", hint: "4b" },
            { de: "politisch", en: "political", hint: "4b" },
            { de: "das Privatleben (Sg.)", en: "private life", hint: "4b" },
            { de: "stürzen", en: "to fall", hint: "4b" },
            { de: "die Wirbelsäule, -n", en: "spine", hint: "4b" },
            { de: "begeistern", en: "to delight / inspire", hint: "4d" },
            { de: "historisch", en: "historical", hint: "4d" },
            { de: "auf|wachen", en: "to wake up", hint: "5b" },
            { de: "frisch", en: "newly / fresh", hint: "5b" },
            { de: "liebevoll", en: "loving", hint: "5b" },
            { de: "die Schwiegereltern (Pl.)", en: "parents-in-law", hint: "5b" },
            { de: "verlieben (sich)", en: "to fall in love", hint: "5b" },
            { de: "verschwinden", en: "to disappear", hint: "5b" },
            { de: "das Verhältnis, -se", en: "relationship", hint: "6b" },
            { de: "überqueren", en: "to cross", hint: "6c ÜB" },
            { de: "auf|geben", en: "to forsake / give up", hint: "6d" }
        ]
    },
    {
        id: "b1-kapitel-3-9a-10b", num: "Kapitel 3 (9a-10b)", name: "Etikette & Höflichkeit", emoji: "🤝",
        items: [
            { de: "veröffentlichen", en: "to release / publish", hint: "9a" },
            { de: "aus|suchen", en: "to choose", hint: "9c" },
            { de: "höflich", en: "polite", hint: "10a" },
            { de: "begrüßen", en: "to greet", hint: "10a" },
            { de: "das Benehmen (Sg.)", en: "behaviour", hint: "10a" },
            { de: "anwesend", en: "present", hint: "10b" },
            { de: "auf|halten", en: "to hold open", hint: "10b" },
            { de: "die Begrüßung, -en", en: "greeting", hint: "10b" },
            { de: "die Beziehung, -en", en: "relationship", hint: "10b" },
            { de: "duzen", en: "to use the informal greeting", hint: "10b" },
            { de: "der Gastgeber, -", en: "host (m)", hint: "10b" },
            { de: "die Gastgeberin, -nen", en: "host (f)", hint: "10b" },
            { de: "die Gewohnheit, -en", en: "habit", hint: "10b" },
            { de: "hierarchisch", en: "hierarchical", hint: "10b" },
            { de: "ignorieren", en: "to ignore", hint: "10b" },
            { de: "siezen", en: "to use the formal greeting", hint: "10b" },
            { de: "üblich", en: "usual", hint: "10b" },
            { de: "umarmen", en: "to hug", hint: "10b" },
            { de: "unsicher", en: "insecure", hint: "10b" },
            { de: "verhalten (sich)", en: "to behave", hint: "10b" },
            { de: "vertraut", en: "familiar", hint: "10b" },
            { de: "der/die Vorgesetzte, -n", en: "superior", hint: "10b" },
            { de: "die Wange, -n", en: "cheek", hint: "10b" }
        ]
    },
    // ==========================================
    // KAPITEL 4: ARBEITSWELT
    // ==========================================
    {
        id: "b1-kapitel-4-1b-1cub", num: "Kapitel 4 (1b-1cÜB)", name: "Berufe, Industrie & Recht", emoji: "⚖️",
        items: [
            { de: "die Analyse, -n", en: "analysis", hint: "1b" },
            { de: "aus|tragen", en: "to deliver", hint: "1b" },
            { de: "der Briefträger, -", en: "postal carrier (m)", hint: "1b" },
            { de: "die Briefträgerin, -nen", en: "postal carrier (f)", hint: "1b" },
            { de: "der Chemiker, -", en: "chemist (m)", hint: "1b" },
            { de: "die Chemikerin, -nen", en: "chemist (f)", hint: "1b" },
            { de: "die Elektronik (Sg.)", en: "electronics", hint: "1b" },
            { de: "exakt", en: "exact", hint: "1b" },
            { de: "der Mechatroniker, -", en: "mechatronics engineer (m)", hint: "1b" },
            { de: "die Mechatronikerin, -nen", en: "mechatronics engineer (f)", hint: "1b" },
            { de: "das Metall, -e", en: "metal", hint: "1b" },
            { de: "zu|stellen", en: "to deliver", hint: "1b" },
            { de: "die Akte, -n", en: "file / document", hint: "1a ÜB" },
            { de: "der/die Angeklagte, -n", en: "defendant", hint: "1a ÜB" },
            { de: "das Einkommen, -", en: "income", hint: "1a ÜB" },
            { de: "der Elektroingenieur, -e", en: "electrical engineer (m)", hint: "1a ÜB" },
            { de: "die Elektroingenieurin, -nen", en: "electrical engineer (f)", hint: "1a ÜB" },
            { de: "gerecht", en: "fair / just", hint: "1a ÜB" },
            { de: "das Gericht, -e", en: "court (of law)", hint: "1a ÜB" },
            { de: "die Gerichtsverhandlung, -en", en: "trial", hint: "1a ÜB" },
            { de: "her|stellen", en: "to produce / create", hint: "1a ÜB" },
            { de: "die Industrie, -n", en: "industry", hint: "1a ÜB" },
            { de: "die Landwirtschaft (Sg.)", en: "agriculture", hint: "1a ÜB" }
        ]
    },
    {
        id: "b1-kapitel-4-1cub-6e", num: "Kapitel 4 (1cÜB-6e)", name: "Justiz, Werkzeuge & Missgeschicke", emoji: "🛠️",
        items: [
            { de: "der Rechtsanwalt, \"-e", en: "lawyer (m)", hint: "1a ÜB" },
            { de: "die Rechtsanwältin, -nen", en: "lawyer (f)", hint: "1a ÜB" },
            { de: "der Richter, -", en: "judge (m)", hint: "1a ÜB" },
            { de: "die Richterin, -nen", en: "judge (f)", hint: "1a ÜB" },
            { de: "der Schreiner, -", en: "carpenter (m)", hint: "1a ÜB" },
            { de: "die Schreinerin, -nen", en: "carpenter (f)", hint: "1a ÜB" },
            { de: "das Urteil, -e", en: "verdict", hint: "1a ÜB" },
            { de: "das Verbrechen, -", en: "crime", hint: "1a ÜB" },
            { de: "der Augenblick, -e", en: "moment", hint: "1c" },
            { de: "ernst nehmen", en: "to take sth seriously", hint: "1c" },
            { de: "aus|halten", en: "to cope (with)", hint: "3" },
            { de: "frei|nehmen", en: "to take time off", hint: "5a" },
            { de: "das Besteck, -e", en: "cutlery", hint: "6a ÜB" },
            { de: "der Hammer, -", en: "hammer", hint: "6a ÜB" },
            { de: "der Kamm, \"-e", en: "comb", hint: "6a ÜB" },
            { de: "die Schere, -n", en: "scissors", hint: "6a ÜB" },
            { de: "schütten", en: "to spill", hint: "6c" },
            { de: "das Versehen, -", en: "accident", hint: "6c" },
            { de: "verwechseln", en: "to confuse", hint: "6c" },
            { de: "die Absicht, -en", en: "intention", hint: "6d" },
            { de: "verzeihen", en: "to forgive", hint: "6d" }
        ]
    },
    {
        id: "b1-kapitel-4-8b-9c", num: "Kapitel 4 (8b-9c)", name: "Bewerbung & Unterlagen", emoji: "📄",
        items: [
            { de: "ab|schreiben", en: "to copy", hint: "8b" },
            { de: "der Anhang, \"-e", en: "appendix / attachment", hint: "8b" },
            { de: "aussagekräftig", en: "meaningful", hint: "8b" },
            { de: "die Bescheinigung, -en", en: "certificate", hint: "8b" },
            { de: "das Bewerbungsfoto, -s", en: "application photo", hint: "8b" },
            { de: "das Bewerbungsschreiben, -", en: "cover letter", hint: "8b" },
            { de: "das Bewerbungstraining, -s", en: "job application training", hint: "8b" },
            { de: "eignen (sich)", en: "to be suitable for", hint: "8b" },
            { de: "erkundigen (sich)", en: "to inquire", hint: "8b" },
            { de: "die Fortbildung, -en", en: "further training", hint: "8b" },
            { de: "die Geduld (Sg.)", en: "patience", hint: "8b" },
            { de: "die Jobsuche, -n", en: "job search", hint: "8b" },
            { de: "der Lebenslauf, \"-e", en: "resume / CV", hint: "8b" },
            { de: "mit|schicken", en: "to send along", hint: "8b" },
            { de: "die Personalabteilung, -en", en: "human resources (HR)", hint: "8b" },
            { de: "der Profi, -s", en: "professional", hint: "8b" },
            { de: "relevant", en: "relevant", hint: "8b" },
            { de: "seriös", en: "respectable", hint: "8b" },
            { de: "die Voraussetzung, -en", en: "prerequisite / condition", hint: "8b" },
            { de: "die Vorlage, -n", en: "template / guideline", hint: "8b" },
            { de: "zukünftig", en: "future", hint: "8b" },
            { de: "der Zweck, -e", en: "purpose", hint: "8b" }
        ]
    },
    {
        id: "b1-kapitel-4-10a-13d", num: "Kapitel 4 (10a-13d)", name: "Vorstellungsgespräch & Auftritt", emoji: "🗣️",
        items: [
            { de: "der Eindruck, \"-e", en: "impression", hint: "10a" },
            { de: "überzeugen", en: "to convince", hint: "10a" },
            { de: "qualifiziert", en: "qualified", hint: "10c" },
            { de: "die Absprache, -n", en: "agreement", hint: "12a" },
            { de: "der Stundenlohn, \"-e", en: "hourly wage", hint: "12a" },
            { de: "die Bewerbungsunterlagen (Pl.)", en: "application documents", hint: "12b" },
            { de: "absolut", en: "absolutely", hint: "13b" },
            { de: "die Anfahrt, -en", en: "journey", hint: "13b" },
            { de: "die Aufregung (Sg.)", en: "excitement / nervousness", hint: "13b" },
            { de: "der Auftritt, -e", en: "appearance", hint: "13b" },
            { de: "der Bewerber, -", en: "applicant (m)", hint: "13b" },
            { de: "die Bewerberin, -nen", en: "applicant (f)", hint: "13b" },
            { de: "die Branche, -n", en: "field of business", hint: "13b" },
            { de: "entspannt", en: "relaxed", hint: "13b" },
            { de: "die Fähigkeit, -en", en: "ability / skill", hint: "13b" },
            { de: "die Körperhaltung, -en", en: "posture", hint: "13b" },
            { de: "die Körpersprache (Sg.)", en: "body language", hint: "13b" },
            { de: "menschlich", en: "human", hint: "13b" },
            { de: "optimistisch", en: "optimistic", hint: "13b" },
            { de: "die Persönlichkeit, -en", en: "personality", hint: "13b" },
            { de: "vor|ziehen", en: "to prefer", hint: "13b" },
            { de: "zählen", en: "to count / matter", hint: "13b" },
            { de: "der Zweifel, -", en: "doubt", hint: "13b" }
        ]
    },
    // ==========================================
    // KAPITEL 5: UMWELTFREUNDLICH?
    // ==========================================
    {
        id: "b1-kapitel-5-1a-2bub", num: "Kapitel 5 (1a-2bÜB)", name: "Müll, Konsum & Umwelt", emoji: "🌱",
        items: [
            { de: "der Abfall, \"-e", en: "waste", hint: "1a" },
            { de: "der Autofahrer, -", en: "driver (m)", hint: "1a" },
            { de: "die Autofahrerin, -nen", en: "driver (f)", hint: "1a" },
            { de: "der Durchschnitt (Sg.)", en: "average", hint: "1a" },
            { de: "europäisch", en: "European", hint: "1a" },
            { de: "der Fleischkonsum (Sg.)", en: "meat consumption", hint: "1a" },
            { de: "das Huhn, \"-er", en: "chicken", hint: "1a" },
            { de: "der Marktanteil, -e", en: "market share", hint: "1a" },
            { de: "der Papierverbrauch (Sg.)", en: "usage of paper", hint: "1a" },
            { de: "der Rekord, -e", en: "record", hint: "1a" },
            { de: "das Rind, -er", en: "beef", hint: "1a" },
            { de: "das Trinkwasser (Sg.)", en: "drinking water", hint: "1a" },
            { de: "verbrauchen", en: "to use up", hint: "1a" },
            { de: "der Verpackungsmüll (Sg.)", en: "packaging waste", hint: "1a" },
            { de: "das Bioprodukt, -e", en: "organic product", hint: "2a" },
            { de: "das Recycling (Sg.)", en: "recycling", hint: "2a" },
            { de: "regional", en: "regional", hint: "2a" },
            { de: "schützen", en: "to protect", hint: "2a" },
            { de: "der Transportweg, -e", en: "transport corridor", hint: "2a" },
            { de: "extrem", en: "extreme", hint: "2b" },
            { de: "die Herkunft, \"-e", en: "origin", hint: "2b" },
            { de: "die Marke, -n", en: "brand", hint: "2b" }
        ]
    },
    {
        id: "b1-kapitel-5-2bub-3", num: "Kapitel 5 (2bÜB-3)", name: "Klimawandel & Maßnahmen", emoji: "🌍",
        items: [
            { de: "das Abgas, -e", en: "exhaust", hint: "2b ÜB" },
            { de: "auf|halten", en: "to stop", hint: "2b ÜB" },
            { de: "bekämpfen", en: "to fight", hint: "2b ÜB" },
            { de: "beobachten", en: "to observe", hint: "2b ÜB" },
            { de: "durch|setzen", en: "to push through / force", hint: "2b ÜB" },
            { de: "erforschen", en: "to investigate", hint: "2b ÜB" },
            { de: "ergreifen", en: "to seize", hint: "2b ÜB" },
            { de: "die Ernte, -n", en: "harvest", hint: "2b ÜB" },
            { de: "ernten", en: "to harvest", hint: "2b ÜB" },
            { de: "fördern", en: "to promote", hint: "2b ÜB" },
            { de: "der Fortschritt, -e", en: "progress", hint: "2b ÜB" },
            { de: "die Klimaerwärmung (Sg.)", en: "global warming", hint: "2b ÜB" },
            { de: "der Klimawandel (Sg.)", en: "climate change", hint: "2b ÜB" },
            { de: "die Maßnahme, -n", en: "measure", hint: "2b ÜB" },
            { de: "messen", en: "to measure", hint: "2b ÜB" },
            { de: "ökologisch", en: "ecological", hint: "2b ÜB" },
            { de: "die Ressource, -n", en: "resource", hint: "2b ÜB" },
            { de: "schädlich", en: "harmful", hint: "2b ÜB" },
            { de: "der Umweltschutz (Sg.)", en: "environmental protection", hint: "2b ÜB" },
            { de: "die Umweltverschmutzung (Sg.)", en: "pollution", hint: "2b ÜB" },
            { de: "verringern", en: "to reduce", hint: "2b ÜB" },
            { de: "verschwenden", en: "to waste", hint: "2b ÜB" },
            { de: "zerstören", en: "to destroy", hint: "2b ÜB" },
            { de: "der Fußabdruck, \"-e", en: "footprint", hint: "3" }
        ]
    },
    {
        id: "b1-kapitel-5-4a-9d", num: "Kapitel 5 (4a-9d)", name: "Ökobilanz, Nachhaltigkeit & Wetter", emoji: "♻️",
        items: [
            { de: "der Geschirrspüler, -", en: "dishwasher", hint: "4a" },
            { de: "die Glasflasche, -n", en: "glass bottle", hint: "4a" },
            { de: "die Plastikflasche, -n", en: "plastic bottle", hint: "4a" },
            { de: "effizient", en: "efficient", hint: "4b" },
            { de: "die Einwegflasche, -n", en: "disposable bottle", hint: "4b" },
            { de: "die Mehrwegflasche, -n", en: "reusable bottle", hint: "4b" },
            { de: "die Ökobilanz, -en", en: "ecobalance / life-cycle assessment", hint: "4b" },
            { de: "das Resultat, -e", en: "result", hint: "4b" },
            { de: "unterscheiden", en: "to distinguish", hint: "4b" },
            { de: "die Alternative, -n", en: "alternative", hint: "6a" },
            { de: "die Pfandflasche, -n", en: "deposit bottle", hint: "6a" },
            { de: "die Energiekosten (Pl.)", en: "cost of energy", hint: "6b" },
            { de: "beschädigt", en: "damaged", hint: "9a" },
            { de: "entstehen", en: "to originate / arise", hint: "9a" },
            { de: "erhältlich", en: "available", hint: "9a" },
            { de: "haltbar", en: "durable", hint: "9a" },
            { de: "krumm", en: "crooked", hint: "9a" },
            { de: "der Kunststoff, -e", en: "plastic", hint: "9a" },
            { de: "nachhaltig", en: "sustainable", hint: "9a" },
            { de: "das Solarpanel, -e", en: "solar panel", hint: "9a" },
            { de: "vermeiden", en: "to avoid", hint: "9a" },
            { de: "retten", en: "to rescue / save", hint: "9b" },
            { de: "der Stromverbrauch (Sg.)", en: "energy usage", hint: "9d" },
            { de: "verschmutzen", en: "to pollute", hint: "9d" }
        ]
    },
    {
        id: "b1-kapitel-5-11a-13e", num: "Kapitel 5 (11a-13e)", name: "Wettererscheinungen & Engagement", emoji: "🌩️",
        items: [
            { de: "der Blitz, -e", en: "lightning", hint: "11a" },
            { de: "blitzen", en: "to flash lightning", hint: "11a" },
            { de: "der Donner, -", en: "thunder", hint: "11a" },
            { de: "donnern", en: "to thunder", hint: "11a" },
            { de: "feucht", en: "humid", hint: "11a" },
            { de: "hageln", en: "to hail", hint: "11a" },
            { de: "mild", en: "mild", hint: "11a" },
            { de: "neblig", en: "foggy", hint: "11a" },
            { de: "nieseln", en: "to drizzle", hint: "11a" },
            { de: "schwül", en: "muggy", hint: "11a" },
            { de: "stürmisch", en: "stormy", hint: "11a" },
            { de: "die Wettervorhersage, -n", en: "weather forecast", hint: "11b" },
            { de: "auf|klären", en: "to inform / clarify", hint: "13a" },
            { de: "beteiligen (sich)", en: "to participate", hint: "13a" },
            { de: "die Bevölkerung, -en", en: "population", hint: "13a" },
            { de: "der Bürger, -", en: "citizen (m)", hint: "13a" },
            { de: "die Bürgerin, -nen", en: "citizen (f)", hint: "13a" },
            { de: "das Engagement, -s", en: "commitment / involvement", hint: "13a" },
            { de: "hilflos", en: "helpless", hint: "13a" },
            { de: "pflanzen", en: "to plant", hint: "13a" },
            { de: "schaden", en: "to harm", hint: "13a" },
            { de: "auf|heben", en: "to pick up", hint: "13e" },
            { de: "die Geschwindigkeit, -en", en: "speed", hint: "13e" }
        ]
    },

    // ==========================================
    // KAPITEL 6: BLICK NACH VORN
    // ==========================================
    {
        id: "b1-kapitel-6-1a-3e", num: "Kapitel 6 (1a-3e)", name: "Zukunft, Drohnen & Vorsätze", emoji: "🚀",
        items: [
            { de: "der Chip, -s", en: "chip", hint: "1a" },
            { de: "die Drohne, -n", en: "drone", hint: "1a" },
            { de: "die Haut, \"-e", en: "skin", hint: "1a" },
            { de: "die Mobilität (Sg.)", en: "mobility", hint: "1a" },
            { de: "der Passagier, -e", en: "passenger (m)", hint: "1a" },
            { de: "die Passagierin, -nen", en: "passenger (f)", hint: "1a" },
            { de: "der Planet, -en", en: "planet", hint: "1a" },
            { de: "staubsaugen", en: "to vacuum clean", hint: "1a" },
            { de: "übernehmen", en: "to take on / overtake", hint: "1a" },
            { de: "die Prognose, -n", en: "prognosis", hint: "1b" },
            { de: "der Anlass, \"-e", en: "reason", hint: "3a" },
            { de: "vor|nehmen (sich)", en: "to plan to do sth", hint: "3a" },
            { de: "die Ausrede, -n", en: "excuse", hint: "3b" },
            { de: "befragen", en: "to question", hint: "3b" },
            { de: "fassen", en: "to make (a resolution)", hint: "3d" },
            { de: "frisch", en: "fresh", hint: "3d" },
            { de: "der Vorsatz, \"-e", en: "resolution", hint: "3d" },
            { de: "die Wahrheit, -en", en: "truth", hint: "3e" },
            { de: "gelingen", en: "to succeed", hint: "3e" },
            { de: "realisieren", en: "to realize", hint: "3e" },
            { de: "konkret", en: "concrete", hint: "3e" }
        ]
    },
    {
        id: "b1-kapitel-6-7b-8d", num: "Kapitel 6 (7b-8d)", name: "Stadt der Zukunft & Infrastruktur", emoji: "🏙️",
        items: [
            { de: "anonym", en: "anonymous", hint: "7b" },
            { de: "autonom", en: "autonomous", hint: "7b" },
            { de: "befinden (sich)", en: "to be located", hint: "7b" },
            { de: "begegnen", en: "to see / meet", hint: "7b" },
            { de: "der Dienstleistungsbereich, -e", en: "service industry", hint: "7b" },
            { de: "die Grünfläche, -n", en: "green space", hint: "7b" },
            { de: "die Hausfassade, -n", en: "house front", hint: "7b" },
            { de: "die Lebensqualität (Sg.)", en: "quality of life", hint: "7b" },
            { de: "lebenswert", en: "to be worth living in", hint: "7b" },
            { de: "das Privatauto, -s", en: "private car", hint: "7b" },
            { de: "die Solarzelle, -n", en: "solar cell", hint: "7b" },
            { de: "das Stadtviertel, -", en: "area / quarter", hint: "7b" },
            { de: "vergrößern", en: "to enlarge", hint: "7b" },
            { de: "die Windturbine, -n", en: "wind turbine", hint: "7b" },
            { de: "das Altenheim, -e", en: "care home", hint: "7c" },
            { de: "das Fundbüro, -s", en: "lost and found office", hint: "7c" },
            { de: "die Fußgängerzone, -n", en: "pedestrian zone", hint: "7c" },
            { de: "das Hallenbad, \"-er", en: "indoor swimming pool", hint: "7c" },
            { de: "die Kindertagesstätte, -n", en: "kindergarten / daycare", hint: "7c" },
            { de: "die Klinik, -en", en: "hospital", hint: "7c" },
            { de: "die Volkshochschule, -n", en: "community college", hint: "7c" },
            { de: "der Zirkus, -se", en: "circus", hint: "7c" },
            { de: "der Bürgermeister, -", en: "mayor (m)", hint: "8d" },
            { de: "die Bürgermeisterin, -nen", en: "mayor (f)", hint: "8d" },
            { de: "die Bildung (Sg.)", en: "education", hint: "8d" },
            { de: "der Wohnraum, \"-e", en: "living space", hint: "8d" }
        ]
    },
    {
        id: "b1-kapitel-6-9a-10b", num: "Kapitel 6 (9a-10b)", name: "Musik, Instrumente & Popkultur", emoji: "🎶",
        items: [
            { de: "die Vorfreude (Sg.)", en: "anticipation", hint: "9a" },
            { de: "die Melodie, -n", en: "melody", hint: "9b" },
            { de: "der Rhythmus, Rhythmen", en: "rhythm", hint: "9b" },
            { de: "die Hürde, -n", en: "hurdle", hint: "9c" },
            { de: "die Liedzeile, -n", en: "lyric / line of a song", hint: "9c" },
            { de: "nach|denken", en: "to think (about)", hint: "9c" },
            { de: "schweben", en: "to float", hint: "9c" },
            { de: "stapeln", en: "to stack", hint: "9c" },
            { de: "bewerten", en: "to evaluate", hint: "9d" },
            { de: "kitschig", en: "cheesy", hint: "9d" },
            { de: "der Bass, \"-e", en: "bass", hint: "9 ÜB" },
            { de: "die Flöte, -n", en: "flute", hint: "9 ÜB" },
            { de: "das Schlagzeug, -e", en: "drums", hint: "9 ÜB" },
            { de: "die Violine, -n", en: "violin", hint: "9 ÜB" },
            { de: "die Auszeichnung, -en", en: "award", hint: "10a" },
            { de: "die Casting-Show, -s", en: "casting show", hint: "10a" },
            { de: "die Charts (Pl.)", en: "charts", hint: "10a" },
            { de: "der Coversong, -s", en: "cover song", hint: "10a" },
            { de: "die Jury, -s", en: "jury", hint: "10a" },
            { de: "der Songwriter, -", en: "songwriter (m)", hint: "10b" },
            { de: "die Songwriterin, -nen", en: "songwriter (f)", hint: "10b" },
            { de: "mit|singen", en: "to sing along", hint: "10b" }
        ]
    },
    // ==========================================
    // KAPITEL 7: ZWISCHENMENSCHLICHES
    // ==========================================
    {
        id: "b1-kapitel-7-1a-2b", num: "Kapitel 7 (1a-2b)", name: "Beziehungen & Gesellschaft", emoji: "👥",
        items: [
            { de: "zwischenmenschlich", en: "interpersonal", hint: "1a" },
            { de: "die Erhöhung, -en", en: "increase", hint: "1a ÜB" },
            { de: "die Forderung, -en", en: "demand", hint: "1a ÜB" },
            { de: "die Gelegenheit, -en", en: "opportunity", hint: "1a ÜB" },
            { de: "die Mahnung, -en", en: "reminder", hint: "1a ÜB" },
            { de: "die Pflicht, -en", en: "duty", hint: "1a ÜB" },
            { de: "schätzen", en: "to value / appreciate", hint: "1a ÜB" },
            { de: "streiken", en: "to go on strike", hint: "1a ÜB" },
            { de: "die Versammlung, -en", en: "assembly / meeting", hint: "1a ÜB" },
            { de: "verspäten (sich)", en: "to be late", hint: "1a ÜB" },
            { de: "das Verständnis (Sg.)", en: "sympathy / understanding", hint: "1a ÜB" },
            { de: "hervor|heben", en: "to highlight", hint: "2a" },
            { de: "berufstätig", en: "working / employed", hint: "2b" },
            { de: "beschließen", en: "to decide", hint: "2b" },
            { de: "die Clique, -n", en: "clique / group of friends", hint: "2b" },
            { de: "die Erwartung, -en", en: "expectation", hint: "2b" },
            { de: "fest|stellen", en: "to realize / state", hint: "2b" },
            { de: "gut tun", en: "to benefit / do good", hint: "2b" },
            { de: "der Konflikt, -e", en: "conflict", hint: "2b" },
            { de: "zusammen|wohnen", en: "to live together", hint: "2b" }
        ]
    },
    {
        id: "b1-kapitel-7-4c-9a", num: "Kapitel 7 (4c-9a)", name: "Konflikte & Streitgespräche", emoji: "🗣️",
        items: [
            { de: "das Netzwerk, -e", en: "network", hint: "4c" },
            { de: "erschöpft", en: "exhausted", hint: "6c" },
            { de: "akzeptieren", en: "to accept", hint: "8a" },
            { de: "diplomatisch", en: "diplomatic", hint: "8a" },
            { de: "einigen (sich)", en: "to agree", hint: "8a" },
            { de: "erleichtern", en: "to facilitate", hint: "8c" },
            { de: "die Harmonie, -n", en: "harmony", hint: "9a" },
            { de: "die Kritik, -en", en: "criticism", hint: "9a" },
            { de: "nach|geben", en: "to give in", hint: "9a" },
            { de: "schweigen", en: "to remain silent", hint: "9a" },
            { de: "der Streit, -e", en: "argument", hint: "9a" },
            { de: "auf|regen (sich)", en: "to get annoyed", hint: "9a" },
            { de: "das Streitgespräch, -e", en: "argument / dispute", hint: "9a" },
            { de: "übertreiben", en: "to exaggerate", hint: "9a" },
            { de: "undiplomatisch", en: "undiplomatic", hint: "9a" }
        ]
    },
    {
        id: "b1-kapitel-7-11a-11c", num: "Kapitel 7 (11a-11c)", name: "Medien, News & Biografie", emoji: "📰",
        items: [
            { de: "amüsieren (sich)", en: "to amuse", hint: "11a ÜB" },
            { de: "angeblich", en: "allegedly", hint: "11a ÜB" },
            { de: "behaupten", en: "to claim", hint: "11a ÜB" },
            { de: "die Behauptung, -en", en: "claim", hint: "11a ÜB" },
            { de: "beweisen", en: "to prove", hint: "11a ÜB" },
            { de: "der Ehegatte, -n", en: "spouse (m)", hint: "11a ÜB" },
            { de: "die Ehegattin, -nen", en: "spouse (f)", hint: "11a ÜB" },
            { de: "der Einfluss, \"-e", en: "influence", hint: "11a ÜB" },
            { de: "die Einzelheit, -en", en: "detail", hint: "11a ÜB" },
            { de: "die Fake News (Pl.)", en: "fake news", hint: "11a ÜB" },
            { de: "fürchten", en: "to be scared", hint: "11a ÜB" },
            { de: "die Presse (Sg.)", en: "press", hint: "11a ÜB" },
            { de: "die Scheidung, -en", en: "divorce", hint: "11a ÜB" },
            { de: "die Schlagzeile, -n", en: "headline", hint: "11a ÜB" },
            { de: "leidenschaftlich", en: "passionate", hint: "11b" },
            { de: "verhindern", en: "to prevent", hint: "11b" },
            { de: "zwingen", en: "to force", hint: "11b" },
            { de: "komponieren", en: "to compose", hint: "11b" },
            { de: "dokumentieren", en: "to document", hint: "11c" },
            { de: "die Inspiration, -en", en: "inspiration", hint: "11c" }
        ]
    },
    {
        id: "b1-kapitel-7-12a-12ub", num: "Kapitel 7 (12a-12ÜB)", name: "Fabeln, Tiere & Moral", emoji: "🦊",
        items: [
            { de: "der Fuchs, \"-e", en: "fox", hint: "12a" },
            { de: "die Moral (Sg.)", en: "moral", hint: "12a" },
            { de: "beißen", en: "to bite", hint: "12b" },
            { de: "die Beute (Sg.)", en: "prey", hint: "12b" },
            { de: "brüllen", en: "to roar", hint: "12b" },
            { de: "die Fabel, -n", en: "fable", hint: "12b" },
            { de: "der Feind, -e", en: "enemy (m)", hint: "12b" },
            { de: "die Feindin, -nen", en: "enemy (f)", hint: "12b" },
            { de: "kraftlos", en: "powerless", hint: "12b" },
            { de: "lügen", en: "to lie", hint: "12b" },
            { de: "fressen", en: "to eat (animals)", hint: "12c" },
            { de: "der Rabe, -n", en: "crow / raven", hint: "12c" },
            { de: "der Schnabel, \"-", en: "beak", hint: "12c" },
            { de: "stehlen", en: "to steal", hint: "12c" },
            { de: "die Ente, -n", en: "duck", hint: "12 ÜB" },
            { de: "loben", en: "to praise", hint: "12 ÜB" },
            { de: "die Fliege, -n", en: "fly", hint: "12 ÜB" },
            { de: "die Giraffe, -n", en: "giraffe", hint: "12 ÜB" },
            { de: "das Krokodil, -e", en: "crocodile", hint: "12 ÜB" },
            { de: "die Mücke, -n", en: "mosquito", hint: "12 ÜB" },
            { de: "der Pinguin, -e", en: "penguin", hint: "12 ÜB" },
            { de: "die Schildkröte, -n", en: "turtle", hint: "12 ÜB" }
        ]
    },

    // ==========================================
    // KAPITEL 8: RUND UM KÖRPER UND GEIST
    // ==========================================
    {
        id: "b1-kapitel-8-1a-2bub", num: "Kapitel 8 (1a-2bÜB)", name: "Körper, Ernährung & Klinik", emoji: "🩺",
        items: [
            { de: "an|strengen (sich)", en: "to show effort", hint: "1a" },
            { de: "ausreichend", en: "sufficient", hint: "1a" },
            { de: "eincremen", en: "to put on lotion", hint: "1a" },
            { de: "die Flüssigkeit, -en", en: "fluid", hint: "1a" },
            { de: "das Gehirn, -e", en: "brain", hint: "1a" },
            { de: "der Geist, -er", en: "soul / spirit / mind", hint: "1a" },
            { de: "die Gymnastik (Sg.)", en: "gymnastics", hint: "1a" },
            { de: "kühlen", en: "to cool", hint: "1a" },
            { de: "der Schatten, -", en: "shadow", hint: "1a" },
            { de: "spüren", en: "to sense / feel", hint: "1a" },
            { de: "stärken", en: "to strengthen", hint: "1a" },
            { de: "atmen", en: "to breathe", hint: "2a ÜB" },
            { de: "auf|lösen", en: "to resolve / dissolve", hint: "2a ÜB" },
            { de: "blass", en: "pale", hint: "2a ÜB" },
            { de: "die Brust, \"-e", en: "chest", hint: "2a ÜB" },
            { de: "ein|nehmen", en: "to take (medicine)", hint: "2a ÜB" },
            { de: "kleben", en: "to stick", hint: "2a ÜB" },
            { de: "der Krankenwagen, -", en: "ambulance", hint: "2a ÜB" },
            { de: "krank|schreiben", en: "to take sick leave", hint: "2a ÜB" },
            { de: "die Notaufnahme, -n", en: "emergency room", hint: "2a ÜB" },
            { de: "das Schmerzmittel, -", en: "painkiller", hint: "2a ÜB" },
            { de: "verschreiben", en: "to prescribe", hint: "2a ÜB" }
        ]
    },
    {
        id: "b1-kapitel-8-5a-5c", num: "Kapitel 8 (5a-5c)", name: "Krankenhausaufenthalt & Pflege", emoji: "🏥",
        items: [
            { de: "die Besuchszeit, -en", en: "visiting hours", hint: "5a" },
            { de: "die Wertsachen (Pl.)", en: "valuables", hint: "5a" },
            { de: "der Bademantel, \"-", en: "bathrobe", hint: "5b" },
            { de: "die Bedienungsanleitung, -en", en: "instruction manual", hint: "5b" },
            { de: "beschildert", en: "marked with signs", hint: "5b" },
            { de: "die Entlassung, -en", en: "discharge", hint: "5b" },
            { de: "die Fernbedienung, -en", en: "remote control", hint: "5b" },
            { de: "das Fernsehgerät, -e", en: "television", hint: "5b" },
            { de: "grundsätzlich", en: "in general", hint: "5b" },
            { de: "der Haupteingang, \"-e", en: "main entrance", hint: "5b" },
            { de: "der Hausschuh, -e", en: "slipper", hint: "5b" },
            { de: "der Notausgang, \"-e", en: "emergency exit", hint: "5b" },
            { de: "der Schlafanzug, \"-e", en: "pyjamas", hint: "5b" },
            { de: "das Schließfach, \"-er", en: "safe / locker", hint: "5b" },
            { de: "sichtbar", en: "visible", hint: "5b" },
            { de: "untersagt sein", en: "to be forbidden", hint: "5b" },
            { de: "die Zahnbürste, -n", en: "toothbrush", hint: "5b" },
            { de: "die Zahnpasta, -pasten", en: "toothpaste", hint: "5b" },
            { de: "der Zimmernachbar, -n", en: "next-door neighbour (m)", hint: "5b" },
            { de: "die Zimmernachbarin, -nen", en: "next-door neighbour (f)", hint: "5b" },
            { de: "zuständig", en: "responsible", hint: "5b" }
        ]
    },
    {
        id: "b1-kapitel-8-6b-7b", num: "Kapitel 8 (6b-7b)", name: "Musik, Gehirn & Forschung", emoji: "🧠",
        items: [
            { de: "aus|lösen", en: "to elicit / cause", hint: "6b" },
            { de: "die Beerdigung, -en", en: "funeral", hint: "6b" },
            { de: "beruhigend", en: "soothing", hint: "6b" },
            { de: "empfinden", en: "to feel", hint: "6b" },
            { de: "feierlich", en: "festive", hint: "6b" },
            { de: "der Forscher, -", en: "researcher (m)", hint: "6b" },
            { de: "die Forscherin, -nen", en: "researcher (f)", hint: "6b" },
            { de: "gelangen", en: "to reach / attain", hint: "6b" },
            { de: "leiden", en: "to suffer", hint: "6b" },
            { de: "der Musikgeschmack (Sg.)", en: "music taste", hint: "6b" },
            { de: "der Puls (Sg.)", en: "pulse", hint: "6b" },
            { de: "sinken", en: "to sink / drop", hint: "6b" },
            { de: "der Ton, \"-e", en: "tone / sound", hint: "6b" },
            { de: "verarbeiten", en: "to process", hint: "6b" },
            { de: "die Wirkung, -en", en: "effect", hint: "6b" },
            { de: "die Heilung, -en", en: "cure / healing", hint: "6c" },
            { de: "die Einschränkung, -en", en: "limitation / restriction", hint: "7a" }
        ]
    },
    {
        id: "b1-kapitel-8-10a-13a", num: "Kapitel 8 (10a-13a)", name: "Gedächtnis & Sinneserlebnisse", emoji: "🌿",
        items: [
            { de: "die Gedächtnisleistung, -en", en: "memory skills", hint: "10a" },
            { de: "überfragt sein", en: "to be stumped", hint: "10a" },
            { de: "die Zunge, -n", en: "tongue", hint: "10a" },
            { de: "die Motivation (Sg.)", en: "motivation", hint: "11a" },
            { de: "vermitteln", en: "to convey / teach", hint: "11a" },
            { de: "aus|denken (sich)", en: "to think of / invent", hint: "11c" },
            { de: "fantasievoll", en: "imaginative", hint: "11c" },
            { de: "überprüfen", en: "to check / verify", hint: "11c" },
            { de: "ungewöhnlich", en: "unusual", hint: "11c" },
            { de: "alltäglich", en: "ordinary / daily", hint: "12a" },
            { de: "aus|breiten (sich)", en: "to spread", hint: "12a" },
            { de: "der Ausflugstipp, -s", en: "excursion tip", hint: "12a" },
            { de: "essbar", en: "edible", hint: "12a" },
            { de: "familienfreundlich", en: "family friendly", hint: "12a" },
            { de: "formen", en: "to form / shape", hint: "12a" },
            { de: "geeignet", en: "suitable", hint: "12a" },
            { de: "interaktiv", en: "interactive", hint: "12a" },
            { de: "der Klang, \"-e", en: "sound", hint: "12a" },
            { de: "der Pfad, -e", en: "path / trail", hint: "12a" },
            { de: "visuell", en: "visual", hint: "12a" }
        ]
    }
];
