// vocab-data.js
export const NETZWERK_DATA_MAPPING = [
    // ==========================================
    // KAPITEL 1: GUTEN TAG! (LENGKAP PER SUBBAB)
    // ==========================================
    {
        id: "kapitel-1-1a", num: "Kapitel 1 (1a)", name: "Begrüßung & Sprachen", emoji: "👋",
        items: [
            { de: "Bulgarisch", en: "Bulgarian", hint: "1a" },
            { de: "Deutsch", en: "German", hint: "Ich spreche Deutsch. (1a)" },
            { de: "Englisch", en: "English", hint: "1a" },
            { de: "gut", en: "good", hint: "Guten Tag! (1a)" },
            { de: "guten Tag", en: "Good day! Hello!", hint: "1a" },
            { de: "Indonesisch", en: "Indonesian", hint: "1a" },
            { de: "international", en: "international", hint: "1a" },
            { de: "Italienisch", en: "Italian", hint: "1a" },
            { de: "Japanisch", en: "Japanese", hint: "1a" },
            { de: "Russisch", en: "Russian", hint: "1a" },
            { de: "Serbisch", en: "Serbian", hint: "1a" },
            { de: "Sie", en: "you (formal)", hint: "Ordnen Sie zu. (1a)" },
            { de: "Türkisch", en: "Turkish", hint: "1a" },
            { de: "Ungarisch", en: "Hungarian", hint: "1a" },
            { de: "was", en: "what?", hint: "Was ist das? (1a)" },
            { de: "zu|ordnen", en: "to assign, to match", hint: "1a" },
            { de: "zusammen|gehören", en: "to fit together", hint: "1a" }
        ]
    },
    {
        id: "kapitel-1-1b", num: "Kapitel 1 (1b)", name: "Wörter im Kursraum", emoji: "🎒",
        items: [
            { de: "die Autobahn, -en", en: "highway", hint: "1b" },
            { de: "das Butterbrot, -e", en: "sandwich", hint: "1b" },
            { de: "das", en: "the (neutral)", hint: "das Würstchen (1b)" },
            { de: "der", en: "the (masculine)", hint: "der Kindergarten (1b)" },
            { de: "die", en: "the (feminine)", hint: "die Flasche (1b)" },
            { de: "die Flasche, -n", en: "bottle", hint: "1b" },
            { de: "das Handtuch, \"-er", en: "towel", hint: "1b" },
            { de: "der Kindergarten, \"-", en: "kindergarten", hint: "1b" },
            { de: "der Koffer, -", en: "suitcase", hint: "1b" },
            { de: "der/die Kranke, -n", en: "sick person", hint: "1b" },
            { de: "die Nudel, -n", en: "noodle", hint: "1b" },
            { de: "das Würstchen, -", en: "sausage", hint: "1b" },
            { de: "das Würstel, -", en: "sausage (Austrian variant)", hint: "1b" },
            { de: "auf", en: "in", hint: "„Würstchen“ heißt auf Italienisch... (1b)" },
            { de: "heißen", en: "to be called", hint: "er heißt, hat geheißen (1b)" },
            { de: "Ihr, Ihre", en: "your (formal)", hint: "In Ihrer Sprache? (1b)" },
            { de: "in", en: "in", hint: "In Ihrer Sprache? (1b)" },
            { de: "Spanisch", en: "Spanish", hint: "1b" },
            { de: "die Sprache, -n", en: "language", hint: "1b" },
            { de: "wie", en: "what / how", hint: "Wie heißen die Wörter? (1b)" },
            { de: "das Wort, \"-er", en: "word", hint: "1b" }
        ]
    },
    {
        id: "kapitel-1-1c-2b", num: "Kapitel 1 (1c-2b)", name: "Hallo! Kontakte", emoji: "💬",
        items: [
            { de: "andere, anderer", en: "other", hint: "1c" },
            { de: "deutsch", en: "German (adj.)", hint: "1c" },
            { de: "ein, eine", en: "a / an", hint: "1c" },
            { de: "kennen", en: "to know", hint: "er kennt, hat gekannt (1c)" },
            { de: "das Kursplakat, -e", en: "course poster", hint: "1c" },
            { de: "machen", en: "to make / do", hint: "Machen Sie ein Plakat. (1c)" },
            { de: "sammeln", en: "to collect", hint: "1c" },
            { de: "und", en: "and", hint: "1c" },
            { de: "auch", en: "also", hint: "2a" },
            { de: "bis bald", en: "see you soon", hint: "2a" },
            { de: "ciao", en: "bye / ciao", hint: "2a" },
            { de: "danke", en: "thank you", hint: "2a" },
            { de: "die", en: "the (plural)", hint: "Wie heißen die Personen? (2a)" },
            { de: "dir", en: "you (dative)", hint: "Wie geht's? Gut, und dir? (2a)" },
            { de: "du", en: "you (informal)", hint: "2a" },
            { de: "die Entschuldigung, -en", en: "excuse me / apology", hint: "2a" },
            { de: "ganz", en: "quite / pretty", hint: "Ganz gut, danke. (2a)" },
            { de: "gehen", en: "to go", hint: "Wie geht's? (2a)" },
            { de: "hallo", en: "hello", hint: "2a" },
            { de: "hören", en: "to hear / listen", hint: "2a" },
            { de: "ich", en: "I", hint: "2a" },
            { de: "lesen", en: "to read", hint: "er liest, hat gelesen (2a)" },
            { de: "die Person, -en", en: "person", hint: "2a" },
            { de: "sehr", en: "very", hint: "Danke, sehr gut. (2a)" },
            { de: "sein", en: "to be", hint: "Hallo, ich bin Julia. (2a)" },
            { de: "tschüs", en: "bye", hint: "2a" },
            { de: "wer", en: "who?", hint: "Wer bist du? (2a)" },
            { de: "die Situation, -en", en: "situation", hint: "2b" },
            { de: "spielen", en: "to play", hint: "2b" }
        ]
    },
    {
        id: "kapitel-1-2c-3b", num: "Kapitel 1 (2c-3b)", name: "Formelle Begrüßung", emoji: "👔",
        items: [
            { de: "bekannt", en: "well-known / familiar", hint: "2c" },
            { de: "der Name, -n", en: "name", hint: "2c" },
            { de: "oder", en: "or", hint: "Julia oder Niklas (2c)" },
            { de: "auf Wiedersehen", en: "goodbye (formal)", hint: "3a" },
            { de: "das", en: "this / that", hint: "Das ist Frau Kowalski. (3a)" },
            { de: "es", en: "it", hint: "Wie geht es Ihnen? (3a)" },
            { de: "Frau", en: "Mrs. / Ms. / woman", hint: "Guten Morgen, Frau Weber. (3a)" },
            { de: "gute Nacht", en: "good night", hint: "3a" },
            { de: "guten Abend", en: "good evening", hint: "3a" },
            { de: "guten Morgen", en: "good morning", hint: "3b" },
            { de: "Herr", en: "Mr. / gentleman", hint: "Guten Tag, Herr Hansen. (3b)" },
            { de: "Ihnen", en: "you (formal dative)", hint: "Wie geht es Ihnen? (3b)" },
            { de: "mein, meine", en: "my", hint: "3b" },
            { de: "formell", en: "formal", hint: "3b" },
            { de: "informell", en: "informal", hint: "3b" },
            { de: "der Nachname, -n", en: "last name / surname", hint: "3b" },
            { de: "das Personalpronomen, -", en: "personal pronoun", hint: "3b" },
            { de: "das Verb, -en", en: "verb", hint: "3b" },
            { de: "der Vorname, -n", en: "first name", hint: "3b" }
        ]
    },
    {
        id: "kapitel-1-4a-5b", num: "Kapitel 1 (4a-5b)", name: "Herkunft & Wohnort", emoji: "🌍",
        items: [
            { de: "die Antwort, -en", en: "answer", hint: "4a" },
            { de: "aus", en: "from (origin)", hint: "Ich komme aus Deutschland. (4a)" },
            { de: "Deutschland", en: "Germany", hint: "4a" },
            { de: "in", en: "in", hint: "Ich wohne in Frankfurt. (4a)" },
            { de: "kommen", en: "to come", hint: "4a" },
            { de: "der Reiseführer, -", en: "travel guide (book or male guide)", hint: "4a" },
            { de: "die Reiseführerin, -nen", en: "travel guide (female)", hint: "4a" },
            { de: "sprechen", en: "to speak", hint: "er spricht, hat gesprochen (4a)" },
            { de: "das Telefon, -e", en: "telephone", hint: "4a" },
            { de: "welche, welcher", en: "which", hint: "Welche Sprachen sprechen Sie? (4a)" },
            { de: "wo", en: "where?", hint: "Wo wohnen Sie? (4a)" },
            { de: "woher", en: "from where?", hint: "Woher kommen Sie? (4a)" },
            { de: "wohnen", en: "to live / reside", hint: "4a" },
            { de: "der Aussagesatz, \"-e", en: "declarative sentence", hint: "4b" },
            { de: "den", en: "the (masculine accusative)", hint: "Ergänzen Sie den Dialog. (4b)" },
            { de: "das Interview, -s", en: "interview", hint: "4b" },
            { de: "variieren", en: "to vary", hint: "4b" },
            { de: "die W-Frage, -n", en: "W-question (who, what, where...)", hint: "4b" },
            { de: "er", en: "he", hint: "4c" },
            { de: "ergänzen", en: "to complete / fill in", hint: "4c" },
            { de: "sie", en: "she", hint: "4c" },
            { de: "notieren", en: "to note down / write down", hint: "5a" },
            { de: "wie", en: "how / as", hint: "Wie in Aufgabe 4a. (5a)" },
            { de: "zwei", en: "two", hint: "5a" },
            { de: "der Partner, -", en: "partner (m)", hint: "5b" },
            { de: "die Partnerin, -nen", en: "partner (f)", hint: "5b" },
            { de: "raten", en: "to guess", hint: "er rät, hat geraten (5b)" },
            { de: "vor|stellen", en: "to introduce", hint: "Stellen Sie den Partner vor. (5b)" }
        ]
    },
    {
        id: "kapitel-1-6a-7c", num: "Kapitel 1 (6a-7c)", name: "Zahlen & Buchstabieren", emoji: "🔢",
        items: [
            { de: "acht", en: "eight", hint: "6a" }, { de: "achtzehn", en: "eighteen", hint: "6a" },
            { de: "der Buchstabe, -n", en: "letter (of alphabet)", hint: "6a" }, { de: "dann", en: "then / afterwards", hint: "6a" },
            { de: "drei", en: "three", hint: "6a" }, { de: "dreizehn", en: "thirteen", hint: "6a" },
            { de: "eins", en: "one", hint: "6a" }, { de: "elf", en: "eleven", hint: "6a" },
            { de: "fünf", en: "five", hint: "6a" }, { de: "fünfzehn", en: "fifteen", hint: "6a" },
            { de: "laut", en: "loud / out loud", hint: "6a" }, { de: "mit|sprechen", en: "to speak along / repeat", hint: "6a" },
            { de: "neun", en: "nine", hint: "6a" }, { de: "neunzehn", en: "nineteen", hint: "6a" },
            { de: "null", en: "zero", hint: "6a" }, { de: "sechs", en: "six", hint: "6b" },
            { de: "sechzehn", en: "sixteen", hint: "6b" }, { de: "sieben", en: "seven", hint: "6b" },
            { de: "siebzehn", en: "seventeen", hint: "6b" }, { de: "vier", en: "four", hint: "6b" },
            { de: "vierzehn", en: "fourteen", hint: "6b" }, { de: "die Zahl, -en", en: "number", hint: "6b" },
            { de: "zehn", en: "ten", hint: "6b" }, { de: "zwanzig", en: "twenty", hint: "6b" },
            { de: "zwölf", en: "twelve", hint: "6b" }, { de: "die Handynummer, -n", en: "mobile phone number", hint: "6c" },
            { de: "dein, deine", en: "your (informal)", hint: "Wie ist deine Handynummer? (6c)" },
            { de: "fragen", en: "to ask", hint: "6c" }, { de: "nach", en: "about / for", hint: "Fragen Sie nach Nummern. (6c)" },
            { de: "die Telefonnummer, -n", en: "telephone number", hint: "6c" }, { de: "das Alphabet, -e", en: "alphabet", hint: "7a" },
            { de: "mit|lesen", en: "to read along", hint: "7a" }, { de: "zuerst", en: "first / at first", hint: "7a" },
            { de: "die E-Mail-Adresse, -n", en: "email address", hint: "7b" }, { de: "das Gespräch, -e", en: "conversation / dialogue", hint: "7b" },
            { de: "man", en: "one / people (pronoun)", hint: "Wie schreibt man das? (7b)" }, { de: "minus", en: "minus", hint: "7b" },
            { de: "der Punkt, -e", en: "dot / period / point", hint: "7b" }, { de: "sagen", en: "to say", hint: "7b" },
            { de: "schreiben", en: "to write", hint: "er schreibt, hat geschrieben (7b)" }, { de: "der Unterstrich, -e", en: "underscore", hint: "7b" },
            { de: "bitte", en: "please / you're welcome", hint: "7c" }, { de: "buchstabieren", en: "to spell", hint: "7c" },
            { de: "der Dialog, -e", en: "dialogue", hint: "7c" }, { de: "ein bisschen", en: "a little bit", hint: "7c" },
            { de: "nicht", en: "not", hint: "7c" }, { de: "noch einmal", en: "once more / again", hint: "7c" }
        ]
    },
    {
        id: "kapitel-1-8a-kurz", num: "Kapitel 1 (8a-KK)", name: "Länder & Kurz und Klar", emoji: "🏳️",
        items: [
            { de: "Algerien", en: "Algeria", hint: "8a" }, { de: "Arabisch", en: "Arabic", hint: "8a" },
            { de: "Brasilien", en: "Brazil", hint: "8a" }, { de: "Französisch", en: "French", hint: "8a" },
            { de: "Japan", en: "Japan", hint: "8a" }, { de: "das Land, \"-er", en: "country", hint: "8a" },
            { de: "lernen", en: "to learn", hint: "8a" }, { de: "Österreich", en: "Austria", hint: "8a" },
            { de: "Portugiesisch", en: "Portuguese", hint: "8a" }, { de: "die Schweiz (Sg.)", en: "Switzerland", hint: "8a" },
            { de: "die USA (Pl.)", en: "USA", hint: "8a" }, { de: "die Tabelle, -n", en: "table / chart", hint: "8a" },
            { de: "Frankreich", en: "France", hint: "8a ÜB" }, { de: "Griechenland", en: "Greece", hint: "8a ÜB" },
            { de: "Italien", en: "Italy", hint: "8a ÜB" }, { de: "Mexiko", en: "Mexico", hint: "8a ÜB" },
            { de: "Portugal", en: "Portugal", hint: "8a ÜB" }, { de: "Thailand", en: "Thailand", hint: "8a ÜB" },
            { de: "Polen", en: "Poland", hint: "8b" }, { de: "Polnisch", en: "Polish", hint: "8b" },
            { de: "Rätoromanisch", en: "Romansh", hint: "8b" }, { de: "Russland", en: "Russia", hint: "8b" },
            { de: "Spanien", en: "Spain", hint: "8b" }, { de: "die Türkei (Sg.)", en: "Turkey", hint: "8b" },
            { de: "die Ukraine (Sg.)", en: "Ukraine", hint: "8b" }, { de: "zu", en: "to / at", hint: "Arbeiten Sie zu zweit. (8c)" },
            { de: "zweit", en: "second / two", hint: "Arbeiten Sie zu zweit. (8c)" }, { de: "kurz", en: "short", hint: "8e" },
            { de: "die Stadt, \"-e", en: "city / town", hint: "8e" }, { de: "der Text, -e", en: "text", hint: "8e" },
            { de: "das Befinden (Sg.)", en: "state of health / condition", hint: "Kurz und klar" }, { de: "darauf", en: "to it / on it", hint: "Kurz und klar" },
            { de: "die Grammatik, -en", en: "grammar", hint: "Kurz und klar" }, { de: "grüßen", en: "to greet", hint: "Kurz und klar" },
            { de: "reagieren", en: "to react / respond", hint: "Kurz und klar" }, { de: "das Redemittel, -", en: "useful phrases / means of expression", hint: "Kurz und klar" },
            { de: "das Subjekt, -e", en: "subject (grammar)", hint: "Kurz und klar" }, { de: "über", en: "about", hint: "Über andere sprechen. (Kurz und klar)" },
            { de: "verabschieden", en: "to say goodbye", hint: "sich verabschieden (Kurz und klar)" }, { de: "das W-Wort, \"-er", en: "question word starting with W", hint: "Kurz und klar" }
        ]
    },

    // ==========================================
    // KAPITEL 2: FREUNDE, KOLLEGEN UND ICH
    // ==========================================
    {
        id: "kapitel-2-1", num: "Kapitel 2 (1)", name: "Freizeit & Hobbys", emoji: "📸",
        items: [
            { de: "gern", en: "gladly / likes to do", hint: "Ich fotografiere gern. (1)" },
            { de: "die Leute (Pl.)", en: "people", hint: "1" },
            { de: "fotografieren", en: "to photograph", hint: "1" },
            { de: "der Freund, -e", en: "friend (male)", hint: "1" },
            { de: "die Freundin, -nen", en: "friend (female) / girlfriend", hint: "1" },
            { de: "joggen", en: "to jog", hint: "1" },
            { de: "der Kollege, -n", en: "colleague (male)", hint: "1" },
            { de: "die Kollegin, -nen", en: "colleague (female)", hint: "1" },
            { de: "die Musik (Sg.)", en: "music", hint: "1" },
            { de: "singen", en: "to sing", hint: "1" },
            { de: "tanzen", en: "to dance", hint: "1" },
            { de: "an|kreuzen", en: "to cross / tick off", hint: "1" },
            { de: "das Kino, -s", en: "cinema / movie theater", hint: "Gehst du gern ins Kino? (1)" },
            { de: "kochen", en: "to cook", hint: "1" },
            { de: "reisen", en: "to travel", hint: "1" },
            { de: "schwimmen", en: "to swim", hint: "1" },
            { de: "antworten", en: "to answer / reply", hint: "1" },
            { de: "arbeiten", en: "to work", hint: "1" },
            { de: "nein", en: "no", hint: "1" }
        ]
    },
    {
        id: "kapitel-2-2a-3d", num: "Kapitel 2 (2a-3d)", name: "Wochenende & Kommentare", emoji: "⚽",
        items: [
            { de: "das Buch, \"-er", en: "book", hint: "2a" },
            { de: "Fußball", en: "football / soccer", hint: "Er spielt gern Fußball. (2a)" },
            { de: "lieben", en: "to love", hint: "2a" },
            { de: "super", en: "super / great", hint: "2a" },
            { de: "toll", en: "great / fantastic", hint: "2a" },
            { de: "wir", en: "we", hint: "2a" },
            { de: "am", en: "on the", hint: "Kochen wir am Wochenende? (2b)" },
            { de: "die Endung, -en", en: "ending (grammar)", hint: "2b" },
            { de: "das Foto, -s", en: "photo / photograph", hint: "2b" },
            { de: "ihr", en: "you (plural informal)", hint: "Joggt ihr morgen auch? (2b)" },
            { de: "der Kommentar, -e", en: "comment", hint: "2b" },
            { de: "lustig", en: "funny / amusing", hint: "2b" },
            { de: "morgen", en: "tomorrow", hint: "3a" },
            { de: "die Spaghetti (Pl.)", en: "spaghetti", hint: "3a" },
            { de: "wirklich", en: "really / truly", hint: "3a" },
            { de: "das Wochenende, -n", en: "weekend", hint: "3a" },
            { de: "das Hobby, -s", en: "hobby", hint: "3d" }
        ]
    },
    {
        id: "kapitel-2-4a-5b", num: "Kapitel 2 (4a-5b)", name: "Wochentage & Orte", emoji: "📅",
        items: [
            { de: "der Dienstag, -e", en: "Tuesday", hint: "4a" },
            { de: "der Donnerstag, -e", en: "Thursday", hint: "4a" },
            { de: "der Freitag, -e", en: "Friday", hint: "4a" },
            { de: "der Mittwoch, -e", en: "Wednesday", hint: "4a" },
            { de: "der Montag, -e", en: "Monday", hint: "4a" },
            { de: "der Samstag, -e", en: "Saturday", hint: "4a" },
            { de: "der Sonntag, -e", en: "Sunday", hint: "4a" },
            { de: "wann", en: "when?", hint: "Wann spielst du Fußball? (4a)" },
            { de: "der Wochentag, -e", en: "day of the week", hint: "4b" },
            { de: "die Frage, -n", en: "question", hint: "4c" },
            { de: "leider", en: "unfortunately", hint: "4c" },
            { de: "das Café, -s", en: "café", hint: "5b" },
            { de: "das Museum, Museen", en: "museum", hint: "5b" },
            { de: "das Restaurant, -s", en: "restaurant", hint: "5b" },
            { de: "das Schwimmbad, \"-er", en: "swimming pool", hint: "5b" },
            { de: "das Stadion, Stadien", en: "stadium", hint: "5b" },
            { de: "der Tag, -e", en: "day", hint: "5b" },
            { de: "der Termin, -e", en: "appointment", hint: "5b" },
            { de: "das Theater, -", en: "theater", hint: "5b" }
        ]
    },
    {
        id: "kapitel-2-6a-9a", num: "Kapitel 2 (6a-9a)", name: "Berufe & Nomen", emoji: "💼",
        items: [
            { de: "der Artikel, -", en: "article (grammar)", hint: "6a" }, { de: "der Arzt, \"-e", en: "doctor (male)", hint: "6a" },
            { de: "die Ärztin, -nen", en: "doctor (female)", hint: "6a" }, { de: "das Auto, -s", en: "car", hint: "6a" },
            { de: "der Beruf, -e", en: "profession / job", hint: "6a" }, { de: "der Computer, -", en: "computer", hint: "6a" },
            { de: "das Geld, -er", en: "money", hint: "6a" }, { de: "das Glas, \"-er", en: "glass", hint: "6a" },
            { de: "der Kellner, -", en: "waiter", hint: "6a" }, { de: "die Kellnerin, -nen", en: "waitress", hint: "6a" },
            { de: "das Medikament, -e", en: "medicine / medication", hint: "6a" }, { de: "die Rechnung, -en", en: "bill / invoice", hint: "6a" },
            { de: "der Schlüssel, -", en: "key", hint: "6a" }, { de: "die Spritze, -n", en: "injection / syringe", hint: "6a" },
            { de: "der Stift, -e", en: "pen / pencil", hint: "6a" }, { de: "die Straße, -n", en: "street", hint: "6a" },
            { de: "der Student, -en", en: "student (male university)", hint: "6a" }, { de: "die Studentin, -nen", en: "student (female university)", hint: "6a" },
            { de: "die Tablette, -n", en: "pill / tablet", hint: "6a" }, { de: "der Taxifahrer, -", en: "taxi driver (male)", hint: "6a" },
            { de: "die Taxifahrerin, -nen", en: "taxi driver (female)", hint: "6a" }, { de: "das Nomen, -", en: "noun", hint: "6c" },
            { de: "der Abend, -e", en: "evening", hint: "7a" }, { de: "alt", en: "old", hint: "Ich bin 22 Jahre alt. (7a)" },
            { de: "groß", en: "large / tall", hint: "7a" }, { de: "hier", en: "here", hint: "7a" },
            { de: "das Krankenhaus, \"-er", en: "hospital", hint: "7a" }, { de: "der Krankenpfleger, -", en: "male nurse", hint: "7b" },
            { de: "die Krankenpflegerin, -nen", en: "female nurse", hint: "7b" }, { de: "meistens", en: "mostly / usually", hint: "7b" },
            { de: "der Nachmittag, -e", en: "afternoon", hint: "7b" }, { de: "nachts", en: "at night", hint: "7b" },
            { de: "der Patient, -en", en: "patient (male)", hint: "7b" }, { de: "die Patientin, -nen", en: "patient (female)", hint: "7b" },
            { de: "pro", en: "per", hint: "7b" }, { de: "die Stunde, -n", en: "hour", hint: "7b" },
            { de: "die Universität, -en", en: "university", hint: "7b" }, { de: "warten", en: "to wait", hint: "7b" },
            { de: "die Woche, -n", en: "week", hint: "7b" }, { de: "das Zimmer, -", en: "room", hint: "7b" },
            { de: "hundert", en: "hundred", hint: "7c" }, { de: "der Architekt, -en", en: "architect (male)", hint: "9a" },
            { de: "die Architektin, -nen", en: "architect (female)", hint: "9a" }, { de: "der Friseur, -e", en: "hairdresser (male)", hint: "9a" },
            { de: "die Friseurin, -nen", en: "hairdresser (female)", hint: "9a" }, { de: "der Informatiker, -", en: "IT specialist (male)", hint: "9a" },
            { de: "die Informatikerin, -nen", en: "IT specialist (female)", hint: "9a" }, { de: "der Ingenieur, -e", en: "engineer (male)", hint: "9a" },
            { de: "die Ingenieurin, -nen", en: "engineer (female)", hint: "9a" }, { de: "der Lehrer, -", en: "teacher (male)", hint: "9a" },
            { de: "die Lehrerin, -nen", en: "teacher (female)", hint: "9a" }, { de: "der Verkäufer, -", en: "salesperson (male)", hint: "9a" },
            { de: "die Verkäuferin, -nen", en: "salesperson (female)", hint: "9a" }
        ]
    },
    {
        id: "kapitel-2-9aub-kurz", num: "Kapitel 2 (9aÜB-KK)", name: "Formulare & Kurz und Klar", emoji: "📝",
        items: [
            { de: "der Elektriker, -", en: "electrician (male)", hint: "9a ÜB" }, { de: "die Elektrikerin, -nen", en: "electrician (female)", hint: "9a ÜB" },
            { de: "der Erzieher, -", en: "nursery school teacher (male)", hint: "9a ÜB" }, { de: "die Erzieherin, -nen", en: "nursery school teacher (female)", hint: "9a ÜB" },
            { de: "der Handwerker, -", en: "craftsman / handyman", hint: "9a ÜB" }, { de: "der Journalist, -en", en: "journalist (male)", hint: "9a ÜB" },
            { de: "die Journalistin, -nen", en: "journalist (female)", hint: "9a ÜB" }, { de: "der Koch, \"-e", en: "cook / chef (male)", hint: "9a ÜB" },
            { de: "die Köchin, -nen", en: "cook / chef (female)", hint: "9a ÜB" }, { de: "der Mechaniker, -", en: "mechanic (male)", hint: "9a ÜB" },
            { de: "die Mechanikerin, -nen", en: "mechanic (female)", hint: "9a ÜB" }, { de: "der Polizist, -en", en: "police officer (male)", hint: "9a ÜB" },
            { de: "die Polizistin, -nen", en: "police officer (female)", hint: "9a ÜB" }, { de: "studieren", en: "to study (at university)", hint: "9b" },
            { de: "das Wörterbuch, \"-er", en: "dictionary", hint: "10a" }, { de: "blau", en: "blue", hint: "11a" },
            { de: "grün", en: "green", hint: "11a" }, { de: "rot", en: "red", hint: "11b" },
            { de: "das Taxi, -s", en: "taxi", hint: "11b" }, { de: "die Adresse, -n", en: "address", hint: "12a" },
            { de: "der Club, -s", en: "club", hint: "12a" }, { de: "der Familienname, -n", en: "family name / surname", hint: "12b" },
            { de: "das Geburtsdatum, -daten", en: "date of birth", hint: "12b" }, { de: "der Geburtsort, -e", en: "place of birth", hint: "12b" },
            { de: "neu", en: "new", hint: "12b" }, { de: "die E-Mail, -s", en: "email", hint: "12b" },
            { de: "die Firma, Firmen", en: "company / firm", hint: "12b" }, { de: "das Formular, -e", en: "form", hint: "12b" },
            { de: "die Hausnummer, -n", en: "house number", hint: "12b" }, { de: "männlich", en: "male", hint: "12b" },
            { de: "die Postleitzahl, -en", en: "postcode / zip code", hint: "12b" }, { de: "die Schule, -n", en: "school", hint: "12b" },
            { de: "weiblich", en: "female", hint: "12b" }, { de: "der Wohnort, -e", en: "place of residence", hint: "12b" },
            { de: "negieren", en: "to negate / deny", hint: "Kurz und klar" }, { de: "ja", en: "yes", hint: "Kurz und klar" },
            { de: "doch", en: "yes (contradicting a negative question)", hint: "Kurz und klar" }, { de: "das Jahr, -e", en: "year", hint: "Kurz und klar" },
            { de: "die Kettenspiel, -e", en: "chain game", hint: "Kurz und klar" }, { de: "das Kärtchen, -", en: "small card", hint: "Kurz und klar" },
            { de: "der Plural (Sg.)", en: "plural", hint: "Kurz und klar" }, { de: "Sg. (Singular)", en: "singular", hint: "Kurz und klar" },
            { de: "Pl. (Plural)", en: "plural", hint: "Kurz und klar" }, { de: "die Angabe, -n", en: "information / statement", hint: "Kurz und klar" }
        ]
    }
];
