
export const NETZWERK_DATA_MAPPING = [
    // ==========================================
    // KAPITEL 1: GUTE REISE!
    // ==========================================
    {
        id: "b1-kapitel-1-1a-3b", num: "Kapitel 1 (1a-3b)", name: "Natur, Urlaub & Genuss", emoji: "🏕️",
        items: [
            { de: "faulenzen", en: "to lounge around", hint: "1a ÜB" },
            { de: "giftig", en: "poisonous", hint: "1a ÜB" },
            { de: "der Himmel, -", en: "sky", hint: "1a ÜB" },
            { de: "im Freien", en: "outdoors", hint: "1a ÜB" },
            { de: "das Insekt, -en", en: "insect", hint: "1a ÜB" },
            { de: "das Netz, -e", en: "net", hint: "1a ÜB" },
            { de: "der Pilz, -e", en: "mushroom", hint: "1a ÜB" },
            { de: "der Schutz (Sg.)", en: "protection", hint: "1a ÜB" },
            { de: "zelten", en: "to camp", hint: "1a ÜB" },
            { de: "angenehm", en: "pleasant", hint: "2" },
            { de: "die Aussicht, -en", en: "view", hint: "2" },
            { de: "drüben", en: "over there", hint: "2" },
            { de: "das Erlebnis, -se", en: "experience", hint: "2" },
            { de: "der Genuss (Sg.)", en: "treat / enjoyment", hint: "2" },
            { de: "herrlich", en: "glorious", hint: "2" },
            { de: "die Küste, -n", en: "coast", hint: "2" },
            { de: "reif", en: "ripe", hint: "2" },
            { de: "der Sand (Sg.)", en: "sand", hint: "2" },
            { de: "die Traube, -n", en: "grape", hint: "2" },
            { de: "die Entfernung, -en", en: "distance", hint: "3b" },
            { de: "das Ferienhaus, \"-er", en: "holiday home", hint: "3b" },
            { de: "gründlich", en: "thorough", hint: "3b" },
            { de: "rechtzeitig", en: "on time", hint: "3b" },
            { de: "das Urlaubsziel, -e", en: "holiday destination", hint: "3b" }
        ]
    },
    {
        id: "b1-kapitel-1-4a-7", num: "Kapitel 1 (4a-7)", name: "Urlaubsplanung & Reisebüro", emoji: "🧳",
        items: [
            { de: "erholen (sich)", en: "to relax", hint: "4a" },
            { de: "der Kompromiss, -e", en: "compromise", hint: "4a" },
            { de: "meinetwegen", en: "fine with me", hint: "4a" },
            { de: "die Urlaubsplanung, -en", en: "holiday planning", hint: "4a" },
            { de: "entspannend", en: "relaxing", hint: "5a" },
            { de: "erfahren", en: "to learn / find out", hint: "5c" },
            { de: "die Schifffahrt, -en", en: "boat trip", hint: "6a" },
            { de: "das Wellnesshotel, -s", en: "spa hotel", hint: "6a" },
            { de: "enthalten sein", en: "to be included", hint: "7" },
            { de: "die Fahrtzeit, -en", en: "travel time", hint: "7" },
            { de: "das Gästehaus, \"-er", en: "guest house", hint: "7" },
            { de: "die Halbpension (Sg.)", en: "half board", hint: "7" },
            { de: "höchstens", en: "at the most", hint: "7" },
            { de: "der Reisebüro-Mitarbeiter, -", en: "travel agent (m)", hint: "7" },
            { de: "die Reisebüro-Mitarbeiterin, -nen", en: "travel agent (f)", hint: "7" },
            { de: "der Skibus, -se", en: "ski bus", hint: "7" },
            { de: "das Skigebiet, -e", en: "ski resort", hint: "7" },
            { de: "der Skilift, -e", en: "ski lift", hint: "7" },
            { de: "die Vollpension (Sg.)", en: "full board", hint: "7" },
            { de: "der Wellness-Bereich, -e", en: "spa area", hint: "7" },
            { de: "der Winterurlaub, -e", en: "winter holiday", hint: "7" }
        ]
    },
    {
        id: "b1-kapitel-1-8b-9c", num: "Kapitel 1 (8b-9c)", name: "Reiseziele & Missgeschicke", emoji: "🚗",
        items: [
            { de: "die Badewanne, -n", en: "bathtub", hint: "8b" },
            { de: "das Boot, -e", en: "boat", hint: "8b" },
            { de: "der Einfall, \"-e", en: "idea", hint: "8b" },
            { de: "enttäuscht", en: "disappointed", hint: "8b" },
            { de: "jedenfalls", en: "in any case", hint: "8c" },
            { de: "obwohl", en: "although / even though", hint: "8c" },
            { de: "offenbar", en: "obvious / apparently", hint: "8c" },
            { de: "spazieren", en: "to go for a walk", hint: "8c" },
            { de: "die Strandpromenade, -n", en: "beach promenade", hint: "8c" },
            { de: "das Abenteuer, -", en: "adventure", hint: "9a" },
            { de: "auf|bauen", en: "to build", hint: "9a" },
            { de: "brennen", en: "to burn", hint: "9a" },
            { de: "der Eimer, -", en: "bucket", hint: "9a" },
            { de: "der Kofferraum, \"-e", en: "car boot / trunk", hint: "9a" },
            { de: "schief|gehen", en: "to go wrong", hint: "9a" },
            { de: "tragen", en: "to carry", hint: "9a" },
            { de: "verzweifelt", en: "desperate", hint: "9a" },
            { de: "die Wiese, -n", en: "meadow", hint: "9a" },
            { de: "das Zeug (Sg.)", en: "stuff", hint: "9a" },
            { de: "fest|machen", en: "to fasten", hint: "9c" },
            { de: "die Perspektive, -n", en: "perspective", hint: "9c" }
        ]
    },
    {
        id: "b1-kapitel-1-11a-13c", num: "Kapitel 1 (11a-13c)", name: "Unterwegs & Almleben", emoji: "🏔️",
        items: [
            { de: "die Zugnummer, -n", en: "train number", hint: "11a" },
            { de: "die Bushaltestelle, -n", en: "bus stop", hint: "12b" },
            { de: "das Gepäckband, \"-er", en: "baggage conveyor belt", hint: "12b" },
            { de: "der Tiergarten, \"-", en: "zoo", hint: "12b" },
            { de: "der Hauptbahnhof, \"-e", en: "central station", hint: "12c" },
            { de: "die Alm, -en", en: "alpine pasture", hint: "13a" },
            { de: "begeistert", en: "enthusiastic", hint: "13a" },
            { de: "beinahe", en: "almost", hint: "13a" },
            { de: "die Einsamkeit (Sg.)", en: "solitude / loneliness", hint: "13a" },
            { de: "der Empfang (Sg.)", en: "reception / signal", hint: "13a" },
            { de: "entschließen (sich)", en: "to decide", hint: "13a" },
            { de: "erholt", en: "relaxed / recovered", hint: "13a" },
            { de: "erkälten (sich)", en: "to have a cold", hint: "13a" },
            { de: "das Gebirge, -", en: "mountains / mountain range", hint: "13a" },
            { de: "das Heimweh (Sg.)", en: "homesickness", hint: "13a" },
            { de: "die Hütte, -n", en: "hut / lodge", hint: "13a" },
            { de: "die Käserei, -en", en: "cheese factory", hint: "13a" },
            { de: "melken", en: "to milk", hint: "13a" },
            { de: "der Sonnenaufgang, \"-e", en: "sunrise", hint: "13a" },
            { de: "der Terminkalender, -", en: "diary / schedule", hint: "13a" },
            { de: "der Olivenbaum, \"-e", en: "olive tree", hint: "13b" },
            { de: "die Abneigung, -en", en: "dislike", hint: "13c" }
        ]
    },
    // ==========================================
    // KAPITEL 2: DAS IST JA PRAKTISCH!
    // ==========================================
    {
        id: "b1-kapitel-2-1a-3a", num: "Kapitel 2 (1a-3a)", name: "Technik, Bedienung & Reparatur", emoji: "🔌",
        items: [
            { de: "benötigen", en: "to need", hint: "1a" },
            { de: "der Fingerabdruck, \"-e", en: "fingerprint", hint: "1a" },
            { de: "der Funkkopfhörer, -", en: "wireless headphones", hint: "1a" },
            { de: "das Lastenfahrrad, \"-er", en: "freight bicycle", hint: "1a" },
            { de: "der Sprachassistent, -en", en: "language assistant", hint: "1a" },
            { de: "der Türöffner, -", en: "door opener", hint: "1a" },
            { de: "die Taste, -n", en: "key / button", hint: "1b" },
            { de: "der Transport, -e", en: "transport", hint: "1b" },
            { de: "an|schließen", en: "to connect / plug in", hint: "1b ÜB" },
            { de: "auf|laden", en: "to charge", hint: "1b ÜB" },
            { de: "bedienen", en: "to use / operate", hint: "1b ÜB" },
            { de: "ein|setzen", en: "to insert", hint: "1b ÜB" },
            { de: "ein|stecken", en: "to plug (in)", hint: "1b ÜB" },
            { de: "installieren", en: "to install", hint: "1b ÜB" },
            { de: "stumm", en: "mute / silent", hint: "1b ÜB" },
            { de: "die Anleitung, -en", en: "instruction", hint: "3a" },
            { de: "an|schaffen (sich)", en: "to get / obtain", hint: "3a" },
            { de: "herunter|fallen", en: "to fall down", hint: "3a" },
            { de: "kaputt|gehen", en: "to break", hint: "3a" },
            { de: "lohnen (sich)", en: "to be worth it", hint: "3a" },
            { de: "das Sonderangebot, -e", en: "special offer", hint: "3a" },
            { de: "der Staubsauger, -", en: "vacuum cleaner", hint: "3a" }
        ]
    },
    {
        id: "b1-kapitel-2-3e-5c", num: "Kapitel 2 (3e-5c)", name: "Einkauf, Garantie & Reklamation", emoji: "💳",
        items: [
            { de: "nähen", en: "to sew", hint: "3e" },
            { de: "reinigen", en: "to clean", hint: "3e" },
            { de: "streichen", en: "to paint", hint: "3e" },
            { de: "der Kopfhörer, -", en: "headphones", hint: "4a" },
            { de: "das Ladekabel, -", en: "charger cable", hint: "4a" },
            { de: "die Powerbank, -s", en: "powerbank", hint: "4a" },
            { de: "daher", en: "therefore", hint: "4b" },
            { de: "darum", en: "that's why", hint: "4b" },
            { de: "deswegen", en: "therefore", hint: "4b" },
            { de: "der Handyakku, -s", en: "mobile phone battery", hint: "4b" },
            { de: "sodass", en: "so that", hint: "4b" },
            { de: "die EC-Karte, -n", en: "debit card", hint: "5a ÜB" },
            { de: "die Gebrauchsanweisung, -en", en: "instructions", hint: "5a ÜB" },
            { de: "die Geheimzahl, -en", en: "PIN", hint: "5a ÜB" },
            { de: "der Geldautomat, -en", en: "ATM", hint: "5a ÜB" },
            { de: "das Girokonto, -konten", en: "checking account", hint: "5a ÜB" },
            { de: "gratis", en: "free", hint: "5a ÜB" },
            { de: "der Rabatt, -e", en: "discount", hint: "5a ÜB" },
            { de: "verraten", en: "to reveal", hint: "5a ÜB" },
            { de: "zurück|zahlen", en: "to pay back", hint: "5a ÜB" },
            { de: "die Garantie, -n", en: "warranty", hint: "5b" },
            { de: "die Quittung, -en", en: "receipt", hint: "5b" },
            { de: "reklamieren", en: "to complain / exchange", hint: "5b" }
        ]
    },
    {
        id: "b1-kapitel-2-6a-7d", num: "Kapitel 2 (6a-7d)", name: "Smart Home & Technologie", emoji: "🏠",
        items: [
            { de: "die Technologie, -n", en: "technology", hint: "6a" },
            { de: "die Vorstellungen (Pl.)", en: "ideas / suggestions", hint: "6a" },
            { de: "die Alarmanlage, -n", en: "alarm system", hint: "6b" },
            { de: "die Ausnahme, -n", en: "exception", hint: "6b" },
            { de: "bemerken", en: "to notice", hint: "6b" },
            { de: "bereits", en: "already", hint: "6b" },
            { de: "berühren", en: "to touch", hint: "6b" },
            { de: "der Einbruch, \"-e", en: "break-in", hint: "6b" },
            { de: "gleichzeitig", en: "simultaneous", hint: "6b" },
            { de: "die Jalousie, -n", en: "shutter / blind", hint: "6b" },
            { de: "steuern", en: "to control", hint: "6b" },
            { de: "der Tagesablauf, \"-e", en: "daily routine", hint: "6b" },
            { de: "die Wand, \"-e", en: "wall", hint: "6b" },
            { de: "an|passen", en: "to adjust", hint: "6d" },
            { de: "ein|schalten", en: "to switch on", hint: "6d" },
            { de: "geschehen", en: "to happen", hint: "7a" },
            { de: "leisten (sich)", en: "to afford", hint: "7a" },
            { de: "entsprechen", en: "to correspond", hint: "7b" },
            { de: "sparsam", en: "frugal / economical", hint: "7c" },
            { de: "die Gefahr, -en", en: "danger", hint: "7d" }
        ]
    },
    {
        id: "b1-kapitel-2-9b-11", num: "Kapitel 2 (9b-11)", name: "Werbung & Konsumverhalten", emoji: "📢",
        items: [
            { de: "die Werbeanzeige, -n", en: "advertisement", hint: "9b" },
            { de: "ansprechend", en: "appealing", hint: "9c" },
            { de: "unmodern", en: "unfashionable", hint: "9c" },
            { de: "unverständlich", en: "incomprehensible", hint: "9c" },
            { de: "ausgezeichnet", en: "excellent", hint: "9d" },
            { de: "frech", en: "cheeky", hint: "9d" },
            { de: "merkwürdig", en: "strange", hint: "9d" },
            { de: "seltsam", en: "odd", hint: "9d" },
            { de: "der Klebefilm, -e", en: "adhesive tape", hint: "10a" },
            { de: "der Markenname, -n", en: "brand name", hint: "10a" },
            { de: "die Schmerztablette, -n", en: "painkiller", hint: "10a" },
            { de: "das Taschentuch, \"-er", en: "handkerchief", hint: "10a" },
            { de: "aufmerksam", en: "attentive", hint: "10b" },
            { de: "beeinflussen", en: "to influence", hint: "10b" },
            { de: "genügen", en: "to suffice", hint: "10b" },
            { de: "das Kaufverhalten, -", en: "shopping behaviour", hint: "10b" },
            { de: "das Unternehmen, -", en: "company", hint: "10b" },
            { de: "das Verhalten, -", en: "behaviour", hint: "10b" },
            { de: "vertrauen", en: "to trust", hint: "10b" },
            { de: "der Werbetrick, -s", en: "advertising trick", hint: "10c" },
            { de: "das Wortspiel, -e", en: "pun / play on words", hint: "10c" },
            { de: "ungesund", en: "unhealthy", hint: "11" },
            { de: "verbieten", en: "to forbid", hint: "11" }
        ]
    },
    // ==========================================
    // KAPITEL 3: VERÄNDERUNGEN
    // ==========================================
    {
        id: "b1-kapitel-3-1a-2ub", num: "Kapitel 3 (1a-2ÜB)", name: "Arbeit, Gesundheit & Ernährung", emoji: "🥦",
        items: [
            { de: "der Arbeiter, -", en: "worker (m)", hint: "1a" },
            { de: "die Arbeiterin, -nen", en: "worker (f)", hint: "1a" },
            { de: "automatisiert", en: "automated", hint: "1a" },
            { de: "die Bedingung, -en", en: "condition", hint: "1a" },
            { de: "die Behandlung, -en", en: "treatment", hint: "1a" },
            { de: "die Diagnose, -n", en: "diagnosis", hint: "1a" },
            { de: "die Hygiene (Sg.)", en: "hygiene", hint: "1a" },
            { de: "die Konkurrenz (Sg.)", en: "competition", hint: "1a" },
            { de: "medizinisch", en: "medical", hint: "1a" },
            { de: "monoton", en: "monotonous", hint: "1a" },
            { de: "operieren", en: "to operate", hint: "1a" },
            { de: "die Pflegekraft, \"-e", en: "caregiver", hint: "1a" },
            { de: "die Schulbildung (Sg.)", en: "education", hint: "1a" },
            { de: "die Strafe, -n", en: "punishment / penalty", hint: "1a" },
            { de: "tolerant", en: "tolerant", hint: "1a" },
            { de: "ausschließlich", en: "exclusive", hint: "2 ÜB" },
            { de: "bewusst", en: "conscious", hint: "2 ÜB" },
            { de: "biologisch", en: "biological", hint: "2 ÜB" },
            { de: "die Diät, -en", en: "diet", hint: "2 ÜB" },
            { de: "ernähren (sich)", en: "to eat / nourish", hint: "2 ÜB" },
            { de: "die Ernährung (Sg.)", en: "nutrition", hint: "2 ÜB" },
            { de: "das Nahrungsmittel, -", en: "food", hint: "2 ÜB" },
            { de: "vegan", en: "vegan", hint: "2 ÜB" },
            { de: "vegetarisch", en: "vegetarian", hint: "2 ÜB" }
        ]
    },
    {
        id: "a1-kapitel-3-3a-3c", num: "Kapitel 3 (3a-3c)", name: "Lebenswege & Herausforderungen", emoji: "🌱",
        items: [
            { de: "erben", en: "to inherit", hint: "3a" },
            { de: "führen", en: "to lead (to)", hint: "3a" },
            { de: "gewohnt", en: "usual", hint: "3a" },
            { de: "die Krisensituation, -en", en: "crisis (situation)", hint: "3a" },
            { de: "die Lebensgeschichte, -n", en: "life story", hint: "3a" },
            { de: "der Lebensweg, -e", en: "path in life", hint: "3a" },
            { de: "der Prozess, -e", en: "process", hint: "3a" },
            { de: "der Todesfall, \"-e", en: "death", hint: "3a" },
            { de: "die Trennung, -en", en: "separation", hint: "3a" },
            { de: "der Wendepunkt, -e", en: "turning point", hint: "3a" },
            { de: "das Anliegen, -", en: "issue", hint: "3c" },
            { de: "der Buchautor, -en", en: "author (m)", hint: "3c" },
            { de: "die Buchautorin, -nen", en: "author (f)", hint: "3c" },
            { de: "ein|setzen (sich)", en: "to support", hint: "3c" },
            { de: "die Herausforderung, -en", en: "challenge", hint: "3c" },
            { de: "der Mut (Sg.)", en: "courage", hint: "3c" },
            { de: "die Rückkehr (Sg.)", en: "return", hint: "3c" },
            { de: "sammeln", en: "to gain / collect", hint: "3c" },
            { de: "das Schutzprojekt, -e", en: "protection project", hint: "3c" },
            { de: "die Sehnsucht, \"-e", en: "longing / desire", hint: "3c" },
            { de: "verursachen", en: "to cause", hint: "3c" },
            { de: "wesentlich", en: "considerable", hint: "3c" },
            { de: "das Wildtier, -e", en: "wild animal", hint: "3c" }
        ]
    },
    {
        id: "b1-kapitel-3-4b-6d", num: "Kapitel 3 (4b-6d)", name: "Erfolge, Liebe & Beziehungen", emoji: "❤️",
        items: [
            { de: "ehren", en: "to honour", hint: "4b" },
            { de: "gelähmt", en: "paralyzed", hint: "4b" },
            { de: "der Held, -en", en: "hero (m)", hint: "4b" },
            { de: "die Heldin, -nen", en: "hero (f)", hint: "4b" },
            { de: "der Höhepunkt, -e", en: "peak", hint: "4b" },
            { de: "kämpfen", en: "to fight", hint: "4b" },
            { de: "mittlerweile", en: "meanwhile", hint: "4b" },
            { de: "der Optimismus (Sg.)", en: "optimism", hint: "4b" },
            { de: "politisch", en: "political", hint: "4b" },
            { de: "das Privatleben (Sg.)", en: "private life", hint: "4b" },
            { de: "stürzen", en: "to fall", hint: "4b" },
            { de: "die Wirbelsäule, -n", en: "spine", hint: "4b" },
            { de: "begeistern", en: "to delight / inspire", hint: "4d" },
            { de: "historisch", en: "historical", hint: "4d" },
            { de: "auf|wachen", en: "to wake up", hint: "5b" },
            { de: "frisch", en: "newly / fresh", hint: "5b" },
            { de: "liebevoll", en: "loving", hint: "5b" },
            { de: "die Schwiegereltern (Pl.)", en: "parents-in-law", hint: "5b" },
            { de: "verlieben (sich)", en: "to fall in love", hint: "5b" },
            { de: "verschwinden", en: "to disappear", hint: "5b" },
            { de: "das Verhältnis, -se", en: "relationship", hint: "6b" },
            { de: "überqueren", en: "to cross", hint: "6c ÜB" },
            { de: "auf|geben", en: "to forsake / give up", hint: "6d" }
        ]
    },
    {
        id: "b1-kapitel-3-9a-10b", num: "Kapitel 3 (9a-10b)", name: "Etikette & Höflichkeit", emoji: "🤝",
        items: [
            { de: "veröffentlichen", en: "to release / publish", hint: "9a" },
            { de: "aus|suchen", en: "to choose", hint: "9c" },
            { de: "höflich", en: "polite", hint: "10a" },
            { de: "begrüßen", en: "to greet", hint: "10a" },
            { de: "das Benehmen (Sg.)", en: "behaviour", hint: "10a" },
            { de: "anwesend", en: "present", hint: "10b" },
            { de: "auf|halten", en: "to hold open", hint: "10b" },
            { de: "die Begrüßung, -en", en: "greeting", hint: "10b" },
            { de: "die Beziehung, -en", en: "relationship", hint: "10b" },
            { de: "duzen", en: "to use the informal greeting", hint: "10b" },
            { de: "der Gastgeber, -", en: "host (m)", hint: "10b" },
            { de: "die Gastgeberin, -nen", en: "host (f)", hint: "10b" },
            { de: "die Gewohnheit, -en", en: "habit", hint: "10b" },
            { de: "hierarchisch", en: "hierarchical", hint: "10b" },
            { de: "ignorieren", en: "to ignore", hint: "10b" },
            { de: "siezen", en: "to use the formal greeting", hint: "10b" },
            { de: "üblich", en: "usual", hint: "10b" },
            { de: "umarmen", en: "to hug", hint: "10b" },
            { de: "unsicher", en: "insecure", hint: "10b" },
            { de: "verhalten (sich)", en: "to behave", hint: "10b" },
            { de: "vertraut", en: "familiar", hint: "10b" },
            { de: "der/die Vorgesetzte, -n", en: "superior", hint: "10b" },
            { de: "die Wange, -n", en: "cheek", hint: "10b" }
        ]
    },
    // ==========================================
    // KAPITEL 4: ARBEITSWELT
    // ==========================================
    {
        id: "b1-kapitel-4-1b-1cub", num: "Kapitel 4 (1b-1cÜB)", name: "Berufe, Industrie & Recht", emoji: "⚖️",
        items: [
            { de: "die Analyse, -n", en: "analysis", hint: "1b" },
            { de: "aus|tragen", en: "to deliver", hint: "1b" },
            { de: "der Briefträger, -", en: "postal carrier (m)", hint: "1b" },
            { de: "die Briefträgerin, -nen", en: "postal carrier (f)", hint: "1b" },
            { de: "der Chemiker, -", en: "chemist (m)", hint: "1b" },
            { de: "die Chemikerin, -nen", en: "chemist (f)", hint: "1b" },
            { de: "die Elektronik (Sg.)", en: "electronics", hint: "1b" },
            { de: "exakt", en: "exact", hint: "1b" },
            { de: "der Mechatroniker, -", en: "mechatronics engineer (m)", hint: "1b" },
            { de: "die Mechatronikerin, -nen", en: "mechatronics engineer (f)", hint: "1b" },
            { de: "das Metall, -e", en: "metal", hint: "1b" },
            { de: "zu|stellen", en: "to deliver", hint: "1b" },
            { de: "die Akte, -n", en: "file / document", hint: "1a ÜB" },
            { de: "der/die Angeklagte, -n", en: "defendant", hint: "1a ÜB" },
            { de: "das Einkommen, -", en: "income", hint: "1a ÜB" },
            { de: "der Elektroingenieur, -e", en: "electrical engineer (m)", hint: "1a ÜB" },
            { de: "die Elektroingenieurin, -nen", en: "electrical engineer (f)", hint: "1a ÜB" },
            { de: "gerecht", en: "fair / just", hint: "1a ÜB" },
            { de: "das Gericht, -e", en: "court (of law)", hint: "1a ÜB" },
            { de: "die Gerichtsverhandlung, -en", en: "trial", hint: "1a ÜB" },
            { de: "her|stellen", en: "to produce / create", hint: "1a ÜB" },
            { de: "die Industrie, -n", en: "industry", hint: "1a ÜB" },
            { de: "die Landwirtschaft (Sg.)", en: "agriculture", hint: "1a ÜB" }
        ]
    },
    {
        id: "b1-kapitel-4-1cub-6e", num: "Kapitel 4 (1cÜB-6e)", name: "Justiz, Werkzeuge & Missgeschicke", emoji: "🛠️",
        items: [
            { de: "der Rechtsanwalt, \"-e", en: "lawyer (m)", hint: "1a ÜB" },
            { de: "die Rechtsanwältin, -nen", en: "lawyer (f)", hint: "1a ÜB" },
            { de: "der Richter, -", en: "judge (m)", hint: "1a ÜB" },
            { de: "die Richterin, -nen", en: "judge (f)", hint: "1a ÜB" },
            { de: "der Schreiner, -", en: "carpenter (m)", hint: "1a ÜB" },
            { de: "die Schreinerin, -nen", en: "carpenter (f)", hint: "1a ÜB" },
            { de: "das Urteil, -e", en: "verdict", hint: "1a ÜB" },
            { de: "das Verbrechen, -", en: "crime", hint: "1a ÜB" },
            { de: "der Augenblick, -e", en: "moment", hint: "1c" },
            { de: "ernst nehmen", en: "to take sth seriously", hint: "1c" },
            { de: "aus|halten", en: "to cope (with)", hint: "3" },
            { de: "frei|nehmen", en: "to take time off", hint: "5a" },
            { de: "das Besteck, -e", en: "cutlery", hint: "6a ÜB" },
            { de: "der Hammer, -", en: "hammer", hint: "6a ÜB" },
            { de: "der Kamm, \"-e", en: "comb", hint: "6a ÜB" },
            { de: "die Schere, -n", en: "scissors", hint: "6a ÜB" },
            { de: "schütten", en: "to spill", hint: "6c" },
            { de: "das Versehen, -", en: "accident", hint: "6c" },
            { de: "verwechseln", en: "to confuse", hint: "6c" },
            { de: "die Absicht, -en", en: "intention", hint: "6d" },
            { de: "verzeihen", en: "to forgive", hint: "6d" }
        ]
    },
    {
        id: "b1-kapitel-4-8b-9c", num: "Kapitel 4 (8b-9c)", name: "Bewerbung & Unterlagen", emoji: "📄",
        items: [
            { de: "ab|schreiben", en: "to copy", hint: "8b" },
            { de: "der Anhang, \"-e", en: "appendix / attachment", hint: "8b" },
            { de: "aussagekräftig", en: "meaningful", hint: "8b" },
            { de: "die Bescheinigung, -en", en: "certificate", hint: "8b" },
            { de: "das Bewerbungsfoto, -s", en: "application photo", hint: "8b" },
            { de: "das Bewerbungsschreiben, -", en: "cover letter", hint: "8b" },
            { de: "das Bewerbungstraining, -s", en: "job application training", hint: "8b" },
            { de: "eignen (sich)", en: "to be suitable for", hint: "8b" },
            { de: "erkundigen (sich)", en: "to inquire", hint: "8b" },
            { de: "die Fortbildung, -en", en: "further training", hint: "8b" },
            { de: "die Geduld (Sg.)", en: "patience", hint: "8b" },
            { de: "die Jobsuche, -n", en: "job search", hint: "8b" },
            { de: "der Lebenslauf, \"-e", en: "resume / CV", hint: "8b" },
            { de: "mit|schicken", en: "to send along", hint: "8b" },
            { de: "die Personalabteilung, -en", en: "human resources (HR)", hint: "8b" },
            { de: "der Profi, -s", en: "professional", hint: "8b" },
            { de: "relevant", en: "relevant", hint: "8b" },
            { de: "seriös", en: "respectable", hint: "8b" },
            { de: "die Voraussetzung, -en", en: "prerequisite / condition", hint: "8b" },
            { de: "die Vorlage, -n", en: "template / guideline", hint: "8b" },
            { de: "zukünftig", en: "future", hint: "8b" },
            { de: "der Zweck, -e", en: "purpose", hint: "8b" }
        ]
    },
    {
        id: "b1-kapitel-4-10a-13d", num: "Kapitel 4 (10a-13d)", name: "Vorstellungsgespräch & Auftritt", emoji: "🗣️",
        items: [
            { de: "der Eindruck, \"-e", en: "impression", hint: "10a" },
            { de: "überzeugen", en: "to convince", hint: "10a" },
            { de: "qualifiziert", en: "qualified", hint: "10c" },
            { de: "die Absprache, -n", en: "agreement", hint: "12a" },
            { de: "der Stundenlohn, \"-e", en: "hourly wage", hint: "12a" },
            { de: "die Bewerbungsunterlagen (Pl.)", en: "application documents", hint: "12b" },
            { de: "absolut", en: "absolutely", hint: "13b" },
            { de: "die Anfahrt, -en", en: "journey", hint: "13b" },
            { de: "die Aufregung (Sg.)", en: "excitement / nervousness", hint: "13b" },
            { de: "der Auftritt, -e", en: "appearance", hint: "13b" },
            { de: "der Bewerber, -", en: "applicant (m)", hint: "13b" },
            { de: "die Bewerberin, -nen", en: "applicant (f)", hint: "13b" },
            { de: "die Branche, -n", en: "field of business", hint: "13b" },
            { de: "entspannt", en: "relaxed", hint: "13b" },
            { de: "die Fähigkeit, -en", en: "ability / skill", hint: "13b" },
            { de: "die Körperhaltung, -en", en: "posture", hint: "13b" },
            { de: "die Körpersprache (Sg.)", en: "body language", hint: "13b" },
            { de: "menschlich", en: "human", hint: "13b" },
            { de: "optimistisch", en: "optimistic", hint: "13b" },
            { de: "die Persönlichkeit, -en", en: "personality", hint: "13b" },
            { de: "vor|ziehen", en: "to prefer", hint: "13b" },
            { de: "zählen", en: "to count / matter", hint: "13b" },
            { de: "der Zweifel, -", en: "doubt", hint: "13b" }
        ]
    }
];
