// vocab-data.js
export const NETZWERK_DATA_MAPPING = [
    // ==========================================
    // KAPITEL 1: GUTEN TAG! (LENGKAP PER SUBBAB)
    // ==========================================
    {
        id: "kapitel-1-1a", num: "Kapitel 1 (1a)", name: "Begrüßung & Sprachen", emoji: "👋",
        items: [
            { de: "Bulgarisch", en: "Bulgarian", hint: "1a" },
            { de: "Deutsch", en: "German", hint: "Ich spreche Deutsch. (1a)" },
            { de: "Englisch", en: "English", hint: "1a" },
            { de: "gut", en: "good", hint: "Guten Tag! (1a)" },
            { de: "guten Tag", en: "Good day! Hello!", hint: "1a" },
            { de: "Indonesisch", en: "Indonesian", hint: "1a" },
            { de: "international", en: "international", hint: "1a" },
            { de: "Italienisch", en: "Italian", hint: "1a" },
            { de: "Japanisch", en: "Japanese", hint: "1a" },
            { de: "Russisch", en: "Russian", hint: "1a" },
            { de: "Serbisch", en: "Serbian", hint: "1a" },
            { de: "Sie", en: "you (formal)", hint: "Ordnen Sie zu. (1a)" },
            { de: "Türkisch", en: "Turkish", hint: "1a" },
            { de: "Ungarisch", en: "Hungarian", hint: "1a" },
            { de: "was", en: "what?", hint: "Was ist das? (1a)" },
            { de: "zu|ordnen", en: "to assign, to match", hint: "1a" },
            { de: "zusammen|gehören", en: "to fit together", hint: "1a" }
        ]
    },
    {
        id: "kapitel-1-1b", num: "Kapitel 1 (1b)", name: "Wörter im Kursraum", emoji: "🎒",
        items: [
            { de: "die Autobahn, -en", en: "highway", hint: "1b" },
            { de: "das Butterbrot, -e", en: "sandwich", hint: "1b" },
            { de: "das", en: "the (neutral)", hint: "das Würstchen (1b)" },
            { de: "der", en: "the (masculine)", hint: "der Kindergarten (1b)" },
            { de: "die", en: "the (feminine)", hint: "die Flasche (1b)" },
            { de: "die Flasche, -n", en: "bottle", hint: "1b" },
            { de: "das Handtuch, \"-er", en: "towel", hint: "1b" },
            { de: "der Kindergarten, \"-", en: "kindergarten", hint: "1b" },
            { de: "der Koffer, -", en: "suitcase", hint: "1b" },
            { de: "der/die Kranke, -n", en: "sick person", hint: "1b" },
            { de: "die Nudel, -n", en: "noodle", hint: "1b" },
            { de: "das Würstchen, -", en: "sausage", hint: "1b" },
            { de: "das Würstel, -", en: "sausage (Austrian variant)", hint: "1b" },
            { de: "auf", en: "in", hint: "„Würstchen“ heißt auf Italienisch... (1b)" },
            { de: "heißen", en: "to be called", hint: "er heißt, hat geheißen (1b)" },
            { de: "Ihr, Ihre", en: "your (formal)", hint: "In Ihrer Sprache? (1b)" },
            { de: "in", en: "in", hint: "In Ihrer Sprache? (1b)" },
            { de: "Spanisch", en: "Spanish", hint: "1b" },
            { de: "die Sprache, -n", en: "language", hint: "1b" },
            { de: "wie", en: "what / how", hint: "Wie heißen die Wörter? (1b)" },
            { de: "das Wort, \"-er", en: "word", hint: "1b" }
        ]
    },
    {
        id: "kapitel-1-1c-2b", num: "Kapitel 1 (1c-2b)", name: "Hallo! Kontakte", emoji: "💬",
        items: [
            { de: "andere, anderer", en: "other", hint: "1c" },
            { de: "deutsch", en: "German (adj.)", hint: "1c" },
            { de: "ein, eine", en: "a / an", hint: "1c" },
            { de: "kennen", en: "to know", hint: "er kennt, hat gekannt (1c)" },
            { de: "das Kursplakat, -e", en: "course poster", hint: "1c" },
            { de: "machen", en: "to make / do", hint: "Machen Sie ein Plakat. (1c)" },
            { de: "sammeln", en: "to collect", hint: "1c" },
            { de: "und", en: "and", hint: "1c" },
            { de: "auch", en: "also", hint: "2a" },
            { de: "bis bald", en: "see you soon", hint: "2a" },
            { de: "ciao", en: "bye / ciao", hint: "2a" },
            { de: "danke", en: "thank you", hint: "2a" },
            { de: "die", en: "the (plural)", hint: "Wie heißen die Personen? (2a)" },
            { de: "dir", en: "you (dative)", hint: "Wie geht's? Gut, und dir? (2a)" },
            { de: "du", en: "you (informal)", hint: "2a" },
            { de: "die Entschuldigung, -en", en: "excuse me / apology", hint: "2a" },
            { de: "ganz", en: "quite / pretty", hint: "Ganz gut, danke. (2a)" },
            { de: "gehen", en: "to go", hint: "Wie geht's? (2a)" },
            { de: "hallo", en: "hello", hint: "2a" },
            { de: "hören", en: "to hear / listen", hint: "2a" },
            { de: "ich", en: "I", hint: "2a" },
            { de: "lesen", en: "to read", hint: "er liest, hat gelesen (2a)" },
            { de: "die Person, -en", en: "person", hint: "2a" },
            { de: "sehr", en: "very", hint: "Danke, sehr gut. (2a)" },
            { de: "sein", en: "to be", hint: "Hallo, ich bin Julia. (2a)" },
            { de: "tschüs", en: "bye", hint: "2a" },
            { de: "wer", en: "who?", hint: "Wer bist du? (2a)" },
            { de: "die Situation, -en", en: "situation", hint: "2b" },
            { de: "spielen", en: "to play", hint: "2b" }
        ]
    },
    {
        id: "kapitel-1-2c-3b", num: "Kapitel 1 (2c-3b)", name: "Formelle Begrüßung", emoji: "👔",
        items: [
            { de: "bekannt", en: "well-known / familiar", hint: "2c" },
            { de: "der Name, -n", en: "name", hint: "2c" },
            { de: "oder", en: "or", hint: "Julia oder Niklas (2c)" },
            { de: "auf Wiedersehen", en: "goodbye (formal)", hint: "3a" },
            { de: "das", en: "this / that", hint: "Das ist Frau Kowalski. (3a)" },
            { de: "es", en: "it", hint: "Wie geht es Ihnen? (3a)" },
            { de: "Frau", en: "Mrs. / Ms. / woman", hint: "Guten Morgen, Frau Weber. (3a)" },
            { de: "gute Nacht", en: "good night", hint: "3a" },
            { de: "guten Abend", en: "good evening", hint: "3a" },
            { de: "guten Morgen", en: "good morning", hint: "3b" },
            { de: "Herr", en: "Mr. / gentleman", hint: "Guten Tag, Herr Hansen. (3b)" },
            { de: "Ihnen", en: "you (formal dative)", hint: "Wie geht es Ihnen? (3b)" },
            { de: "mein, meine", en: "my", hint: "3b" },
            { de: "formell", en: "formal", hint: "3b" },
            { de: "informell", en: "informal", hint: "3b" },
            { de: "der Nachname, -n", en: "last name / surname", hint: "3b" },
            { de: "das Personalpronomen, -", en: "personal pronoun", hint: "3b" },
            { de: "das Verb, -en", en: "verb", hint: "3b" },
            { de: "der Vorname, -n", en: "first name", hint: "3b" }
        ]
    },
    {
        id: "kapitel-1-4a-5b", num: "Kapitel 1 (4a-5b)", name: "Herkunft & Wohnort", emoji: "🌍",
        items: [
            { de: "die Antwort, -en", en: "answer", hint: "4a" },
            { de: "aus", en: "from (origin)", hint: "Ich komme aus Deutschland. (4a)" },
            { de: "Deutschland", en: "Germany", hint: "4a" },
            { de: "in", en: "in", hint: "Ich wohne in Frankfurt. (4a)" },
            { de: "kommen", en: "to come", hint: "4a" },
            { de: "der Reiseführer, -", en: "travel guide (book or male guide)", hint: "4a" },
            { de: "die Reiseführerin, -nen", en: "travel guide (female)", hint: "4a" },
            { de: "sprechen", en: "to speak", hint: "er spricht, hat gesprochen (4a)" },
            { de: "das Telefon, -e", en: "telephone", hint: "4a" },
            { de: "welche, welcher", en: "which", hint: "Welche Sprachen sprechen Sie? (4a)" },
            { de: "wo", en: "where?", hint: "Wo wohnen Sie? (4a)" },
            { de: "woher", en: "from where?", hint: "Woher kommen Sie? (4a)" },
            { de: "wohnen", en: "to live / reside", hint: "4a" },
            { de: "der Aussagesatz, \"-e", en: "declarative sentence", hint: "4b" },
            { de: "den", en: "the (masculine accusative)", hint: "Ergänzen Sie den Dialog. (4b)" },
            { de: "das Interview, -s", en: "interview", hint: "4b" },
            { de: "variieren", en: "to vary", hint: "4b" },
            { de: "die W-Frage, -n", en: "W-question (who, what, where...)", hint: "4b" },
            { de: "er", en: "he", hint: "4c" },
            { de: "ergänzen", en: "to complete / fill in", hint: "4c" },
            { de: "sie", en: "she", hint: "4c" },
            { de: "notieren", en: "to note down / write down", hint: "5a" },
            { de: "wie", en: "how / as", hint: "Wie in Aufgabe 4a. (5a)" },
            { de: "zwei", en: "two", hint: "5a" },
            { de: "der Partner, -", en: "partner (m)", hint: "5b" },
            { de: "die Partnerin, -nen", en: "partner (f)", hint: "5b" },
            { de: "raten", en: "to guess", hint: "er rät, hat geraten (5b)" },
            { de: "vor|stellen", en: "to introduce", hint: "Stellen Sie den Partner vor. (5b)" }
        ]
    },
    {
        id: "kapitel-1-6a-7c", num: "Kapitel 1 (6a-7c)", name: "Zahlen & Buchstabieren", emoji: "🔢",
        items: [
            { de: "acht", en: "eight", hint: "6a" }, { de: "achtzehn", en: "eighteen", hint: "6a" },
            { de: "der Buchstabe, -n", en: "letter (of alphabet)", hint: "6a" }, { de: "dann", en: "then / afterwards", hint: "6a" },
            { de: "drei", en: "three", hint: "6a" }, { de: "dreizehn", en: "thirteen", hint: "6a" },
            { de: "eins", en: "one", hint: "6a" }, { de: "elf", en: "eleven", hint: "6a" },
            { de: "fünf", en: "five", hint: "6a" }, { de: "fünfzehn", en: "fifteen", hint: "6a" },
            { de: "laut", en: "loud / out loud", hint: "6a" }, { de: "mit|sprechen", en: "to speak along / repeat", hint: "6a" },
            { de: "neun", en: "nine", hint: "6a" }, { de: "neunzehn", en: "nineteen", hint: "6a" },
            { de: "null", en: "zero", hint: "6a" }, { de: "sechs", en: "six", hint: "6b" },
            { de: "sechzehn", en: "sixteen", hint: "6b" }, { de: "sieben", en: "seven", hint: "6b" },
            { de: "siebzehn", en: "seventeen", hint: "6b" }, { de: "vier", en: "four", hint: "6b" },
            { de: "vierzehn", en: "fourteen", hint: "6b" }, { de: "die Zahl, -en", en: "number", hint: "6b" },
            { de: "zehn", en: "ten", hint: "6b" }, { de: "zwanzig", en: "twenty", hint: "6b" },
            { de: "zwölf", en: "twelve", hint: "6b" }, { de: "die Handynummer, -n", en: "mobile phone number", hint: "6c" },
            { de: "dein, deine", en: "your (informal)", hint: "Wie ist deine Handynummer? (6c)" },
            { de: "fragen", en: "to ask", hint: "6c" }, { de: "nach", en: "about / for", hint: "Fragen Sie nach Nummern. (6c)" },
            { de: "die Telefonnummer, -n", en: "telephone number", hint: "6c" }, { de: "das Alphabet, -e", en: "alphabet", hint: "7a" },
            { de: "mit|lesen", en: "to read along", hint: "7a" }, { de: "zuerst", en: "first / at first", hint: "7a" },
            { de: "die E-Mail-Adresse, -n", en: "email address", hint: "7b" }, { de: "das Gespräch, -e", en: "conversation / dialogue", hint: "7b" },
            { de: "man", en: "one / people (pronoun)", hint: "Wie schreibt man das? (7b)" }, { de: "minus", en: "minus", hint: "7b" },
            { de: "der Punkt, -e", en: "dot / period / point", hint: "7b" }, { de: "sagen", en: "to say", hint: "7b" },
            { de: "schreiben", en: "to write", hint: "er schreibt, hat geschrieben (7b)" }, { de: "der Unterstrich, -e", en: "underscore", hint: "7b" },
            { de: "bitte", en: "please / you're welcome", hint: "7c" }, { de: "buchstabieren", en: "to spell", hint: "7c" },
            { de: "der Dialog, -e", en: "dialogue", hint: "7c" }, { de: "ein bisschen", en: "a little bit", hint: "7c" },
            { de: "nicht", en: "not", hint: "7c" }, { de: "noch einmal", en: "once more / again", hint: "7c" }
        ]
    },
    {
        id: "kapitel-1-8a-kurz", num: "Kapitel 1 (8a-KK)", name: "Länder & Kurz und Klar", emoji: "🏳️",
        items: [
            { de: "Algerien", en: "Algeria", hint: "8a" }, { de: "Arabisch", en: "Arabic", hint: "8a" },
            { de: "Brasilien", en: "Brazil", hint: "8a" }, { de: "Französisch", en: "French", hint: "8a" },
            { de: "Japan", en: "Japan", hint: "8a" }, { de: "das Land, \"-er", en: "country", hint: "8a" },
            { de: "lernen", en: "to learn", hint: "8a" }, { de: "Österreich", en: "Austria", hint: "8a" },
            { de: "Portugiesisch", en: "Portuguese", hint: "8a" }, { de: "die Schweiz (Sg.)", en: "Switzerland", hint: "8a" },
            { de: "die USA (Pl.)", en: "USA", hint: "8a" }, { de: "die Tabelle, -n", en: "table / chart", hint: "8a" },
            { de: "Frankreich", en: "France", hint: "8a ÜB" }, { de: "Griechenland", en: "Greece", hint: "8a ÜB" },
            { de: "Italien", en: "Italy", hint: "8a ÜB" }, { de: "Mexiko", en: "Mexico", hint: "8a ÜB" },
            { de: "Portugal", en: "Portugal", hint: "8a ÜB" }, { de: "Thailand", en: "Thailand", hint: "8a ÜB" },
            { de: "Polen", en: "Poland", hint: "8b" }, { de: "Polnisch", en: "Polish", hint: "8b" },
            { de: "Rätoromanisch", en: "Romansh", hint: "8b" }, { de: "Russland", en: "Russia", hint: "8b" },
            { de: "Spanien", en: "Spain", hint: "8b" }, { de: "die Türkei (Sg.)", en: "Turkey", hint: "8b" },
            { de: "die Ukraine (Sg.)", en: "Ukraine", hint: "8b" }, { de: "zu", en: "to / at", hint: "Arbeiten Sie zu zweit. (8c)" },
            { de: "zweit", en: "second / two", hint: "Arbeiten Sie zu zweit. (8c)" }, { de: "kurz", en: "short", hint: "8e" },
            { de: "die Stadt, \"-e", en: "city / town", hint: "8e" }, { de: "der Text, -e", en: "text", hint: "8e" },
            { de: "das Befinden (Sg.)", en: "state of health / condition", hint: "Kurz und klar" }, { de: "darauf", en: "to it / on it", hint: "Kurz und klar" },
            { de: "die Grammatik, -en", en: "grammar", hint: "Kurz und klar" }, { de: "grüßen", en: "to greet", hint: "Kurz und klar" },
            { de: "reagieren", en: "to react / respond", hint: "Kurz und klar" }, { de: "das Redemittel, -", en: "useful phrases / means of expression", hint: "Kurz und klar" },
            { de: "das Subjekt, -e", en: "subject (grammar)", hint: "Kurz und klar" }, { de: "über", en: "about", hint: "Über andere sprechen. (Kurz und klar)" },
            { de: "verabschieden", en: "to say goodbye", hint: "sich verabschieden (Kurz und klar)" }, { de: "das W-Wort, \"-er", en: "question word starting with W", hint: "Kurz und klar" }
        ]
    },

    // ==========================================
    // KAPITEL 2: FREUNDE, KOLLEGEN UND ICH
    // ==========================================
    {
        id: "kapitel-2-1", num: "Kapitel 2 (1)", name: "Freizeit & Hobbys", emoji: "📸",
        items: [
            { de: "gern", en: "gladly / likes to do", hint: "Ich fotografiere gern. (1)" },
            { de: "die Leute (Pl.)", en: "people", hint: "1" },
            { de: "fotografieren", en: "to photograph", hint: "1" },
            { de: "der Freund, -e", en: "friend (male)", hint: "1" },
            { de: "die Freundin, -nen", en: "friend (female) / girlfriend", hint: "1" },
            { de: "joggen", en: "to jog", hint: "1" },
            { de: "der Kollege, -n", en: "colleague (male)", hint: "1" },
            { de: "die Kollegin, -nen", en: "colleague (female)", hint: "1" },
            { de: "die Musik (Sg.)", en: "music", hint: "1" },
            { de: "singen", en: "to sing", hint: "1" },
            { de: "tanzen", en: "to dance", hint: "1" },
            { de: "an|kreuzen", en: "to cross / tick off", hint: "1" },
            { de: "das Kino, -s", en: "cinema / movie theater", hint: "Gehst du gern ins Kino? (1)" },
            { de: "kochen", en: "to cook", hint: "1" },
            { de: "reisen", en: "to travel", hint: "1" },
            { de: "schwimmen", en: "to swim", hint: "1" },
            { de: "antworten", en: "to answer / reply", hint: "1" },
            { de: "arbeiten", en: "to work", hint: "1" },
            { de: "nein", en: "no", hint: "1" }
        ]
    },
    {
        id: "kapitel-2-2a-3d", num: "Kapitel 2 (2a-3d)", name: "Wochenende & Kommentare", emoji: "⚽",
        items: [
            { de: "das Buch, \"-er", en: "book", hint: "2a" },
            { de: "Fußball", en: "football / soccer", hint: "Er spielt gern Fußball. (2a)" },
            { de: "lieben", en: "to love", hint: "2a" },
            { de: "super", en: "super / great", hint: "2a" },
            { de: "toll", en: "great / fantastic", hint: "2a" },
            { de: "wir", en: "we", hint: "2a" },
            { de: "am", en: "on the", hint: "Kochen wir am Wochenende? (2b)" },
            { de: "die Endung, -en", en: "ending (grammar)", hint: "2b" },
            { de: "das Foto, -s", en: "photo / photograph", hint: "2b" },
            { de: "ihr", en: "you (plural informal)", hint: "Joggt ihr morgen auch? (2b)" },
            { de: "der Kommentar, -e", en: "comment", hint: "2b" },
            { de: "lustig", en: "funny / amusing", hint: "2b" },
            { de: "morgen", en: "tomorrow", hint: "3a" },
            { de: "die Spaghetti (Pl.)", en: "spaghetti", hint: "3a" },
            { de: "wirklich", en: "really / truly", hint: "3a" },
            { de: "das Wochenende, -n", en: "weekend", hint: "3a" },
            { de: "das Hobby, -s", en: "hobby", hint: "3d" }
        ]
    },
    {
        id: "kapitel-2-4a-5b", num: "Kapitel 2 (4a-5b)", name: "Wochentage & Orte", emoji: "📅",
        items: [
            { de: "der Dienstag, -e", en: "Tuesday", hint: "4a" },
            { de: "der Donnerstag, -e", en: "Thursday", hint: "4a" },
            { de: "der Freitag, -e", en: "Friday", hint: "4a" },
            { de: "der Mittwoch, -e", en: "Wednesday", hint: "4a" },
            { de: "der Montag, -e", en: "Monday", hint: "4a" },
            { de: "der Samstag, -e", en: "Saturday", hint: "4a" },
            { de: "der Sonntag, -e", en: "Sunday", hint: "4a" },
            { de: "wann", en: "when?", hint: "Wann spielst du Fußball? (4a)" },
            { de: "der Wochentag, -e", en: "day of the week", hint: "4b" },
            { de: "die Frage, -n", en: "question", hint: "4c" },
            { de: "leider", en: "unfortunately", hint: "4c" },
            { de: "das Café, -s", en: "café", hint: "5b" },
            { de: "das Museum, Museen", en: "museum", hint: "5b" },
            { de: "das Restaurant, -s", en: "restaurant", hint: "5b" },
            { de: "das Schwimmbad, \"-er", en: "swimming pool", hint: "5b" },
            { de: "das Stadion, Stadien", en: "stadium", hint: "5b" },
            { de: "der Tag, -e", en: "day", hint: "5b" },
            { de: "der Termin, -e", en: "appointment", hint: "5b" },
            { de: "das Theater, -", en: "theater", hint: "5b" }
        ]
    },
    {
        id: "kapitel-2-6a-9a", num: "Kapitel 2 (6a-9a)", name: "Berufe & Nomen", emoji: "💼",
        items: [
            { de: "der Artikel, -", en: "article (grammar)", hint: "6a" }, { de: "der Arzt, \"-e", en: "doctor (male)", hint: "6a" },
            { de: "die Ärztin, -nen", en: "doctor (female)", hint: "6a" }, { de: "das Auto, -s", en: "car", hint: "6a" },
            { de: "der Beruf, -e", en: "profession / job", hint: "6a" }, { de: "der Computer, -", en: "computer", hint: "6a" },
            { de: "das Geld, -er", en: "money", hint: "6a" }, { de: "das Glas, \"-er", en: "glass", hint: "6a" },
            { de: "der Kellner, -", en: "waiter", hint: "6a" }, { de: "die Kellnerin, -nen", en: "waitress", hint: "6a" },
            { de: "das Medikament, -e", en: "medicine / medication", hint: "6a" }, { de: "die Rechnung, -en", en: "bill / invoice", hint: "6a" },
            { de: "der Schlüssel, -", en: "key", hint: "6a" }, { de: "die Spritze, -n", en: "injection / syringe", hint: "6a" },
            { de: "der Stift, -e", en: "pen / pencil", hint: "6a" }, { de: "die Straße, -n", en: "street", hint: "6a" },
            { de: "der Student, -en", en: "student (male university)", hint: "6a" }, { de: "die Studentin, -nen", en: "student (female university)", hint: "6a" },
            { de: "die Tablette, -n", en: "pill / tablet", hint: "6a" }, { de: "der Taxifahrer, -", en: "taxi driver (male)", hint: "6a" },
            { de: "die Taxifahrerin, -nen", en: "taxi driver (female)", hint: "6a" }, { de: "das Nomen, -", en: "noun", hint: "6c" },
            { de: "der Abend, -e", en: "evening", hint: "7a" }, { de: "alt", en: "old", hint: "Ich bin 22 Jahre alt. (7a)" },
            { de: "groß", en: "large / tall", hint: "7a" }, { de: "hier", en: "here", hint: "7a" },
            { de: "das Krankenhaus, \"-er", en: "hospital", hint: "7a" }, { de: "der Krankenpfleger, -", en: "male nurse", hint: "7b" },
            { de: "die Krankenpflegerin, -nen", en: "female nurse", hint: "7b" }, { de: "meistens", en: "mostly / usually", hint: "7b" },
            { de: "der Nachmittag, -e", en: "afternoon", hint: "7b" }, { de: "nachts", en: "at night", hint: "7b" },
            { de: "der Patient, -en", en: "patient (male)", hint: "7b" }, { de: "die Patientin, -nen", en: "patient (female)", hint: "7b" },
            { de: "pro", en: "per", hint: "7b" }, { de: "die Stunde, -n", en: "hour", hint: "7b" },
            { de: "die Universität, -en", en: "university", hint: "7b" }, { de: "warten", en: "to wait", hint: "7b" },
            { de: "die Woche, -n", en: "week", hint: "7b" }, { de: "das Zimmer, -", en: "room", hint: "7b" },
            { de: "hundert", en: "hundred", hint: "7c" }, { de: "der Architekt, -en", en: "architect (male)", hint: "9a" },
            { de: "die Architektin, -nen", en: "architect (female)", hint: "9a" }, { de: "der Friseur, -e", en: "hairdresser (male)", hint: "9a" },
            { de: "die Friseurin, -nen", en: "hairdresser (female)", hint: "9a" }, { de: "der Informatiker, -", en: "IT specialist (male)", hint: "9a" },
            { de: "die Informatikerin, -nen", en: "IT specialist (female)", hint: "9a" }, { de: "der Ingenieur, -e", en: "engineer (male)", hint: "9a" },
            { de: "die Ingenieurin, -nen", en: "engineer (female)", hint: "9a" }, { de: "der Lehrer, -", en: "teacher (male)", hint: "9a" },
            { de: "die Lehrerin, -nen", en: "teacher (female)", hint: "9a" }, { de: "der Verkäufer, -", en: "salesperson (male)", hint: "9a" },
            { de: "die Verkäuferin, -nen", en: "salesperson (female)", hint: "9a" }
        ]
    },
    {
        id: "kapitel-2-9aub-kurz", num: "Kapitel 2 (9aÜB-KK)", name: "Formulare & Kurz und Klar", emoji: "📝",
        items: [
            { de: "der Elektriker, -", en: "electrician (male)", hint: "9a ÜB" }, { de: "die Elektrikerin, -nen", en: "electrician (female)", hint: "9a ÜB" },
            { de: "der Erzieher, -", en: "nursery school teacher (male)", hint: "9a ÜB" }, { de: "die Erzieherin, -nen", en: "nursery school teacher (female)", hint: "9a ÜB" },
            { de: "der Handwerker, -", en: "craftsman / handyman", hint: "9a ÜB" }, { de: "der Journalist, -en", en: "journalist (male)", hint: "9a ÜB" },
            { de: "die Journalistin, -nen", en: "journalist (female)", hint: "9a ÜB" }, { de: "der Koch, \"-e", en: "cook / chef (male)", hint: "9a ÜB" },
            { de: "die Köchin, -nen", en: "cook / chef (female)", hint: "9a ÜB" }, { de: "der Mechaniker, -", en: "mechanic (male)", hint: "9a ÜB" },
            { de: "die Mechanikerin, -nen", en: "mechanic (female)", hint: "9a ÜB" }, { de: "der Polizist, -en", en: "police officer (male)", hint: "9a ÜB" },
            { de: "die Polizistin, -nen", en: "police officer (female)", hint: "9a ÜB" }, { de: "studieren", en: "to study (at university)", hint: "9b" },
            { de: "das Wörterbuch, \"-er", en: "dictionary", hint: "10a" }, { de: "blau", en: "blue", hint: "11a" },
            { de: "grün", en: "green", hint: "11a" }, { de: "rot", en: "red", hint: "11b" },
            { de: "das Taxi, -s", en: "taxi", hint: "11b" }, { de: "die Adresse, -n", en: "address", hint: "12a" },
            { de: "der Club, -s", en: "club", hint: "12a" }, { de: "der Familienname, -n", en: "family name / surname", hint: "12b" },
            { de: "das Geburtsdatum, -daten", en: "date of birth", hint: "12b" }, { de: "der Geburtsort, -e", en: "place of birth", hint: "12b" },
            { de: "neu", en: "new", hint: "12b" }, { de: "die E-Mail, -s", en: "email", hint: "12b" },
            { de: "die Firma, Firmen", en: "company / firm", hint: "12b" }, { de: "das Formular, -e", en: "form", hint: "12b" },
            { de: "die Hausnummer, -n", en: "house number", hint: "12b" }, { de: "männlich", en: "male", hint: "12b" },
            { de: "die Postleitzahl, -en", en: "postcode / zip code", hint: "12b" }, { de: "die Schule, -n", en: "school", hint: "12b" },
            { de: "weiblich", en: "female", hint: "12b" }, { de: "der Wohnort, -e", en: "place of residence", hint: "12b" },
            { de: "negieren", en: "to negate / deny", hint: "Kurz und klar" }, { de: "ja", en: "yes", hint: "Kurz und klar" },
            { de: "doch", en: "yes (contradicting a negative question)", hint: "Kurz und klar" }, { de: "das Jahr, -e", en: "year", hint: "Kurz und klar" },
            { de: "die Kettenspiel, -e", en: "chain game", hint: "Kurz und klar" }, { de: "das Kärtchen, -", en: "small card", hint: "Kurz und klar" },
            { de: "der Plural (Sg.)", en: "plural", hint: "Kurz und klar" }, { de: "Sg. (Singular)", en: "singular", hint: "Kurz und klar" },
            { de: "Pl. (Plural)", en: "plural", hint: "Kurz und klar" }, { de: "die Angabe, -n", en: "information / statement", hint: "Kurz und klar" }
        ]
    }

// ==========================================
    // KAPITEL 3: IN HAMBURG (LENGKAP PER SUBBAB)
    // ==========================================
    {
        id: "kapitel-3-1a-1b", num: "Kapitel 3 (1a-1b)", name: "Sehenswürdigkeiten", emoji: "⚓",
        items: [
            { de: "die Stadttour, -en", en: "city tour", hint: "1a" },
            { de: "die Station, -en", en: "station", hint: "1a" },
            { de: "der Bahnhof, \"-e", en: "train station", hint: "1b" },
            { de: "die Bauzeit (Sg.)", en: "construction period", hint: "1b" },
            { de: "der Besucher, -", en: "visitor (m)", hint: "1b" },
            { de: "die Besucherin, -nen", en: "visitor (f)", hint: "1b" },
            { de: "bis", en: "until", hint: "Bauzeit: bis 2016 (1b)" },
            { de: "breit", en: "wide", hint: "1b" },
            { de: "erste, erster", en: "first", hint: "1b" },
            { de: "der Euro, -s", en: "euro", hint: "1b" },
            { de: "hoch", en: "high", hint: "1b" },
            { de: "die Kirche, -n", en: "church", hint: "1b" },
            { de: "das Konzert, -e", en: "concert", hint: "1b" },
            { de: "das Konzerthaus, \"-er", en: "concert hall", hint: "1b" },
            { de: "die Kosten (Pl.)", en: "costs", hint: "1b" },
            { de: "der Meter, -", en: "metre", hint: "1b" },
            { de: "die Mitte (Sg.)", en: "middle", hint: "1b" },
            { de: "das Rathaus, \"-er", en: "town hall", hint: "1b" },
            { de: "der Star, -s", en: "star / celebrity", hint: "1b" },
            { de: "der Turm, \"-e", en: "tower", hint: "1b" },
            { de: "über", en: "over / more than", hint: "Der Turm ist über 120 Jahre alt. (1b)" }
        ]
    },
    {
        id: "kapitel-3-1d-2b", num: "Kapitel 3 (1d-2b)", name: "Hafen & Taxifahrt", emoji: "🚕",
        items: [
            { de: "auf", en: "on / upon", hint: "Die Schiffe fahren auf dem Fluss. (1d)" },
            { de: "bis zu", en: "up to", hint: "1d" },
            { de: "circa", en: "approximately / approx.", hint: "1d" },
            { de: "da", en: "there", hint: "1d" },
            { de: "dem", en: "the (dative masculine/neuter)", hint: "auf dem Fluss (1d)" },
            { de: "der Fluss, \"-e", en: "river", hint: "1d" },
            { de: "der Hafen, \"-", en: "harbour / port", hint: "1d" },
            { de: "in", en: "in", hint: "Der Zug fährt in 8 Stunden... (1d)" },
            { de: "das Meer, -e", en: "sea / ocean", hint: "1d" },
            { de: "der Mensch, -en", en: "human / person", hint: "1d" },
            { de: "nach", en: "to (direction)", hint: "Der Zug fährt nach Warschau. (1d)" },
            { de: "das Schiff, -e", en: "ship / boat", hint: "1d" },
            { de: "sehen", en: "to see", hint: "er sieht, hat gesehen (1d)" },
            { de: "das Symbol, -e", en: "symbol", hint: "1d" },
            { de: "der Zug, \"-e", en: "train", hint: "1d" },
            { de: "die Ausstellung, -en", en: "exhibition", hint: "1d" },
            { de: "die Brücke, -n", en: "bridge", hint: "1d" },
            { de: "lang", en: "long", hint: "1d" },
            { de: "der Ort, -e", en: "place / location / village", hint: "1d" },
            { de: "über", en: "about / on", hint: "Sammeln Sie Informationen über Ihre Stadt. (1d)" },
            { de: "grüezi", en: "hello (Swiss German)", hint: "2a" },
            { de: "grüß Gott", en: "hello (Southern German/Austrian)", hint: "2a" },
            { de: "das Hotel, -s", en: "hotel", hint: "2a" },
            { de: "moin", en: "hello / good morning (Northern German)", hint: "2a" },
            { de: "so", en: "this way / like this", hint: "So sagt man auf Deutsch: ... (2a)" },
            { de: "die Taxifahrt, -en", en: "taxi ride", hint: "2a" },
            { de: "der Weg, -e", en: "way / path", hint: "2a" },
            { de: "interessant", en: "interesting", hint: "2b" },
            { de: "die Kunsthalle, -n", en: "art gallery / museum", hint: "2b" },
            { de: "die Lösung, -en", en: "solution / answer", hint: "2b" }
        ]
    },
    {
        id: "kapitel-3-3-6c", num: "Kapitel 3 (3-6c)", name: "Verkehrsmittel & Glück", emoji: "🎫",
        items: [
            { de: "okay", en: "okay", hint: "3" },
            { de: "der Plan, \"-e", en: "plan / map", hint: "3" },
            { de: "rechts", en: "right / to the right", hint: "3" },
            { de: "richtig", en: "correct / true", hint: "3" },
            { de: "schon", en: "already", hint: "Da ist auch schon das Hotel. (3)" },
            { de: "schön", en: "beautiful / nice", hint: "3" },
            { de: "der See, -n", en: "lake", hint: "3" },
            { de: "zeichnen", en: "to draw", hint: "3" },
            { de: "auf|stehen", en: "to stand up / get up", hint: "er steht auf, ist aufgestanden (4a)" },
            { de: "bilden", en: "to form / make", hint: "Bilden Sie drei Gruppen. (4a)" },
            { de: "die Gruppe, -n", en: "group", hint: "4a" },
            { de: "passand", en: "matching / fitting", hint: "4a" },
            { de: "unbestimmt", en: "indefinite", hint: "der unbestimmte Artikel (4a)" },
            { de: "das Haus, \"-er", en: "house", hint: "4a" },
            { de: "der Satz, \"-e", en: "sentence", hint: "4a" },
            { de: "doppelt", en: "double", hint: "4b" },
            { de: "der Konsonant, -en", en: "consonant", hint: "4b" },
            { de: "der Vokal, -e", en: "vowel", hint: "4b" },
            { de: "vor", en: "before / in front of", hint: "Vor dem Nomen steht der Artikel. (4b)" },
            { de: "der Arm, -e", en: "arm", hint: "4c" },
            { de: "klopfen", en: "to knock / tap", hint: "4c" },
            { de: "kreisen", en: "to circle / rotate", hint: "4c" },
            { de: "der Tisch, -e", en: "table", hint: "4c" },
            { de: "die Bildgeschichte, -n", en: "comic strip / picture story", hint: "5a" },
            { de: "der Bus, -se", en: "bus", hint: "5a" },
            { de: "das Fahrrad, \"-er", en: "bicycle / bike", hint: "5a" },
            { de: "die U-Bahn, -en", en: "subway / underground", hint: "5a" },
            { de: "zeigen", en: "to point / show", hint: "Zeigen Sie auf das Bild. (5a)" },
            { de: "zu Fuß", en: "on foot", hint: "Pia geht zu Fuß. (5a)" },
            { de: "das Flugzeug, -e", en: "airplane / plane", hint: "5b" },
            { de: "die S-Bahn, -en", en: "suburban train", hint: "5b" },
            { de: "die Straßenbahn, -en", en: "tram", hint: "5b" },
            { de: "aber", en: "but", hint: "Jetzt aber schnell! (6a)" },
            { de: "also", en: "so / therefore", hint: "Kein Bus, also schnell! (6a)" },
            { de: "das Bild, -er", en: "picture / image", hint: "6a" },
            { de: "die Fahrkarte, -n", en: "ticket", hint: "6a" },
            { de: "das Glück (Sg.)", en: "luck / happiness", hint: "So ein Glück! (6a)" },
            { de: "heute", en: "today", hint: "6a" },
            { de: "jetzt", en: "now", hint: "6a" },
            { de: "schnell", en: "quick / fast", hint: "6a" },
            { de: "der Test, -s", en: "test", hint: "6a" },
            { de: "die Konzertkarte, -n", en: "concert ticket", hint: "6b" },
            { de: "der Negationsartikel, -", en: "negative article", hint: "6c" }
        ]
    },
    {
        id: "kapitel-3-7a-9d", num: "Kapitel 3 (7a-9d)", name: "Orientierung & Kulturevents", emoji: "🎭",
        items: [
            { de: "links", en: "left / to the left", hint: "7a" },
            { de: "die Wegbeschreibung, -en", en: "directions", hint: "7a" },
            { de: "geradeaus", en: "straight ahead", hint: "7b" },
            { de: "der Dank (Sg.)", en: "thanks", hint: "Vielen Dank. (7c)" },
            { de: "einfach", en: "easy / simple", hint: "Das ist ganz einfach. (7c)" },
            { de: "genau", en: "exactly", hint: "Ja, genau. (7c)" },
            { de: "der Imperativ, -e", en: "imperative", hint: "7c" },
            { de: "das Mal, -e", en: "time", hint: "Würfeln Sie drei Mal. (8)" },
            { de: "der Markt, \"-e", en: "market", hint: "8" },
            { de: "der Park, -s", en: "park", hint: "8" },
            { de: "der Start, -s", en: "starting line / start", hint: "8" },
            { de: "würfeln", en: "to roll the dice", hint: "8" },
            { de: "das Ziel, -e", en: "goal / destination / finish line", hint: "8" },
            { de: "an", en: "over / during", hint: "An 10 Tagen über 100 Filme. (9a)" },
            { de: "der Chor, \"-e", en: "choir", hint: "9a" },
            { de: "deutschsprachig", en: "German-speaking", hint: "9a" },
            { de: "diese, dieser", en: "this", hint: "9a" },
            { de: "dirigieren", en: "to conduct (orchestra)", hint: "9a" },
            { de: "das Event, -s", en: "event", hint: "9a" },
            { de: "das Festival, -s", en: "festival", hint: "9a" },
            { de: "der Film, -e", en: "film / movie", hint: "9a" },
            { de: "der Filmfan, -s", en: "film fan", hint: "9a" },
            { de: "der Gast, \"-e", en: "guest", hint: "9b" },
            { de: "ihr, ihre", en: "its / her", hint: "Die Stadthalle zeigt ihre Produktionen. (9b)" },
            { de: "das Orchester, -", en: "orchestra", hint: "9b" },
            { de: "die Produktion, -en", en: "production", hint: "9b" },
            { de: "das Publikum (Sg.)", en: "audience", hint: "9b" },
            { de: "der Regisseur, -e", en: "director (m)", hint: "9b" },
            { de: "die Regisseurin, -nen", en: "director (f)", hint: "9b" },
            { de: "das Requiem, -s", en: "requiem", hint: "9b" },
            { de: "der Schauspieler, -", en: "actor", hint: "9b" },
            { de: "die Schauspielerin, -nen", en: "actress", hint: "9b" },
            { de: "sein, seine", en: "his", hint: "Der Regisseur präsentiert seinen Film. (9b)" },
            { de: "der Solist, -en", en: "soloist (m)", hint: "9b" },
            { de: "die Solistin, -nen", en: "soloist (f)", hint: "9b" },
            { de: "das Theater-Festival, -s", en: "theatre festival", hint: "9b" },
            { de: "das Ticket, -s", en: "ticket", hint: "9b" },
            { de: "die Welt, -en", en: "world", hint: "9b" },
            { de: "ähnlich", en: "similar", hint: "9d" },
            { de: "finden", en: "to find / think", hint: "Finden Sie Sport interessant? (9d)" }
        ]
    },
    {
        id: "kapitel-3-10a-kurz", num: "Kapitel 3 (10a-KK)", name: "Monate & Kurz und klar", emoji: "🍂",
        items: [
            { de: "der April (Sg.)", en: "April", hint: "10a" }, { de: "der August (Sg.)", en: "August", hint: "10a" },
            { de: "der Dezember (Sg.)", en: "December", hint: "10a" }, { de: "der Februar (Sg.)", en: "February", hint: "10a" },
            { de: "der Frühling (Sg.)", en: "spring", hint: "10a" }, { de: "der Herbst (Sg.)", en: "autumn", hint: "10a" },
            { de: "der Januar (Sg.)", en: "January", hint: "10a" }, { de: "der Juli (Sg.)", en: "July", hint: "10a" },
            { de: "der Juni (Sg.)", en: "June", hint: "10a" }, { de: "der Mai (Sg.)", en: "May", hint: "10a" },
            { de: "der März (Sg.)", en: "March", hint: "10a" }, { de: "der Monat, -e", en: "month", hint: "10a" },
            { de: "der November (Sg.)", en: "November", hint: "10a" }, { de: "der Oktober (Sg.)", en: "October", hint: "10a" },
            { de: "der September (Sg.)", en: "September", hint: "10a" }, { de: "der Sommer, -", en: "summer", hint: "10a" },
            { de: "der Winter, -", en: "winter", hint: "10a" }, { de: "die Jahreszeit, -en", en: "season", hint: "10b" },
            { de: "das Plakat, -e", en: "poster", hint: "10d" },
            { de: "das Adjektiv, -e", en: "adjective", hint: "Kurz und klar" },
            { de: "das Ding, -e", en: "thing", hint: "Kurz und klar" },
            { de: "die Position, -en", en: "position", hint: "Kurz und klar" },
            { de: "stellen", en: "to ask / place", hint: "eine Frage stellen (Kurz und klar)" }
        ]
    },

    // ==========================================
    // KAPITEL 4: GUTEN APPETIT! (PER SUBBAB)
    // ==========================================
    {
        id: "kapitel-4-1a-1b", num: "Kapitel 4 (1a-1b)", name: "Lebensmittel & Frühstück", emoji: "🍏",
        items: [
            { de: "der Apfelsaft, \"-e", en: "apple juice", hint: "1a" },
            { de: "die Banane, -n", en: "banana", hint: "1a" },
            { de: "das Brötchen, -", en: "bread roll", hint: "1a" },
            { de: "die Butter (Sg.)", en: "butter", hint: "1a" },
            { de: "die/das Cola, -s", en: "cola", hint: "1a" },
            { de: "das Ei, -er", en: "egg", hint: "1a" },
            { de: "der Essig, -e", en: "vinegar", hint: "1a" },
            { de: "das Fleisch (Sg.)", en: "meat", hint: "1a" },
            { de: "das Frühstück, -e", en: "breakfast", hint: "1a" },
            { de: "das Gemüse, -", en: "vegetable", hint: "1a" },
            { de: "guten Appetit", en: "Enjoy your meal!", hint: "1a" },
            { de: "der/das Joghurt, -s", en: "yogurt", hint: "1a" },
            { de: "die Kartoffel, -n", en: "potato", hint: "1a" },
            { de: "der Käse (Sg.)", en: "cheese", hint: "1a" },
            { de: "das Lebensmittel, -", en: "groceries / food", hint: "1a" },
            { de: "die Marmelade, -n", en: "jam / marmalade", hint: "1a" },
            { de: "die Milch (Sg.)", en: "milk", hint: "1a" },
            { de: "das Mittagessen, -", en: "lunch", hint: "1a" },
            { de: "das Müsli, -s", en: "muesli", hint: "1a" },
            { de: "das Öl, -e", en: "oil", hint: "1a" },
            { de: "der Orangensaft, \"-e", en: "orange juice", hint: "1a" },
            { de: "der Pfeffer, -", en: "pepper", hint: "1a" },
            { de: "das Salz, -e", en: "salt", hint: "1a" },
            { de: "der Tee, -s", en: "tea", hint: "1a" },
            { de: "verbinden", en: "to connect / link", hint: "Verbinden Sie Nomen und Artikel. (1b)" },
            { de: "das Wasser, -", en: "water", hint: "1b" },
            { de: "die Muttersprache, -n", en: "mother tongue / native language", hint: "1b" }
        ]
    },
    {
        id: "kapitel-4-2a-2c", num: "Kapitel 4 (2a-2c)", name: "Einkauf & Geschäfte", emoji: "🛒",
        items: [
            { de: "die Bäckerei, -en", en: "bakery", hint: "2a" },
            { de: "ein|kaufen", en: "to shop / buy groceries", hint: "2a" },
            { de: "die Metzgerei, -en", en: "butcher's shop", hint: "2a" },
            { de: "der Supermarkt, \"-e", en: "supermarket", hint: "2a" },
            { de: "das Abendessen, -", en: "dinner / supper", hint: "2a" },
            { de: "das Brot, -e", en: "bread", hint: "2a" },
            { de: "die Gurke, -n", en: "cucumber", hint: "2a" },
            { de: "der Kaffee, -s", en: "coffee", hint: "2a" },
            { de: "der/das Keks, -e", en: "cookie / biscuit", hint: "2a" },
            { de: "der Kuchen, -", en: "cake", hint: "2a" },
            { de: "die Sahne (Sg.)", en: "cream", hint: "2a" },
            { de: "der Salat, -e", en: "salad / lettuce", hint: "2a" },
            { de: "der Schinken, -", en: "ham", hint: "2a" },
            { de: "die Schokolade, -n", en: "chocolate", hint: "2a" },
            { de: "die Suppe, -n", en: "soup", hint: "2a" },
            { de: "die Tomate, -n", en: "tomato", hint: "2a" },
            { de: "die Wurst, \"-e", en: "sausage / cold cuts", hint: "2a" },
            { de: "der Zucker (Sg.)", en: "sugar", hint: "2a" },
            { de: "der Apfel, \"-", en: "apple", hint: "2b" },
            { de: "das Geschäft, -e", en: "shop / store", hint: "2b" },
            { de: "kaufen", en: "to buy", hint: "2c" }
        ]
    },
    {
        id: "kapitel-4-3a-5b", num: "Kapitel 4 (3a-5b)", name: "Grillparty & Akkusativ", emoji: "🥩",
        items: [
            { de: "bis später", en: "see you later", hint: "3a" },
            { de: "die Einladung, -en", en: "invitation", hint: "3a" },
            { de: "das Essen, -", en: "meal / food", hint: "3a" },
            { de: "fertig", en: "ready / finished", hint: "Das Essen ist gleich fertig. (3b)" },
            { de: "gleich", en: "soon / shortly / in a moment", hint: "Das Essen ist gleich fertig. (3b)" },
            { de: "grillen", en: "to barbecue / grill", hint: "3b" },
            { de: "die Nachricht, -en", en: "message / news", hint: "Sie schreibt Paul eine Nachricht. (3b)" },
            { de: "uns", en: "us / our place", hint: "Wir grillen heute Abend bei uns. (3b)" },
            { de: "vielleicht", en: "maybe / perhaps", hint: "3b" },
            { de: "die Zeit, -en", en: "time", hint: "Wir haben morgen keine Zeit. (3b)" },
            { de: "alles", en: "everything", hint: "3b" },
            { de: "brauchen", en: "to need", hint: "3b" },
            { de: "der Einkaufszettel, -", en: "grocery list", hint: "3b" },
            { de: "das Getränk, -e", en: "drink / beverage", hint: "3b" },
            { de: "die Grillparty, -s", en: "barbecue party", hint: "3c" },
            { de: "mehr", en: "anymore / more", hint: "Wir haben keinen Käse mehr. (3c)" },
            { de: "planen", en: "to plan", hint: "3c" },
            { de: "stimmen", en: "to be correct / true", hint: "Ja, stimmt. (3c)" },
            { de: "teuer", en: "expensive", hint: "3c" },
            { de: "der Einkauf, \"-e", en: "purchase / shopping", hint: "3c ÜB" },
            { de: "die Birne, -n", en: "pear", hint: "3d" },
            { de: "der Fisch, -e", en: "fish", hint: "3d" },
            { de: "das Hähnchen, -", en: "chicken", hint: "3d" },
            { de: "die Olive, -n", en: "olive", hint: "3d" },
            { de: "die Pommes frites (Pl.)", en: "chips / french fries", hint: "3d" },
            { de: "der Reis (Sg.)", en: "rice", hint: "3d" },
            { de: "schmecken", en: "to taste", hint: "3d" },
            { de: "süß", en: "sweet", hint: "Schokolade schmeckt süß. (3d)" },
            { de: "der Akkusativ, -e", en: "accusative (grammar)", hint: "4" },
            { de: "der Nominativ, -e", en: "nominative (grammar)", hint: "4" },
            { de: "essen", en: "to eat", hint: "er isst, hat gegessen (4)" },
            { de: "zusammen", en: "together", hint: "4" },
            { de: "der Saft, \"-e", en: "juice", hint: "5a" },
            { de: "der Umlaut, -e", en: "umlaut (ä, ö, ü)", hint: "5b" }
        ]
    },
    {
        id: "kapitel-4-6a-6dub", num: "Kapitel 4 (6a-6d)", name: "Supermarkt & Mengen", emoji: "⚖️",
        items: [
            { de: "der Cent, -s", en: "cent", hint: "6a" },
            { de: "dort", en: "there / over there", hint: "6b" },
            { de: "dran|kommen", en: "to have one's turn", hint: "er kommt dran, ist drangekommen (6b)" },
            { de: "der Einkaufswagen, -", en: "shopping cart / trolley", hint: "6b" },
            { de: "der Emmentaler", en: "Emmentaler cheese", hint: "6b" },
            { de: "etwas", en: "something / anything else", hint: "Sonst noch etwas? (6b)" },
            { de: "finden", en: "to find", hint: "Wo finde ich Reis? (6b)" },
            { de: "das Gramm, -", en: "gram", hint: "6b" },
            { de: "gut", en: "alright / okay", hint: "Also gut... (6b)" },
            { de: "der Kassenzettel, -", en: "receipt", hint: "6b" },
            { de: "kosten", en: "to cost", hint: "6b" },
            { de: "machen", en: "to make / total up", hint: "Das macht 12 Euro. (6b)" },
            { de: "möchten", en: "would like", hint: "er möchte (6b)" },
            { de: "nehmen", en: "to take", hint: "Ich nehme ein Brötchen. (6b)" },
            { de: "der Preis, -e", en: "price", hint: "6b" },
            { de: "sonst", en: "otherwise / else", hint: "Sonst noch etwas? (6b)" },
            { de: "das Stück, -e", en: "piece", hint: "6b" },
            { de: "die Tüte, -n", en: "bag / paper bag", hint: "6b" },
            { de: "wechseln", en: "to change / exchange", hint: "6b" },
            { de: "wie viel, wie viele", en: "how much / how many", hint: "6b" },
            { de: "die Limonade, -n", en: "lemonade", hint: "6c" },
            { de: "recherchieren", en: "to research", hint: "6c" },
            { de: "der Becher, -", en: "cup / tub (e.g. yogurt)", hint: "6d ÜB" },
            { de: "die Dose, -n", en: "jar / can / tin", hint: "6d ÜB" },
            { de: "das Fett, -e", en: "fat", hint: "6d ÜB" },
            { de: "das Kilo, -s", en: "kilo", hint: "6d ÜB" },
            { de: "das Kilogramm, -", en: "kilogram", hint: "6d ÜB" },
            { de: "der Liter, -", en: "litre", hint: "6d ÜB" },
            { de: "das Maß, -e", en: "measure / measurement", hint: "6d ÜB" },
            { de: "die Packung, -en", en: "packet / pack", hint: "6d ÜB" },
            { de: "die Verpackung, -en", en: "packaging", hint: "6d ÜB" }
        ]
    },
    {
        id: "kapitel-4-7a-9c", num: "Kapitel 4 (7a-9c)", name: "Mahlzeiten & Gewohnheiten", emoji: "🍕",
        items: [
            { de: "gerne", en: "with pleasure", hint: "7a" },
            { de: "gleichfalls", en: "likewise / same to you", hint: "7a" },
            { de: "lecker", en: "tasty / delicious", hint: "7a" },
            { de: "satt", en: "full (not hungry anymore)", hint: "7b" },
            { de: "die Mahlzeit, -en", en: "meal", hint: "Mahlzeit! (Enjoy your meal!) (7b)" },
            { de: "die Frau, -en", en: "woman / wife", hint: "Die Frau trinkt gern Tee. (8a)" },
            { de: "der Mann, \"-er", en: "man / husband", hint: "Der Mann möchte ein Brötchen. (8a)" },
            { de: "trinken", en: "to drink", hint: "er trinkt, hat getrunken (8a)" },
            { de: "abends", en: "in the evening", hint: "9a" },
            { de: "allein", en: "alone", hint: "9a" },
            { de: "die Arbeit, -en", en: "work / job", hint: "9a" },
            { de: "asiatisch", en: "Asian", hint: "9a" },
            { de: "der Döner, -", en: "kebab", hint: "9a" },
            { de: "frühstücken", en: "to eat breakfast", hint: "9a" },
            { de: "gesund", en: "healthy", hint: "9a" },
            { de: "halb", en: "half past", hint: "Ich frühstücke um halb acht. (9a)" },
            { de: "die Kantine, -n", en: "canteen / cafeteria", hint: "9a" },
            { de: "manchmal", en: "sometimes", hint: "9a" },
            { de: "mittags", en: "at noon / lunchtime", hint: "9a" },
            { de: "mögen", en: "to like", hint: "er mag, hat gemocht (9a)" },
            { de: "der Morgen, -", en: "morning", hint: "9a" },
            { de: "morgens", en: "in the morning", hint: "9a" },
            { de: "nachmittags", en: "in the afternoon", hint: "9a" },
            { de: "nichts", en: "nothing", hint: "9a" },
            { de: "nur", en: "only", hint: "9a" },
            { de: "das Obst (Sg.)", en: "fruit", hint: "9a" },
            { de: "die Pizza, -s / Pizzen", en: "pizza", hint: "9a" },
            { de: "schlafen", en: "to sleep", hint: "er schläft, hat geschlafen (9a)" },
            { de: "das Sushi, -s", en: "sushi", hint: "9a" },
            { de: "um", en: "at (time)", hint: "Abends um sieben essen wir. (9a)" },
            { de: "vormittags", en: "in the morning (before noon)", hint: "9a" },
            { de: "wach", en: "awake", hint: "9a" },
            { de: "wenig", en: "little / a bit / few", hint: "9a" },
            { de: "erzählen", en: "to tell / narrate", hint: "9b" },
            { de: "der Vormittag, -e", en: "morning (before noon)", hint: "9c" }
        ]
    },
    {
        id: "kapitel-4-10a-kurz", num: "Kapitel 4 (10a-KK)", name: "Küchenberufe & Mindmap", emoji: "👨‍🍳",
        items: [
            { de: "die Mindmap, -s", en: "mind map", hint: "10a" },
            { de: "das Paar, -e", en: "pair / couple", hint: "10b" },
            { de: "das Thema, Themen", en: "topic / theme", hint: "10b" },
            { de: "die Assoziation, -en", en: "association", hint: "10c" },
            { de: "ein|fallen", en: "to come to mind", hint: "es fällt ein, ist eingefallen (10c)" },
            { de: "frei", en: "free", hint: "Sammeln Sie freie Assoziationen. (10c)" },
            { de: "die Methode, -n", en: "method", hint: "10c" },
            { de: "thematisch", en: "topical / thematic", hint: "10c" },
            { de: "die Wortgruppe, -n", en: "word group", hint: "10c" },
            { de: "rund um", en: "all around / all about", hint: "Berufe rund ums Essen (11)" },
            { de: "als", en: "as", hint: "Max arbeitet als Koch. (11)" },
            { de: "die Altstadt, \"-e", en: "historic city / old town", hint: "11" },
            { de: "am", en: "at the / on the", hint: "Max ist Koch am Bodensee. (11)" },
            { de: "die Arbeitszeit, -en", en: "working hours", hint: "11" },
            { de: "beantworten", en: "to answer", hint: "11" },
            { de: "der Champignon, -s", en: "mushroom", hint: "11" },
            { de: "Chef", en: "boss / chef (male)", hint: "11" },
            { de: "die Chefin, -nen", en: "boss (female)", hint: "11" },
            { de: "das Dessert, -s", en: "dessert", hint: "11" },
            { de: "echt", en: "really / real", hint: "Das ist dann echt stressig! (11)" },
            { de: "das Fischgericht, -e", en: "fish dish", hint: "11" },
            { de: "frisch", en: "fresh", hint: "11" },
            { de: "das Gericht, -e", en: "dish / meal", hint: "11" },
            { de: "helfen", en: "to help", hint: "er hilft, hat geholfen (11)" },
            { de: "klein", en: "small", hint: "11" },
            { de: "kreativ", en: "creative", hint: "11" },
            { de: "länger", en: "longer", hint: "11" },
            { de: "natürlich", en: "of course / naturally", hint: "11" },
            { de: "nett", en: "nice / kind", hint: "11" },
            { de: "normalerweise", en: "normally", hint: "11" },
            { de: "probieren", en: "to try / taste", hint: "11" },
            { de: "schälen", en: "to peel", hint: "11" },
            { de: "schneiden", en: "to cut / chop", hint: "er schneidet, hat geschnitten (11)" },
            { de: "seit", en: "since / for", hint: "seit zwei Jahren (11)" },
            { de: "der Spaß (Sg.)", en: "fun", hint: "Kochen macht Spaß. (11)" },
            { de: "stressig", en: "stressful", hint: "11" },
            { de: "das Team, -s", en: "team", hint: "11" },
            { de: "Uhr", en: "o'clock / hours", hint: "Ich arbeite von 6 bis 15 Uhr. (11)" },
            { de: "waschen", en: "to wash", hint: "er wäscht, hat gewaschen (11)" },
            { de: "wichtig", en: "important", hint: "11" },
            { de: "zu|bereiten", en: "to prepare / cook", hint: "11" },
            { de: "zurück", en: "back", hint: "11" },
            { de: "führen", en: "to lead / have", hint: "ein Gespräch führen (Kurz und klar)" },
            { de: "unregelmäßig", en: "irregular", hint: "unregelmäßige Verben (Kurz und klar)" },
            { de: "die Vorliebe, -n", en: "preference / liking", hint: "Kurz und klar" }
        ]
    }
];
